IF
Global("CbRopeBridgeMade","AR4330",3)
InMyArea("Pellig")   
Global("CbRopeBridgeP","AR4330",0)
Delay(10)
THEN
RESPONSE #100
ActionOverride("Pellig",JumpToPoint([249.428]))
SetGlobal("CbRopeBridgeP","AR4330",1)
END


IF
Global("CbRopeBridgeMade","AR4330",3)
Global("CbRopeBridgeH","AR4330",0)
InMyArea("Haiass")
Delay(6)
THEN
RESPONSE #100
ActionOverride("Haiass",JumpToPoint([276.68]))
SetGlobal("CbRopeBridgeH","AR4330",1)
END
