IF
GlobalLT("SanDoctor","GLOBAL",10)
Global("DocWasHere","BG3402",0)
THEN
RESPONSE #100
IncrementGlobal("SanDoctor","GLOBAL",1)
ActionOverride("CVSandr",AddSpecialAbility("SpHeal2"))
SetGlobal("DocWasHere","BG3402",1)
END

IF
Global("wyvernp","GLOBAL",0)
OR(2)
GlobalGT("Homesail","Global",8)
GlobalGT("Chapter","Global",5)
!PartyHasItem("Misc52")
!InParty("Coran")
THEN
RESPONSE #100
SetGlobal("wyvernp","GLOBAL",1)
END