IF
GlobalLT("SanDoctor","GLOBAL",4)
Global("DocWasHere","bg0002",0)
THEN
RESPONSE #100
IncrementGlobal("SanDoctor","GLOBAL",1)
ActionOverride("CVSandr",AddSpecialAbility("sanhand"))
SetGlobal("DocWasHere","bg0002",1)
END

IF
GlobalGT("SanDoctor","GLOBAL",3)
GlobalLT("SanDoctor","GLOBAL",10)
Global("DocWasHere","bg0002",0)
THEN
RESPONSE #100
IncrementGlobal("SanDoctor","GLOBAL",1)
ActionOverride("CVSandr",AddSpecialAbility("sanhand"))
SetGlobal("DocWasHere","bg0002",1)
END