IF
OnCreation()
Global("OpenArcive","cvtml1",0)
GlobalLT("SanKhalBlood","GLOBAL",9)
THEN
RESPONSE #100
SetGlobal("OpenArcive","cvtml1",1)
TriggerActivation("InnerArchive2",FALSE)
END

IF
GlobalGT("SanKhalBlood","GLOBAL",8)
Global("OpenArcive","cvtml1",1)
THEN
RESPONSE #100
SetGlobal("OpenArcive","cvtml1",2)
TriggerActivation("InnerArchive2",TRUE)
END

IF
AreaCheck("CVTML1")
Global("SandragQuestn","cvtml1",0)
THEN
RESPONSE #100
SetGlobal("SandragQuestn","cvtml1",1)
END