IF
Global("Helpers","LOCALS",0)
AreaCheck("BG2200")
THEN
RESPONSE #100
CreateCreature("CVBanDE1",[3700.2040],0)
CreateCreature("CVBanDE1",[3700.2040],0)
CreateCreature("CVBanDE1",[3700.2040],0)
CreateCreature("CVBanDE1",[3700.2040],0)
CreateCreature("CVBanDE1",[3700.2040],0)
CreateCreature("CVBanDE1",[3700.2040],0)
CreateCreature("CVBanDE1",[3700.2040],0)
CreateCreature("CVBanDE1",[3700.2040],0)
SetGlobal("Helpers","LOCALS",1)
END