/*Set Romance Path*/

IF
NumTimesTalkedTo(0)
See([PC])
Gender(Player1,MALE)
THEN
RESPONSE #100
SetGlobal("SanRomPath","GLOBAL",1)
RealSetGlobalTimer("SanDreamTalkTime","GLOBAL",TWENTY_MINUTES)
RealSetGlobalTimer("SanFlirTi","GLOBAL",7200)
Dialogue(Nearest([PC]))
END

IF
NumTimesTalkedTo(0)
See([PC])
Gender(Player1,FEMALE)
THEN
RESPONSE #100                                   
SetGlobal("SanRomPath","GLOBAL",2)
RealSetGlobalTimer("SanDreamTalkTime","GLOBAL",TWENTY_MINUTES)
RealSetGlobalTimer("SanFlirTi","GLOBAL",7200)
Dialogue(Nearest([PC]))
END

IF
Global("SandrahJoined","GLOBAL",1)
Global("SanMoTiStart","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanMoTiStart","LOCALS",1)
RealSetGlobalTimer("SandrahMorningTalkTime","GLOBAL",90)
END

IF
See([PC])
Global("SandrahJoined","GLOBAL",6)
Global("SanBG2Rejoin","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanBG2Rejoin","GLOBAL",1)
MoveToObject(Player1)
Dialogue(Nearest([PC]))
END

//Flirt triggers

IF
RealGlobalTimerExpired("SanFlirTi","GLOBAL")
InParty(Myself)
!AreaCheck("BG5000")
OR(4)
Global("SanFlirt","GLOBAL",0)
Global("SanFlirt","GLOBAL",2)
Global("SanFlirt","GLOBAL",4)
Global("SanFlirt","GLOBAL",6)
THEN
RESPONSE #100
IncrementGlobal("SanFlirt","GLOBAL",1)
END

IF
RealGlobalTimerExpired("SanFlirTi","GLOBAL")
InParty(Myself)
Global("SanPidPack","GLOBAL",9)
Global("SanFlirt","GLOBAL",8)
THEN
RESPONSE #100
IncrementGlobal("SanFlirt","GLOBAL",1)
END

IF
!Global("endofbg1","GLOBAL",2)
RealGlobalTimerExpired("SanFlirTi","GLOBAL")
GlobalGT("Chapter","Global",3)
InParty(Myself)
Global("SanFlirt","GLOBAL",10)
GlobalLT("Sanpoints","GLOBAL",29)
Global("Sanbehbast","LOCALS",0)
!AreaCheck("BG1901")
THEN
RESPONSE #100
SetGlobal("Sanbehbast","LOCALS",1)
END

IF
!Global("endofbg1","GLOBAL",2)
RealGlobalTimerExpired("SanFlirTi","GLOBAL")
GlobalGT("Chapter","Global",4)
InParty(Myself)
GlobalLT("Sanpoints","GLOBAL",47)
GlobalLT("Sanbehbast","LOCALS",3)
!AreaCheck("BG1803")
AreaType(OUTDOOR)
THEN
RESPONSE #100
SetGlobal("Sanbehbast","LOCALS",3)
END

IF
!Global("endofbg1","GLOBAL",2)
RealGlobalTimerExpired("SanFlirTi","GLOBAL")
GlobalGT("Chapter","Global",3)
InParty(Myself)
Global("SanFlirt","GLOBAL",10)
GlobalGT("Sanpoints","GLOBAL",30)
!AreaCheck("BG1901")
THEN
RESPONSE #100
IncrementGlobal("SanFlirt","GLOBAL",1)
END

IF
RealGlobalTimerExpired("SanFlirTi","GLOBAL")
GlobalGT("Chapter","Global",5)
!AreaCheck("BG0900")
InParty(Myself)
OR(3)
Global("SanFlirt","GLOBAL",12)
Global("SanFlirt","GLOBAL",14)
Global("SanFlirt","GLOBAL",16)
THEN
RESPONSE #100
IncrementGlobal("SanFlirt","GLOBAL",1)
END

IF
InParty(Myself)
RealGlobalTimerExpired("SanFlirTi","GLOBAL")
Global("SanFlirt","GLOBAL",18)
GlobalGT("SanLibCommt2","LOCALS",1)
THEN
RESPONSE #100
IncrementGlobal("SanFlirt","GLOBAL",1)
END

IF
InParty(Myself)
!See([ENEMY])
See(Player1)
!StateCheck(Player1,CD_STATE_NOTVALID)
CombatCounter(0)
!AreaType(DUNGEON)
OR(12)
Global("SanFlirt","GLOBAL",1)
Global("SanFlirt","GLOBAL",3)
Global("SanFlirt","GLOBAL",5)
Global("SanFlirt","GLOBAL",7)
Global("SanFlirt","GLOBAL",9)
Global("SanFlirt","GLOBAL",11)
Global("SanFlirt","GLOBAL",13)
Global("SanFlirt","GLOBAL",15)
Global("SanFlirt","GLOBAL",17)
Global("SanFlirt","GLOBAL",19)
Global("Sanbehbast","LOCALS",1)
Global("Sanbehbast","LOCALS",3)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogNoSet("CVSandr")
END

// Mystra Make Good
IF
Global("SanPCGoodMys","GLOBAL",2)
THEN
RESPONSE #100
SetGlobal("SanPCGoodMys","GLOBAL",3)
ClearAllActions()
StartCutSceneMode()
StartCutScene("SanmysG")
END

IF
Global("SanPCGoodMys","GLOBAL",4)
THEN
RESPONSE #100
SetGlobal("SanPCGoodMys","GLOBAL",5)
ClearAllActions()
StartCutSceneMode()
StartCutScene("SanMysGR")
END

// Haiass Joins Sandrah

IF
AreaCheck("bg2700")
InParty("CVSandr")
GlobalLT("HaiassLevel","GLOBAL",2)
!InMyArea("Haiass")
!PartyHasItem("silhai")
!Global("HAIASSQUIETO","GLOBAL",1)
Global("HaiassMiss","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("HaiassMiss","LOCALS",1)
RealSetGlobalTimer("HaiassMissTime","LOCALS",240)
END

IF
Global("HaiassMiss","LOCALS",1)
RealGlobalTimerExpired("HaiassMissTime","LOCALS")
GlobalLT("HaiassLevel","GLOBAL",2)
!InMyArea("Haiass")
CombatCounter(0)
!See([ENEMY])
!PartyHasItem("silhai")
!Global("HAIASSQUIETO","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("HaiassMiss","LOCALS",2)
SetGlobal("HaiassJoinSan","GLOBAL",1)
SetGlobal("HaiassLevel","GLOBAL",1)
CreateCreatureObject("Haiass1",Myself,0,0,0)
END

IF
Global("HaiassJoinSan","GLOBAL",2)
THEN
RESPONSE #100
MakeGlobal()
SetGlobal("HaiassSeUne","GLOBAL",1)
SetGlobal("HaiassQuieto","GLOBAL",0)
SetGlobal("HaiassJumpOn","GLOBAL",1)
SetGlobal("HaiassDesdeBg","GLOBAL",0)
SetGlobal("HaiassJoinSan","GLOBAL",2)
GiveItemCreate("silhai",Player1,0,0,0)
SetGlobal("HaiassJoinSan","GLOBAL",3)
END


//Hates Red Wizards
IF
HasItem("CMCLCK07",Myself)
THEN
RESPONSE #100
DropItem("CMCLCK07",[-1.-1])
DisplayStringWait(Myself,@192)
END

IF
HasItem("PSRing01",Myself)
THEN
RESPONSE #100
DropItem("PSRing01",[-1.-1])
DisplayStringWait(Myself,@192)
END

IF
HasItem("Soaitm06",Myself)
THEN
RESPONSE #100
DropItem("Soaitm06",[-1.-1])
DisplayStringWait(Myself,@192)
END


/*Trigger Imoen Reminder*/

IF
AreaCheck("bg2700")
GlobalLT("Chapter","Global",2)
InParty("CVSandr")
!InParty("Imoen2")
!Dead("Imoen2")
Global("Imoreminder","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("Imoreminder","GLOBAL",1)
END

IF
Global("Imoreminder","GLOBAL",1)
!InParty("imoen2")
!Dead("Imoen2")
THEN
RESPONSE #100
SetGlobal("Imoreminder","GLOBAL",2)
RealSetGlobalTimer("ReturnImoTime","GLOBAL",300)
END

IF
Global("Imoreminder","GLOBAL",2)
!InParty("imoen2")
!Dead("Imoen2")
RealGlobalTimerExpired("ReturnImoTime","GLOBAL")
THEN
RESPONSE #100
SetGlobal("Imoreminder","GLOBAL",3)
END

IF
Global("Imoreminder","GLOBAL",4)
InParty("imoen2")
CombatCounter(0)
THEN
RESPONSE #100
SetGlobal("Imoreminder","GLOBAL",5)
MoveToObject(Player1)
StartDialogNoSet("CVSandr")
END


/* Morning Talks*/
IF
InParty(Myself)
PartyRested()
!See([ENEMY])
RealGlobalTimerExpired("SandrahMorningTalkTime","GLOBAL")
OR(3)
Global("SandrahMorningTalk","GLOBAL",0)
Global("SandrahMorningTalk","GLOBAL",2)
Global("SandrahMorningTalk","GLOBAL",12)
THEN
RESPONSE #100
IncrementGlobal("SandrahMorningTalk","GLOBAL",1)
END

IF
InParty(Myself)
PartyRested()
!See([ENEMY])
RealGlobalTimerExpired("SandrahMorningTalkTime","GLOBAL")
Global("SandrahMorningTalk","GLOBAL",4)
Global("SanRomPath","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("SandrahMorningTalk","GLOBAL",5)
END

IF
InParty(Myself)
PartyRested()
!See([ENEMY])
Global("SandrahMorningTalk","GLOBAL",4)
Global("SanRomPath","GLOBAL",2)
RealGlobalTimerExpired("SandrahMorningTalkTime","GLOBAL")
THEN
RESPONSE #100
SetGlobal("SandrahMorningTalk","GLOBAL",6)
END

IF
PartyRested()
!See([ENEMY])
RealGlobalTimerExpired("SandrahMorningTalkTime","GLOBAL")
Global("SanRomPath","GLOBAL",1)
Global("SandrahMorningTalk","GLOBAL",7)
InParty(Myself)
THEN
RESPONSE #100
SetGlobal("SandrahMorningTalk","GLOBAL",8)
END

IF
InParty(Myself)
PartyRested()
!See([ENEMY])
RealGlobalTimerExpired("SandrahMorningTalkTime","GLOBAL")
Global("SanRomPath","GLOBAL",2)
Global("SandrahMorningTalk","GLOBAL",7)
THEN
RESPONSE #100
SetGlobal("SandrahMorningTalk","GLOBAL",9)
END

IF
Global("SandrahMorningTalk","GLOBAL",11)
InParty("CVSandr")
AreaCheck("BG3402")
THEN
RESPONSE #100 
SetGlobal("SandrahMorningTalk","GLOBAL",12)
SetGlobal("SanBranRepl","GLOBAL",1) 
RealSetGlobalTimer("SandrahMorningTalkTime","GLOBAL",1800)
END

IF
PartyRested()
!See([ENEMY])
Global("SANDRAHLT","GLOBAL",3)
GlobalLT("Formedcloth","GLOBAL",6)
AreaType(OUTDOOR)
TimeGT(4)
TimeLT(DAWN_END)
THEN
RESPONSE #100
SetGlobal("SANDRAHLT","GLOBAL",4)
END

IF
Global("SANDRAHLT","GLOBAL",5) 
RealGlobalTimerExpired("SandrahMorningTalkTime","GLOBAL")
GlobalGT("SankillBg1","GLOBAL",750)
THEN
RESPONSE #100
SetGlobal("SANDRAHLT","GLOBAL",6)
END

IF
AreaCheck("BG0515")
Global("SanDurlAnsw","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanDurlAnsw","LOCALS",1)
END

IF
AreaCheck("bg2300")
Global("DuerFAInn","GLOBAL",0)
Dead("Duearc01")
THEN
RESPONSE #100
SetGlobal("DuerFAInn","GLOBAL",1)
END

// Sympathy Points

IF
GlobalGT("Sanpoints","GLOBAL",39)
Global("Sancharm","LOCALS",2)
ReputationGT(Player1,14)
TimeGT(20)
AreaType(OUTDOOR)
!AreaType(CITY)
THEN
RESPONSE #100
SetGlobal("Sancharm","LOCALS",3)
END

IF
Global("Sancharm","LOCALS",4)
Delay(6)
THEN
RESPONSE #100
SetGlobal("Sancharm","LOCALS",5)
CreateVisualEffectObject("SPFLESHS",Player1) 
ActionOverride(Player1,AddSpecialAbility("cvheal"))
ActionOverride("CVSandr",AddSpecialAbility("cvheal"))
END

IF
Global("Sancharm","LOCALS",5)
Delay(6)
THEN
RESPONSE #100
AddXPObject("CVSandr",3000)
SetGlobal("Sancharm","LOCALS",6)
END

//Haiass Friend Talk

IF
InMyArea("Haiass")
!AreaType(CITY)
AreaType(FOREST)
CombatCounter(0)
GlobalGT("SandrahMorningTalk","GLOBAL",5)
Global("HaiassFr","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("HaiassFr","GLOBAL",1)
MoveToObject("Haiass")
Interact("CVSandr")
END

// Haiass and Pelligram

IF
InMyArea("Haiass")
InMyArea("Pellig")
HPPercentLT("Haiass",60)
HPPercentGT("Haiass",0)
Global("HaiassHurt","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("HaiassHurt","GLOBAL",1)
Interact("CVSandr")
END

IF
InMyArea("Haiass")
InMyArea("Pellig")
AreaCheck("bg2300")
Global("HaiassPellRom","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("HaiassPellRom","GLOBAL",1)
RealSetGlobalTimer("HaiassPellT","GLOBAL",1800)
END

IF
RealGlobalTimerExpired("HaiassPellT","GLOBAL")
Global("HaiassPellRom","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("HaiassPellRom","GLOBAL",2)
END

IF
InMyArea("Haiass")
InMyArea("Pellig")
Global("HaiassPellRom","GLOBAL",2)
AreaType(FOREST)
TimeOfDay(NIGHT)
THEN
RESPONSE #100
SetGlobal("HaiassPellRom","GLOBAL",3)
END

IF
InMyArea("Haiass")
InMyArea("Pellig")
Global("HaiassPellRom","GLOBAL",4)
TimeOfDay(DAY)
OR(8)
AreaCheck("BG0200")
AreaCheck("BG0300")
AreaCheck("BG0600")
AreaCheck("BG0700")
AreaCheck("BG0800")
AreaCheck("bg1100")
AreaCheck("bg1200")
AreaCheck("bg1300")
THEN
RESPONSE #100
SetGlobal("HaiassPellRom","GLOBAL",5)
END

IF
InMyArea("Haiass")
InMyArea("Pellig")
Global("HaiassPellRom","GLOBAL",6)
TimeOfDay(DAY)
OR(6)
AreaCheck("BG4200")
AreaCheck("BG4600")
AreaCheck("BG5200")
AreaCheck("BG0400")
AreaCheck("BG0900")
AreaCheck("BG2400")
OR(2)
See("rabbit01")
See("rabbit")
THEN
RESPONSE #100
SetGlobal("HaiassPellRom","GLOBAL",7)
END

//  Boo and Pelligram
IF
!Global("EndofBG1","Global",2)
InMyArea("Pellig")
InParty("Minsc")
!AreaCheck("BG4800")
!AreaType(DUNGEON)
GlobalGT("SanVisitedWD","GLOBAL",1)
Global("SanBooPel","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanBooPel","GLOBAL",1)
END

IF
Global("EndofBG1","Global",2)
InMyArea("Pellig")
InParty("Minsc")
Global("HaiassJumpOn","GLOBAL",1)
!AreaType(DUNGEON)
Global("SanBooPel","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanBooPel","GLOBAL",11)
END

IF
!Global("EndofBG1","Global",2)
InParty("Minsc")
AreaType(CITY)
!AreaCheck("BG4800")
TimeOfDay(NIGHT)
Global("SanBooTlk","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanBooTlk","GLOBAL",1)
END

IF
Global("EndofBG1","Global",2)
InParty("Minsc")
AreaType(CITY)
!AreaCheck("ar0700")
TimeOfDay(NIGHT)
Global("SanBooTlk","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanBooTlk","GLOBAL",21)
END

IF
Global("SanBooTlk","GLOBAL",2)
InParty("Minsc")
HPPercentLT("Minsc",70)
THEN
RESPONSE #100
SetGlobal("SanBooTlk","GLOBAL",3)
END

IF
Global("SanBooTlk","GLOBAL",22)
InParty("Minsc")
HPPercentLT("Minsc",70)
THEN
RESPONSE #100
SetGlobal("SanBooTlk","GLOBAL",23)
END

IF
Global("SanBooTlk","GLOBAL",4)
RealGlobalTimerExpired("SanMinskInt","GLOBAL")
!TimeOfDay(NIGHT)
AreaType(FOREST)
InParty("Minsc")
!Global("EndofBG1","Global",2)
THEN
RESPONSE #100
SetGlobal("SanBooTlk","GLOBAL",5)
END

IF
Global("SanBooTlk","GLOBAL",6)
RealGlobalTimerExpired("SanMinskInt","GLOBAL")
InParty("Minsc")
!AreaType(DUNGEON)
!Global("EndofBG1","Global",2)
THEN
RESPONSE #100
SetGlobal("SanBooTlk","GLOBAL",7)
END

IF
Global("SanBooTlk","GLOBAL",10)
RealGlobalTimerExpired("SanMinskInt","GLOBAL")
AreaType(FOREST)
InParty("Minsc")
THEN
RESPONSE #100
SetGlobal("SanBooTlk","GLOBAL",11)
END

IF
!Global("EndofBG1","Global",2)
GlobalGT("SanBooTlk","GLOBAL",3)
AreaType(DUNGEON)
InParty("Minsc")
Global("SanMinsDung","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanMinsDung","LOCALS",1)
END

IF
Global("EndofBG1","Global",2)
GlobalGT("SanBooTlk","GLOBAL",3)
AreaType(DUNGEON)
InParty("Minsc")
Global("SanMinsDung","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanMinsDung","LOCALS",11)
END

IF
InParty("Minsc")
GlobalGT("SanBooTlk","GLOBAL",6)
HPPercentLT("Minsc",60)
HPPercentGT("Minsc",0)
Global("SanMinsHur2","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanMinsHur2","LOCALS",1)
END

IF
InParty("Minsc")
GlobalGT("SanBooTlk","GLOBAL",6)
Global("SanMinsParty","LOCALS",0)
OR(9)
InMyArea("Tazok")
InMyArea("Tazok2")
InMyArea("Basilmut")
InMyArea("Basilnat")
InMyArea("ATR'JKLSAD'ROA'CH")
InMyArea("DSShar")
InMyArea("Jabbress")
InMyArea("BW05Gra0")
InMyArea("BW05Grac")
THEN
RESPONSE #100
SetGlobal("SanMinsParty","LOCALS",1)
END

IF
InParty("Minsc")
Global("SanMinsParty","LOCALS",2)
CombatCounter(0)
Delay(18)
OR(9)
Dead("Venkt")
Dead("Tazok2")
Dead("Basilmut")
Dead("Basilnat")
Dead("ATR'JKLSAD'ROA'CH")
Dead("DSShar")
Dead("Jabbress")
Dead("BW05Gra0")
Dead("BW05Grac")
THEN
RESPONSE #100
SetGlobal("SanMinsParty","LOCALS",3)
END

IF
Global("X#MinscBoo","GLOBAL",1)
!AreaCheck("BG0800")
InParty("Minsc")
THEN
RESPONSE #100
SetGlobal("X#MinscBoo","GLOBAL",2)
END

IF
Global("X#MinscBoo","GLOBAL",3) 
RealGlobalTimerExpired("SanMinskInt","GLOBAL")
InParty("Minsc")
InParty("Dynaheir")
TimeGT(20)
!AreaType(CITY)
THEN
RESPONSE #100
SetGlobal("X#MinscBoo","GLOBAL",4)
END

IF
See("Minsc")
!See([ENEMY])
CombatCounter(0)
!StateCheck("Minsc",CD_STATE_NOTVALID)
OR(15)
Global("SanBooPel","GLOBAL",1)
Global("SanBooTlk","GLOBAL",1)
Global("SanBooTlk","GLOBAL",3)
Global("SanBooTlk","GLOBAL",5)
Global("SanBooTlk","GLOBAL",7)
Global("SanMinsDung","LOCALS",1)
Global("SanBooTlk","GLOBAL",11)
Global("SanMinsHur2","LOCALS",1)
Global("SanMinsParty","LOCALS",1)
Global("SanMinsParty","LOCALS",3)
Global("X#MinscBoo","GLOBAL",2)
Global("SanBooPel","GLOBAL",11)
Global("SanBooTlk","GLOBAL",21)
Global("SanBooTlk","GLOBAL",23)
Global("SanMinsDung","LOCALS",11)
THEN
RESPONSE #100
Interact("CVSandr")
END

IF
Global("SanHamstSp","LOCALS",0)
GlobalGT("SanShauMinsc","GLOBAL",31)
THEN
RESPONSE #100
SetGlobal("SanHamstSp","LOCALS",1)
AddSpecialAbility("CVDrag10")
END

// Friendship Talks
IF
!AreaCheck("bg2300")
!AreaCheck("BG3300")
!AreaCheck("bg2700")
!AreaCheck("bg2800")
!See([ENEMY])
!AreaType(DUNGEON)
Global("SanFT","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanFT","GLOBAL",1)
END

IF
See(Player1)
!StateCheck(Player1,CD_STATE_NOTVALID)
CombatCounter(0)
!StateCheck(Myself,CD_STATE_NOTVALID)
Global("BG1FlirtHeal","LOCALS",0)
HPPercentLT(Player1,80)
THEN
RESPONSE #100
ReallyForceSpellRES("SanHand",Player1)
SetGlobal("BG1FlirtHeal","LOCALS",1)
END

IF
RealGlobalTimerExpired("SanFTWait","GLOBAL")
Global("SanFT","GLOBAL",2)
AreaType(CITY)
THEN
RESPONSE #100
SetGlobal("SanFT","GLOBAL",3)
END

IF
RealGlobalTimerExpired("SanFTWait","GLOBAL")
Global("SanFT","GLOBAL",4)
!AreaType(OUTDOOR)
!AreaType(DUNGEON)
THEN
RESPONSE #100
SetGlobal("SanFT","GLOBAL",5)
END

IF
GlobalGT("SanFT","GLOBAL",2)
Global("Sanhors","GLOBAL",0)
OR(2)
See("Horsesa")
See("Horse01")
THEN
RESPONSE #100
SetGlobal("Sanhors","GLOBAL",1)
END

/* First Lovetalk*/
IF
InParty(Myself)
!See([ENEMY])
CombatCounter(0)
Global("SandrahLT","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("SandrahLT","GLOBAL",2)
END

IF
InMyArea("Pellig")
GlobalGT("Sanft","GLOBAL",5)
GlobalGT("Santlove","GLOBAL",7)
!TimeOfDay(DAY)
!AreaType(CITY)
AreaType(OUTDOOR)
Global("SanPussMis","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanPussMis","GLOBAL",1)
END

// Feldebath
IF
Global("SanFeldeTalk","GLOBAL",0)
InParty(Myself)
!See([ENEMY])
AreaCheck("BG3351")
Global("SanFeldeW","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanFeldeW","LOCALS",1)
RealSetGlobalTimer("SanFeldeWTi","LOCALS",3)
END

IF
Global("SanFeldeW","LOCALS",1)
RealGlobalTimerExpired("SanFeldeWTi","LOCALS")
THEN
RESPONSE #100
SetGlobal("SanFeldeW","LOCALS",2)
SetGlobal("SanFeldeTalk","GLOBAL",1)
END


// Balduran's Island
IF
Global("kaishas1","GLOBAL",1)
Global("SanOnBalduIsl","GLOBAL",0)
!Dead("kaishwlf")
!Global("DMWWNoKillKaishas","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("SanOnBalduIsl","GLOBAL",1)
END

IF
Global("SanOnBalduIsl","GLOBAL",1)
OR(2)
Dead("kaishwlf")
Global("DMWWNoKillKaishas","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("SanOnBalduIsl","GLOBAL",2)
END

IF
Global("SanOnBalduIsl","GLOBAL",2)
AreaCheck("BG1004")
THEN
RESPONSE #100
SetGlobal("SanOnBalduIsl","GLOBAL",3)
END

IF
Global("SanOnBalduIsl","GLOBAL",1)
AreaCheck("BG1500")
Global("SanPackW","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanPackW","LOCALS",1)
END

IF
Global("SanPackW","LOCALS",2)
AreaCheck("BG1500")
Dead("karoug")
THEN
RESPONSE #100
SetGlobal("SanPackW","LOCALS",3)
END

IF
Global("DMWWKaishasChat","GLOBAL",1)
Global("DMWWNoKillKaishas","GLOBAL",1)
Global("SanPackW","LOCALS",4)
THEN
RESPONSE #100
SetGlobal("SanPackW","LOCALS",5)
END

IF
Global("SanVsTalos","GLOBAL",1)
Global("SantalosDec","GLOBAL",0)
AreaCheck("ar9pba")
See("NTMilea")
THEN
RESPONSE #100
SetGlobal("SantalosDec","GLOBAL",1)
END

IF
Global("SanVsTalos","GLOBAL",1)
Global("Charlestonmoved","GLOBAL",2)
Global("SantalIdl","GLOBAL",0)
!AreaCheck("BG4101")
!AreaCheck("BG4100")
AreaType(OUTDOOR)
CombatCounter(0)
!See([Enemy])
PartyHasItem("misc48")
Delay(24)
THEN
RESPONSE #100
ClearAllActions()
StartCutSceneMode()
FadeToColor([20.0],0)
StorePartyLocations()
SmallWait(2)
ActionOverride(Player1,LeaveAreaLUA("CVtal1","",[1214.665],5))
ActionOverride(Player2,LeaveAreaLUA("CVtal1","",[647.557],4))
ActionOverride(Player3,LeaveAreaLUA("CVtal1","",[1068.844],6))
ActionOverride(Player4,LeaveAreaLUA("CVtal1","",[615.622],3))
ActionOverride(Player5,LeaveAreaLUA("CVtal1","",[633.761],7))
ActionOverride(Player6,LeaveAreaLUA("CVtal1","",[706.496],5))
FadeFromColor([30.0],0)
EndCutSceneMode()
SetGlobal("SantalIdl","GLOBAL",1)
END


//Trolls

IF
Global("SanDesTroll","LOCALS",0)
OR(2)
See("Trolde01")
See("Trolde02")
THEN
RESPONSE #100
SetGlobal("SanDesTroll","LOCALS",1)
DialogInterrupt(TRUE)
StartDialogNoSet("CVSandr")
END

IF
Global("SanDesTroll","LOCALS",5)
!AreaType(FOREST)
THEN
RESPONSE #100
SetGlobal("SanDesTroll","LOCALS",2)
END

IF
Global("SanDesTroll","LOCALS",3)
AreaType(FOREST)
!See([ENEMY])
See(Player1)
!StateCheck(Player1,CD_STATE_NOTVALID)
CombatCounter(0)
Delay(12)
THEN
RESPONSE #100
SetGlobal("SanDesTroll","LOCALS",4)
END

//Eldoth
IF
InParty("Eldoth")
GlobalLT("Chapter","GLOBAL",6)
Global("SanEldoDisl","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanEldoDisl","LOCALS",1) 
RealSetGlobalTimer("HaiassMissTime","LOCALS",240)
END

IF
InParty("Eldoth")
RealGlobalTimerExpired("HaiassMissTime","LOCALS")
OR(2)
Global("SanEldoDisl","LOCALS",1)
Global("SanEldoDisl","LOCALS",6)
THEN
RESPONSE #100
IncrementGlobal("SanEldoDisl","LOCALS",1)
END

IF
Global("X#BentEld","GLOBAL",1)
Global("SanEldoDisl","LOCALS",3)
THEN
RESPONSE #100
SetGlobal("SanEldoDisl","LOCALS",4)
END

IF
Global("SanEldoDisl","LOCALS",5)
InParty("Eldoth")
!AreaCheck("bg2300")
AreaType(FOREST)
THEN
RESPONSE #100
SetGlobal("SanEldoDisl","LOCALS",6)
RealSetGlobalTimer("HaiassMissTime","LOCALS",240)
END

IF
Global("SanEldoDisl","LOCALS",7)
InParty("Eldoth")
!See([ENEMY])
See(Player1)
!StateCheck("Eldoth",CD_STATE_NOTVALID)
CombatCounter(0)
THEN
RESPONSE #100
Interact("CVSandr")
END

// Coran
IF
InParty("Coran")
Global("SanCoran","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanCoran","LOCALS",1)
RealSetGlobalTimer("SanCoranTi","LOCALS",360)
END

IF
InParty("Coran")
RealGlobalTimerExpired("SanCoranTi","LOCALS")  
OR(2)
Global("SanCoran","LOCALS",1)
Global("SanCoran","LOCALS",9)
THEN
RESPONSE #100
IncrementGlobal("SanCoran","LOCALS",1)
END

IF
Global("SanCoran","LOCALS",3)
InParty("Coran")
AreaType(CITY)
AreaType(OUTDOOR)
!TimeOfDay(NIGHT)
THEN
RESPONSE #100
SetGlobal("SanCoran","LOCALS",4)
END

IF
Global("SanCoran","LOCALS",11)
RealGlobalTimerExpired("SanCoranTi","LOCALS")
InParty("Coran")
!AreaType(CITY)
AreaType(OUTDOOR)
OR(2)
TimeOfDay(NIGHT)
TimeOfDay(DUSK)
THEN
RESPONSE #100
SetGlobal("SanCoran","LOCALS",12)
END

IF
GlobalGT("SanCoran","LOCALS",12)
TimeOfDay(DAY)
AreaType(CITY)
InParty("Coran")
Global("SanCorShirt","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanCorShirt","LOCALS",1)
END

IF
Global("SanCoran","LOCALS",5)
InParty("Coran")
RealGlobalTimerExpired("SanCoranTi","LOCALS")
OR(16)
AreaCheck("BG4801")
AreaCheck("BG2616")
AreaCheck("BG3351")
AreaCheck("BG3304")
AreaCheck("BG2301")
AreaCheck("BG0105")
AreaCheck("BG0116")
AreaCheck("BG0119")
AreaCheck("BG0706")
AreaCheck("BG4003")
AreaCheck("BG1001")
AreaCheck("bh0115")
AreaCheck("bh0107")
AreaCheck("BG3357")
AreaCheck("BG0114")
AreaCheck("CVRoa2")
THEN
RESPONSE #100
SetGlobal("SanCoran","LOCALS",6)
END

IF
InParty("Coran")
Global("SanCorFlow","LOCALS",0)
PartyHasItem("X#cflow")
TimeGT(12)
THEN
RESPONSE #100
SetGlobal("SanCorFlow","LOCALS",1)
END

IF
Global("P#Briel_Stay","GLOBAL",1)
InParty("Coran")
OR(3)
Global("SanRomPath","GLOBAL",1)
GlobalLT("P#CFriendTalk","GLOBAL",7)
Global("P#CoranRomanceInactive","GLOBAL",1)
Global("P#CoranBaby","GLOBAL",0)
GlobalGT("SanCoran","LOCALS",4)
!AreaCheck("BG0103")
Global("SanCorbabe","GLOBAL",0)
Delay(22)
THEN
RESPONSE #100
SetGlobal("SanCorbabe","GLOBAL",1)
END

IF
InParty("Coran")
Global("SanCorbabe","GLOBAL",2) 
PartyHasItem("X#CBABY")
THEN
RESPONSE #100
SetGlobal("SanCorbabe","GLOBAL",3)
RealSetGlobalTimer("P#CGBabyTalkTime","GLOBAL",600)
END

IF
RealGlobalTimerExpired("P#CGBabyTalkTime","GLOBAL")
InParty("Coran")
!AreaType(DUNGEON)
!AreaCheck("BG2626")
CombatCounter(0)
!See([ENEMY])
OR(3)
Global("SanCorbabe","GLOBAL",3)
Global("SanCorbabe","GLOBAL",5)
Global("SanCorbabe","GLOBAL",7)
THEN
RESPONSE #100
IncrementGlobal("SanCorbabe","GLOBAL",1)
END

IF
Global("SanCorbabe","GLOBAL",9) 
RealGlobalTimerExpired("P#CGBabyTalkTime","GLOBAL")
!InParty("Coran")
THEN
RESPONSE #100
SetGlobal("SanCorbabe","GLOBAL",10)
END

IF
InParty("Coran")
!See([ENEMY])
See("Coran")
!StateCheck("Coran",CD_STATE_NOTVALID)
CombatCounter(0)
OR(15)
Global("SanCorShirt","LOCALS",1)
Global("SanCorFlow","LOCALS",1)
Global("SanCoran","LOCALS",2)
Global("SanCoran","LOCALS",4)
Global("SanCoran","LOCALS",6)
Global("SanCoran","LOCALS",8)
Global("SanCoran","LOCALS",10)
Global("SanCoran","LOCALS",12)
Global("SanCoran","LOCALS",15)
Global("SanCoran","LOCALS",17)
Global("SanCorbabe","GLOBAL",1)
Global("SanCorbabe","GLOBAL",4)
Global("SanCorbabe","GLOBAL",6)
Global("SanCorbabe","GLOBAL",8)
Global("SanCorbabe","GLOBAL",12)
THEN
RESPONSE #100
Interact("CVSandr")
END

IF
Global("SanCoran","LOCALS",13)
THEN
RESPONSE #100
SetGlobal("SanCoran","LOCALS",14)
AddSpecialAbility("cvknok")
AddSpecialAbility("cvtrap")
END

IF
Global("SanCoran","LOCALS",16)
THEN
RESPONSE #100
SetGlobal("SanCoran","LOCALS",17)
AddSpecialAbility("cvdrag8")
END

//Dungeon Talks
IF
AreaType(DUNGEON)
GlobalGT("Chapter","GLOBAL",1)
Global("SanDungtalk","GLOBAL",0)
Delay(35)
THEN
RESPONSE #100
SetGlobal("SanDungtalk","GLOBAL",1)
END

IF
AreaType(DUNGEON)
Global("SanDungtalk","GLOBAL",2)
RealGlobalTimerExpired("SanDungtalkInt","GLOBAL")
Delay(35)
THEN
RESPONSE #100
SetGlobal("SanDungtalk","GLOBAL",3)
END

//Stolen Book for Candlekeep
IF
Global("ReturnNashQuest","GLOBAL",7)
Global("SanCldKBo","LOCALS",0)
OR(3)
PartyHasItem("Book38")
PartyHasItem("Book39")
Global("ReturnNashQuestNandin","GLOBAL",3)
THEN
RESPONSE #100
SetGlobal("SanCldKBo","LOCALS",1)
END

IF
Global("ReturnNashQuest","GLOBAL",7)
Global("SanCldKBo","LOCALS",1)
AreaCheck("BG5400")
THEN
RESPONSE #100
SetGlobal("SanCldKBo","LOCALS",2)
END

IF
Global("ReturnNashQuest","GLOBAL",7)
Global("SanCldKBo","LOCALS",0)
AreaCheck("BG5400")
See("Emerson")
THEN
RESPONSE #100
SetGlobal("SanCldKBo","LOCALS",12)
ActionOverride("Emerson",SetGlobal("SanCldKBo","LOCALS",12))
DisplayStringWait(Player1,@542)
END

IF
Global("ReturnNashQuest","GLOBAL",7)
Global("SanCldKBo","LOCALS",3)
Global("EmDrow","BG5400",0)
AreaCheck("BG5400")
See("Emerson")
THEN
RESPONSE #100
SetGlobal("EmDrow","BG5400",1)
DisplayStringWait(Player1,@542)
END

IF
GlobalGT("ReturnNashQuest","GLOBAL",6)
AreaCheck("BG5402")
InParty("Xan")
Global("SanXanNashRet","LOCALS",0)
Delay(25)
THEN
RESPONSE #100
SetGlobal("SanXanNashRet","LOCALS",1)
END

IF
OR(1)
Global("SanCldKBo","LOCALS",3)
Global("SanCldKBo","LOCALS",0)
InParty("B!Gavin")
AreaCheck("BG5401")
THEN
RESPONSE #100
SetGlobal("SanCldKBo","LOCALS",4)
END

//Safana
IF
InParty("Safana")
Global("SanSafaBan","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanSafaBan","GLOBAL",1)
RealSetGlobalTimer("SanSafaBanTi","LOCALS",900)
END

IF
Global("SanSafaBan","GLOBAL",1)
RealGlobalTimerExpired("SanSafaBanTi","LOCALS")
InParty("Safana")
!AreaType(DUNGEON)
THEN
RESPONSE #100
SetGlobal("SanSafaBan","GLOBAL",2)
END

IF
InParty("Safana")
Global("SanSafaBan","GLOBAL",3)
RealGlobalTimerExpired("SanSafaBanTi","LOCALS")
AreaType(City)
TimeOfDay(DAY)
!AreaType(DUNGEON)
THEN
RESPONSE #100
SetGlobal("SanSafaBan","GLOBAL",4)
END

IF
!StateCheck("Safana",CD_STATE_NOTVALID)
!See([ENEMY])
CombatCounter(0)
!AreaType(DUNGEON)
See("Safana")
OR(3)
Global("SanSafaBan","GLOBAL",2)
Global("SanSafaBan","GLOBAL",4)
Global("SanSafaBan","GLOBAL",11)
THEN
RESPONSE #100
MoveToObject("Safana")
Interact("CVSandr")
END

IF
InParty("Safana")
Global("SanSafaBan","GLOBAL",5)
RealGlobalTimerExpired("SanSafaBanTi","LOCALS")
TimeOfDay(DAY)
Delay(16)
OR(5)
AreaCheck("BG0100")
AreaCheck("BG0200")
AreaCheck("BG0600")
AreaCheck("BG1100")
AreaCheck("BG1200")
THEN
RESPONSE #100
CreateCreatureObjectOffset("CVSafcit",Myself,[125.125])
CreateCreatureObjectOffset("CVSafgua",Myself,[75.75])
SetGlobal("SanSafaBan","GLOBAL",6)
END

IF
Global("SanSafaBan","GLOBAL",7)
THEN
RESPONSE #100
		ClearAllActions()
		SaveGame(0)
		SmallWait(6)
		StartCutSceneMode()
		FadeToColor([30.0],0)
		Wait(2) 
                ActionOverride("CVSafgua",EscapeArea())
		ActionOverride("CVSafcit",EscapeArea())
                Wait(4)
		ActionOverride(Player1,LeaveAreaLUA("BG0607","",[970.729],9))
		ActionOverride(Player2,LeaveAreaLUA("BG0607","",[970.729],9))
		ActionOverride(Player3,LeaveAreaLUA("BG0607","",[970.729],9))
		ActionOverride(Player4,LeaveAreaLUA("BG0607","",[970.729],9))
		ActionOverride(Player5,LeaveAreaLUA("BG0607","",[970.729],9))
		ActionOverride(Player6,LeaveAreaLUA("BG0607","",[970.729],9))
		FadeFromColor([30.0],0)
                EndCutSceneMode()
		SetGlobal("SanSafaBan","GLOBAL",8)
END

IF
Global("SanSafaBan","GLOBAL",8)
THEN
RESPONSE #100
CreateCreatureObjectOffset("CVentar",Myself,[25.25])
CreateCreatureObjectOffset("CVSafgua",Myself,[45.45])
CreateCreatureObjectOffset("CVSafcit",Myself,[65.65])
SetGlobal("SanSafaBan","GLOBAL",9)
END

IF
Global("SanSafaBan","GLOBAL",12)
THEN
RESPONSE #100
SetGlobal("SanSafaBan","GLOBAL",13)
AddSpecialAbility("CVDRA14")
END

//Ajantis + Sandrah past
IF
InParty("Ajantis") 
!AreaCheck("BG1400")
!AreaCheck("BG1401")
!AreaCheck("bg2300")
Global("SanRomPath","GLOBAL",1)
Global("KnoAjMale","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("KnoAjMale","GLOBAL",1)
END

IF
InParty("Ajantis")
!AreaCheck("BG1400")
!AreaCheck("BG1401")
!AreaCheck("bg2300")
Global("SanRomPath","GLOBAL",2)
Global("KnoAjFem","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("KnoAjFem","GLOBAL",1)
END

IF
InParty("Ajantis")
Global("SanAjan1","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanAjan1","LOCALS",1)
RealSetGlobalTimer("SanAjan2","LOCALS",1800)
END

IF
InParty("Ajantis")
!StateCheck("Ajantis",CD_STATE_NOTVALID)
!StateCheck("CVSandr",CD_STATE_NOTVALID)
!See([ENEMY])
Global("PCKnowsElmDaughter","GLOBAL",0)
Global("SanAjan1","LOCALS",1)
RealGlobalTimerExpired("SanAjan2","LOCALS")
THEN
RESPONSE #100
SetGlobal("SanAjan1","LOCALS",2)
END

IF
AreaType(CITY)
InParty("Ajantis")
Global("SanAjaThief","GLOBAL",0)
OR(2)
Global("KnoAjFem","GLOBAL",3)
Global("KnoAjMale","GLOBAL",3)
!AreaCheck("bg2300")
CombatCounter(0)
Delay(18)
THEN
RESPONSE #100
SetGlobal("SanAjaThief","GLOBAL",1)
CreateCreatureObjectOffset("cvajam",Myself,[125.100])
CreateCreatureObjectOffset("cvajab",Myself,[165.120])
ActionOverride("cvajab",StartDialogueNoSet([PC]))
END

IF
InParty("Ajantis")
CombatCounter(0)
!See([ENEMY])
See("Ajantis")
!StateCheck("Ajantis",CD_STATE_NOTVALID)
OR(13)
Global("SanAjan1","LOCALS",2)
Global("SanAjkilBant","GLOBAL",1)
Global("SanHelmDogmas","GLOBAL",2)
Global("SanHelmDogmas","GLOBAL",6)
Global("SanHelmDogmas","GLOBAL",9)
Global("SanHelmDogmas","GLOBAL",10)
Global("SanHelmDogmas","GLOBAL",13)
Global("SanAjanProp2","GLOBAL",5)
Global("SanAjanProp3","GLOBAL",2)
Global("SanHelmDogmas","GLOBAL",26)
Global("SanAjanGifts","GLOBAL",1)
Global("SanAjanGifts","GLOBAL",3)
Global("SanAjanGifts","GLOBAL",5)
THEN
RESPONSE #100
MoveToObject("Ajantis")
Interact("CVSandr")
END

//Evil Prince(ss)
IF
Global("SanEvlPri","GLOBAL",0)
Alignment(Player1,MASK_EVIL)
InParty(Myself)
!AreaCheck("bg2700")
THEN
RESPONSE #100
SetGlobal("SanEvlPri","GLOBAL",1)
RealSetGlobalTimer("SanEviPriT","LOCALS",36000)
END

IF
Global("SanEvlPri","GLOBAL",1)
OR(5)
RealGlobalTimerExpired("SanEviPriT","LOCALS")
ReputationLT(Player1,8)
Dead("greywolf")
Dead("cmbou06")
Dead("osmadi")
CombatCounter(0)
!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
RESPONSE #100
SetGlobal("SanEvlPri","GLOBAL",2)
RealSetGlobalTimer("SanEviPriT","LOCALS",11000)
Interact("CVSandr")
END

IF
Global("SanEvlPri","GLOBAL",0)
ReputationLT(Player1,7)
!Alignment(Player1,MASK_EVIL)
CombatCounter(0)
!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
RESPONSE #100
SetGlobal("SanEvlPri","GLOBAL",2)
RealSetGlobalTimer("SanEviPriT","LOCALS",11000)
Interact("CVSandr")
END

// Set Branwen Global

IF
!Global("ENDOFBG1","GLOBAL",2)
!InParty("Branwen")
Global("SanBranSearch","GLOBAL",0)
!Global("SanBranSearch","GLOBAL",2)
OR(4)
AreaCheck("BG3400")
AreaCheck("BG3300")
AreaCheck("BG4800")
AreaCheck("BG4900")
THEN
RESPONSE #100
SetGlobal("SanBranSearch","GLOBAL",1)
SetGlobal("SanBranSearchRem","GLOBAL",1)
RealSetGlobalTimer("SanBranSearchRemTime","GLOBAL",180)
END

IF
RealGlobalTimerExpired("SanBranSearchRemTime","GLOBAL")
Global("SanBranSearchRem","GLOBAL",1)
!InParty("Branwen")
OR(4)
AreaCheck("BG3400")
AreaCheck("BG3300")
AreaCheck("BG4800")
AreaCheck("BG4900")
THEN
RESPONSE #100
SetGlobal("SanBranSearchRem","GLOBAL",2) 
END

IF
Global("P#BRANWENROMANCEACTIVE","GLOBAL",2)
Global("SanBranDec","GLOBAL",0)
AreaType(OUTDOOR)
THEN
RESPONSE #100
SetGlobal("SanBranDec","GLOBAL",1)
RealSetGlobalTimer("SanBranSearchRemTime","GLOBAL",180)
END

IF
RealGlobalTimerExpired("SanBranSearchRemTime","GLOBAL")
Global("SanBranDec","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("SanBranDec","GLOBAL",2)
END

IF
!Global("ENDOFBG1","GLOBAL",2)
InParty("Branwen")
Global("SanBranSearch","GLOBAL",1)
Global("SanBranRepl","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("SanBranSearch","GLOBAL",3)
END

IF
!Global("ENDOFBG1","GLOBAL",2)
InParty("Branwen")
Global("SanBranSearch","GLOBAL",1)
!Global("SanBranRepl","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("SanBranSearch","GLOBAL",4)
END

IF
!InParty("Branwen")
Global("SanBranSearchRem","GLOBAL",3)
AreaCheck("BG4900")
OR(7)
See("Gazib")
See("Skeezer")
See("Binky")
See("Keiria")
See("Lestor")
See("c#q03011")
See("pnashk")
THEN
RESPONSE #100
SetGlobal("SanBranSearchRem","GLOBAL",4)
END

IF
Global("SanBranSearchRem","GLOBAL",4)
AreaCheck("BG4900")
!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogueNoSet("CVSandr")
END

IF
!Global("ENDOFBG1","GLOBAL",2)
Global("SanBranSearch","GLOBAL",3)
InParty("Branwen")
!StateCheck("Branwen",CD_STATE_NOTVALID)
Global("SanBranJoined","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanBranJoined","GLOBAL",1)
MoveToObject(Player1)
Interact("CVSandr")
END

IF
!Global("ENDOFBG1","GLOBAL",2)
Global("SanBranSearch","GLOBAL",4)
InParty("Branwen")
!StateCheck("Branwen",CD_STATE_NOTVALID)
Global("SanBranJoined","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanBranJoined","GLOBAL",1)
EraseJournalEntry(@11)
MoveToObject(Player1)
Interact("CVSandr")
END

IF
!Global("ENDOFBG1","GLOBAL",2)
RealGlobalTimerExpired("SanBranReplTime","GLOBAL")
Global("SanBranSearch","GLOBAL",3)
Global("SanLeaveBran","GLOBAL",0)
!See([ENEMY])
CombatCounter(0)
THEN
RESPONSE #100
SetGlobal("SanLeaveBran","GLOBAL",1)
MoveToObject(Player1)
StartDialogueNoSet("CVSandr")
END

IF
!Global("ENDOFBG1","GLOBAL",2)
Global("SanLeaveBran","GLOBAL",0)
GlobalLT("Sanpoints","GLOBAL",5)
InParty("Branwen")
!AreaCheck("BG4900")
!See([ENEMY])
CombatCounter(0)
THEN
RESPONSE #100
SetGlobal("SanLeaveBran","GLOBAL",1)
MoveToObject(Player1)
StartDialogueNoSet("CVSandr")
END

IF
!Global("ENDOFBG1","GLOBAL",2)
Global("SanBranSearch","GLOBAL",4)
InParty("Branwen")
Global("SanBranRepl","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("SanPidPack","GLOBAL",36)
SetGlobal("SanBranSearch","GLOBAL",3)
RealSetGlobalTimer("SanBranReplTime","GLOBAL",ONE_DAY)
END

IF
!Global("ENDOFBG1","GLOBAL",2)
InParty("Branwen")
!Dead("Tranzig")
AreaCheck("BG5400")
Global("SanBranTRInv","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanBranTRInv","LOCALS",1)
END

IF
!Global("ENDOFBG1","GLOBAL",2)
InParty("Branwen")
GlobalGT("Chapter","GLOBAL",2)
Global("SanBranFrT","GLOBAL",0)
OR(16)
AreaCheck("BG4801")
AreaCheck("BG2616")
AreaCheck("BG3351")
AreaCheck("BG3304")
AreaCheck("BG2301")
AreaCheck("BG0105")
AreaCheck("BG0116")
AreaCheck("BG0119")
AreaCheck("BG0706")
AreaCheck("BG4003")
AreaCheck("BG1001")
AreaCheck("bh0115")
AreaCheck("bh0107")
AreaCheck("BG3357")
AreaCheck("BG0114")
AreaCheck("CVRoa2")
THEN
RESPONSE #100
SetGlobal("SanBranFrT","GLOBAL",1)
END

IF
Global("P#BRLOVETALK","GLOBAL",39)
InParty("Branwen")
Global("P#BRANWENROMANCEACTIVE","GLOBAL",2)
Global("SanBranOV","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanBranOV","LOCALS",1)
RealSetGlobalTimer("SanBranReplTime","GLOBAL",3000)
END

IF
Global("SanBranOV","LOCALS",1)
RealGlobalTimerExpired("SanBranReplTime","GLOBAL")
InParty("Branwen")
AreaType(CITY)
!AreaType(DUNGEON)
THEN
RESPONSE #100
SetGlobal("SanBranOV","LOCALS",2)
END

IF
!See([ENEMY])
See("Branwen")
See(Player1)
!StateCheck("Branwen",CD_STATE_NOTVALID)
!StateCheck(Player1,CD_STATE_NOTVALID)
OR(3)
Global("SanBranFrT","GLOBAL",1)
Global("SanBranKilT","GLOBAL",1)
Global("SanBranOV","LOCALS",2)
THEN
RESPONSE #100
MoveToObject("Branwen")
Interact("CVSandr")
END

IF
!Global("ENDOFBG1","GLOBAL",2)
InParty("Branwen")
!TimeOfDay(NIGHT)
!See([ENEMY])
Global("SanBranFrT","GLOBAL",2)
GlobalGT("CHAPTER","GLOBAL",2)
RealGlobalTimerExpired("SanBranFrTTT","LOCALS")
OR(15)
AreaCheck("BG3600")
AreaCheck("BG3100")
AreaCheck("BG2100")
AreaCheck("CVElm4")
AreaCheck("bg2700")
AreaCheck("BG5800")
AreaCheck("ar3594")
AreaCheck("ar3588")
AreaCheck("ar3500")
AreaCheck("BG2000")
AreaCheck("BG1000")
AreaCheck("BG1500")
AreaCheck("bh1200")
AreaCheck("bh1400")
AreaCheck("bh2200")
THEN
RESPONSE #100  
SetGlobal("SanBranFrT","GLOBAL",3)
END

IF
AreaType(DUNGEON)
Global("SanBranFrT","GLOBAL",4)
THEN
RESPONSE #100
SetGlobal("SanBranFrT","GLOBAL",5)
END

IF
!Global("ENDOFBG1","GLOBAL",2)
Global("SanBranSharDzt","GLOBAL",1)
Global("SanBranDzt","GLOBAL",0)
InParty("Branwen")
OR(2)
AreaCheck("BG4200")
AreaCheck("BG0500")
Delay(12)
THEN
RESPONSE #100
SetGlobal("SanBranDzt","GLOBAL",1)
END

IF
Global("SanBranSharDzt","GLOBAL",1)
Global("SansharDzt","GLOBAL",0)
!InParty("Branwen")
InParty("Sharteel")
OR(2)
AreaCheck("BG4200")
AreaCheck("BG0500")
Delay(12)
THEN
RESPONSE #100
SetGlobal("SansharDzt","GLOBAL",1)
END

IF
!Global("ENDOFBG1","GLOBAL",2)
InParty("Branwen")
Dead("Tranzig")
!AreaCheck("BG3352")
Global("SanBranTrzg","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanBranTrzg","GLOBAL",1)
END

IF
InParty("Branwen")
Global("SanBranTrzg","GLOBAL",2)
AreaType(FOREST)
TimeOfDay(DAY)
THEN
RESPONSE #100
SetGlobal("SanBranTrzg","GLOBAL",3)
END


IF
GlobalGT("P#BRLOVETALK","GLOBAL",12)
InParty("Branwen")
Global("SanBrandoT","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanBrandoT","GLOBAL",1)
RealSetGlobalTimer("SanBranFrTTT","LOCALS",480)
END

IF
RealGlobalTimerExpired("SanBranFrTTT","LOCALS")
Global("SanBrandoT","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("SanBrandoT","GLOBAL",2)
END

IF
InParty("Branwen")
Global("SanBranDetLove","GLOBAL",0)
OR(2)
Global("SanBranKilT","GLOBAL",2)
Global("P#BRLOVETALK","GLOBAL",22)
THEN
RESPONSE #100
SetGlobal("SanBranDetLove","GLOBAL",1)
RealSetGlobalTimer("SanBranDelLove","LOCALS",1200)
END

IF
Global("SanBranDetLove","GLOBAL",1)
RealGlobalTimerExpired("SanBranDelLove","LOCALS")
RealGlobalTimerExpired("SanBranFrTTT","LOCALS")
THEN
RESPONSE #100
SetGlobal("SanBranDetLove","GLOBAL",2)
END

IF
!StateCheck("Branwen",CD_STATE_NOTVALID)
!See([ENEMY])
CombatCounter(0)
OR(7)
Global("SanBranDzt","GLOBAL",1)
Global("SanBranFrT","GLOBAL",3)
Global("SanBranFrT","GLOBAL",5)
Global("SanBranTrzg","GLOBAL",1)
Global("SanBranFrT","GLOBAL",8)
Global("SanBranDetLove","GLOBAL",2)
Global("SanBranTrzg","GLOBAL",3)
THEN
RESPONSE #100
MoveToObject("Branwen")
Interact("CVSandr")
END

IF
Global("SanBranTrzg","GLOBAL",4)
GlobalGT("SanBranFrT","GLOBAL",5)
Global("SanBranKilT","GLOBAL",2)
InParty("Branwen")
OR(3)
Gender(Player1,FEMALE)
Global("P#BRANWENROMANCEACTIVE","GLOBAL",0)
Global("P#BRANWENROMANCEACTIVE","GLOBAL",3)
Global("SanBranDecF","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanBranDecF","GLOBAL",1)
AddSpecialAbility("CVDrag5")
END

IF
Global("SanBranDec","GLOBAL",4)
THEN
RESPONSE #100
SetGlobal("SanBranDec","GLOBAL",5)
AddSpecialAbility("CVDrag5")
END

//Druid Ambush Carnival
IF
Global("DruidCar","BG4900",1)
AreaCheck("BG4900")
OR(2)
See("CVDrud1")
See("CVDrud3")
THEN
RESPONSE #100
ClearAllActions()
StartCutSceneMode()
MoveViewPoint([3744.1668],STANDARD)
Wait(2)
SetGlobal("DruidCar","BG4900",2)
EndCutSceneMode()
ActionOverride("CVDrud3",StartDialogueNoSet([PC]))
END

//Girdle of Gender, Healing Scrolls, Centeol, Golem Manual
IF
Global("SanhealScrl","GLOBAL",0)
OR(2)
PartyHasItem("scrl56")
PartyHasItem("scrls56")
THEN
RESPONSE #100
SetGlobal("SanhealScrl","GLOBAL",1)
END

IF
!InParty("Xan")
InParty("Kivan")
Global("SanSpokeCent","LOCALS",0)
Global("CentKiv","GLOBAL",0)
OR(2)
Global("Centejon","BG2101",1)
Global("P#Rain","GLOBAL",6)
THEN
RESPONSE #100
SetGlobal("CentKiv","GLOBAL",1)
END

IF
!InParty("Xan")
!InParty("Kivan")
Global("CentPC","GLOBAL",0)
Global("SanSpokeCent","LOCALS",0)
OR(2)
Global("Centejon","BG2101",1)
Global("P#Rain","GLOBAL",6)
THEN
RESPONSE #100
SetGlobal("CentPC","GLOBAL",1)
END

IF
InParty("Xan")
Global("SanSpokeCent","LOCALS",0)
Global("CentXan","GLOBAL",0)
OR(2)
Global("Centejon","BG2101",1)
Global("P#Rain","GLOBAL",6)
Delay(12)
THEN
RESPONSE #100
SetGlobal("CentXan","GLOBAL",1)
END

IF
Global("SanGolman","LOCALS",0)
OR(7)
AreaCheck("ar4907")
AreaCheck("BG2614")
AreaCheck("BG3314")
AreaCheck("BG3353")
AreaCheck("BG0120")
AreaCheck("BG0156")
AreaCheck("BG4012")
!PartyHasItem("cvgolman")
Delay(15)
THEN
RESPONSE #100
SetGlobal("SanGolman","LOCALS",1)
GiveItemCreate("cvgolman",Player1,0,0,0)
END

IF
Global("SanGolman","LOCALS",0)
PartyHasItemIdentified("cdmgolem")
Delay(22)
THEN
RESPONSE #100
SetGlobal("SanGolman","LOCALS",2)
END

IF
GlobalLT("SanGolman","LOCALS",2)
PartyHasItemIdentified("cvgolman")
Delay(22)
THEN
RESPONSE #100
SetGlobal("SanGolman","LOCALS",2)
END

// Faldorn

IF
InParty("Faldorn")
Global("SanFalB","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanFalB","GLOBAL",1)
RealSetGlobalTimer("SanFalBW","LOCALS",623)
END

IF
InParty("Faldorn")
!AreaCheck("BG1600")
TimeOfDay(NIGHT)
Global("SanFalB","GLOBAL",1)
RealGlobalTimerExpired("SanFalBW","LOCALS")
THEN
RESPONSE #100
SetGlobal("SanFalB","GLOBAL",2)
END

IF
InParty("Faldorn") 
See("Faldorn")
!See([ENEMY])
!StateCheck("Faldorn",CD_STATE_NOTVALID)
Global("SanFalB","GLOBAL",2)
THEN
RESPONSE #100
MoveToObject("Faldorn")
Interact("CVSandr")
END

// Done Nashkel Mines
IF
!Global("ENDOFBG1","GLOBAL",2)
OR(2)
AreaCheck("BG5400")
AreaCheck("BG5000")
InParty("CVSandr")
Global("Chapter","GLOBAL",3)
Global("SanThruNasM","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanThruNasM","GLOBAL",1)
END

IF
Global("SanThruNasM","GLOBAL",1)
AreaCheck("BG5000")
!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogueNoSet("CVSandr")
END

//Shoal

IF
Global("ShoalKiss","GLOBAL",1)
Dead("SHOAL")
!Dead("Droth")
!InMyArea("Droth")
Global("Sandroth","LOCALS",0)
THEN
RESPONSE #100
CreateCreature("DROTH",[2500.500],6)
ActionOverride("Droth",MoveToPoint([2900.525]))
SetGlobal("Sandroth","LOCALS",1)
END

// Bone Hill
IF
AreaCheck("BG3402")
See("BHPell")
Global("SanPellQ0","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanPellQ0","LOCALS",1)
END

// Demonic Scroll
IF
Global("ScrlalzT","GLOBAL",0)
AreaCheck("BG3334")
PartyHasItem("SCRLALZ")
InParty("CVSandr")
THEN
RESPONSE #100
AddJournalEntry(@13,QUEST)
SetGlobal("ScrlalzT","GLOBAL",1)
END

IF
Global("ScrlalzI","GLOBAL",0)
AreaCheck("BG3333")
PartyHasItem("SCRLALZ")
InParty("CVSandr")
!Global("UsedScrlPort","GLOBAL",1)
!Global("UsedScrlRock","GLOBAL",1)
!Global("UsedScrlLoc","GLOBAL",1)
!Global("UsedScrlRock","GLOBAL",2)
THEN
RESPONSE #100
DisplayStringWait(Myself,@55)
SetGlobal("ScrlalzI","GLOBAL",1)
END

IF
Global("ScrlalzI","GLOBAL",1)
Global("ScrlToldArea","GLOBAL",0)
Global("UsedScrlPort","GLOBAL",1)
Global("UsedScrlRock","GLOBAL",2)
Global("UsedScrlLoc","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("ScrlalzI","GLOBAL",2)
SetGlobal("ScrlalzT","GLOBAL",2)
END

IF
Global("SanNarQ","GLOBAL",2)
AreaCheck("BG5200")
Global("ScrlToldArea","GLOBAL",0)
PartyHasItem("SCRLALZ")
InParty("CVSandr")
THEN
RESPONSE #100
SetGlobal("ScrlalzT","GLOBAL",3)
DisplayStringHead("CVSandr",@22)
SetGlobal("ScrlToldArea","GLOBAL",1)
END

// Eminster NarQuest

IF
RealGlobalTimerExpired("NarQMess","GLOBAL")
Global("NarQMessApp","GLOBAL",0)
OR(2)
GlobalLT("BHQuestAccept","GLOBAL",3)
GlobalGT("BHQuestAccept","GLOBAL",8)
AreaType(OUTDOOR)
THEN
RESPONSE #100
SetGlobal("NarQMessApp","GLOBAL",1)
END

IF
Global("NarQMessApp","GLOBAL",1)
!AreaType(DUNGEON)
InParty("CVSandr")
!StateCheck("CVSandr",CD_STATE_NOTVALID)
Global("NarQMessApp","GLOBAL",1)
Global("NarQMessCre","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("NarQMessCre","LOCALS",1)
CreateCreatureObjectOffScreen("NarQMes",Myself,0,0,0)
END

IF
Global("NarQMessApp","GLOBAL",2)
RealGlobalTimerExpired("NarqMesRemTTime","GLOBAL")
InParty("CVSandr")
!StateCheck("CVSandr",CD_STATE_NOTVALID)
Global("SanNarQ","GLOBAL",0)
Global("ElminGaveNarQ","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("NarQMessApp","GLOBAL",4)
END

IF
Global("NarQMessApp","GLOBAL",4)
InParty("CVSandr")
!StateCheck(Player1,CD_STATE_NOTVALID)
Global("NarQMesReAp","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("NarQMesReAp","LOCALS",1)
CreateCreatureObject("NarQMes",Myself,0,0,0)
END

IF
Global("NarQMessApp","GLOBAL",5)
RealGlobalTimerExpired("NarqMesRemTTime","GLOBAL")
InParty("CVSandr")
!StateCheck(Player1,CD_STATE_NOTVALID)
Global("ElminGaveNarQ","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanNarQnotElm","GLOBAL",1)
MoveToObject(Player1)
StartDialogueNoSet("CVSandr")
END


//Found NarLair

IF
Dead("CVDEKN1")
Global("NarPortFound","GLOBAL",0)
THEN
RESPONSE #100
ClearAllActions()
SmallWait(2) 
StartCutSceneMode()
                MoveToPoint([3744.1668])
                Face(9)
                MoveViewPoint([3744.1668],STANDARD)
		DisplayStringWait(Myself,@45)
		SmallWait(8)
		DisplayStringWait(Myself,@46)
		SmallWait(10)
		DisplayStringWait(Myself,@47)
		Wait(6)
		StartMovie("Flythr02")
                FadeToColor([30.0],0)
		Wait(2)
		ActionOverride(Player1,LeaveAreaLUA("CVNAR1","",[699.458],5))
		ActionOverride(Player2,LeaveAreaLUA("CVNAR1","",[699.458],9))
		ActionOverride(Player3,LeaveAreaLUA("CVNAR1","",[699.458],10))
		ActionOverride(Player4,LeaveAreaLUA("CVNAR1","",[699.458],10))
		ActionOverride(Player5,LeaveAreaLUA("CVNAR1","",[699.458],9))
		ActionOverride(Player6,LeaveAreaLUA("CVNAR1","",[699.458],5))
		FadeFromColor([30.0],0)
                EndCutSceneMode()
                SetGlobal("NarPortFound","GLOBAL",1)
                SetGlobal("EnterNar","GLOBAL",1)
		AddJournalEntry(@48,QUEST)

END

IF
Global("SanNarQ","GLOBAL",3)
OR(2)
PartyHasItem("AlzaHrt2")
PartyHasItem("AlzaHrt1")
THEN
RESPONSE #100
SetGlobal("SanNarQ","GLOBAL",4)
DisplayStringHead("CVSandr",@61)
END

IF
	Global("SanNarQ","GLOBAL",5)
	Global("EnterNar","GLOBAL",1)
THEN
	RESPONSE #100
		ClearAllActions()
		SaveGame(0)
		SmallWait(6)
		StartCutSceneMode()
		FadeToColor([30.0],0)
		Wait(2)
		ActionOverride(Player1,LeaveAreaLUA("CVNAR1","",[699.458],9))
		ActionOverride(Player2,LeaveAreaLUA("CVNAR1","",[699.458],9))
		ActionOverride(Player3,LeaveAreaLUA("CVNAR1","",[699.458],9))
		ActionOverride(Player4,LeaveAreaLUA("CVNAR1","",[699.458],9))
		ActionOverride(Player5,LeaveAreaLUA("CVNAR1","",[699.458],9))
		ActionOverride(Player6,LeaveAreaLUA("CVNAR1","",[699.458],9))
		FadeFromColor([30.0],0)
                EndCutSceneMode()
		SetGlobal("EnterNar","GLOBAL",2)
END

// Dead Cat
IF
Global("SanNarQ","GLOBAL",2)
Global("NotWFall","GLOBAL",0)
Range("Container2",20)
AreaCheck("BG5200")
OR(2)
PartyHasItem("MISC62") 
Global("HelpDrienne","GLOBAL",1)
!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
RESPONSE #100
SetGlobal("NotWFall","GLOBAL",1)
END

IF
Global("PixieHint","GLOBAL",1)
AreaCheck("BG5200")
!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
RESPONSE #100
SetGlobal("PixieHint","GLOBAL",2)
END

IF
Global("PixieHint","GLOBAL",2)
AreaCheck("BG5200")
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogueNoSet("CVSandr")
END

IF
GlobalLT("SanNarQ","GLOBAL",7)
AreaCheck("BG3402")
InParty("CVSandr") 
PartyHasItem("SanParc")
THEN
RESPONSE #100
SetGlobal("SanNarQ","GLOBAL",7)
END

// Found AlzLair

IF
Global("SanNarQ","GLOBAL",2)
Global("ScrlToldArea","GLOBAL",1)
AreaCheck("BG5202")
PartyHasItem("SCRLALZ")
PartyHasItem("DEMSCR")
InParty("CVSandr")
THEN
RESPONSE #100
SetGlobal("ScrlalzT","GLOBAL",3)
DisplayStringHead("CVSandr",@53)
SetGlobal("ScrlToldArea","GLOBAL",2)
SetGlobal("SanNarQ","GLOBAL",3)
END

IF
Global("AlzLairOpen","GLOBAL",1)
Global("AlzPortFound","GLOBAL",0)
THEN
RESPONSE #100
ClearAllActions()
SmallWait(2)
StartCutSceneMode()
                SmallWait(4)
                FadeToColor([30.0],0)
		Wait(2)
		ActionOverride(Player1,LeaveAreaLUA("CVNAR2","",[126.337],12))
		ActionOverride(Player2,LeaveAreaLUA("CVNAR2","",[269.350],13))
		ActionOverride(Player3,LeaveAreaLUA("CVNAR2","",[218.392],11))
		ActionOverride(Player4,LeaveAreaLUA("CVNAR2","",[161.257],11))
		ActionOverride(Player5,LeaveAreaLUA("CVNAR2","",[126.337],12))
		ActionOverride(Player6,LeaveAreaLUA("CVNAR2","",[269.350],13))
		FadeFromColor([30.0],0)
		EndCutSceneMode()
		SetGlobal("AlzPortFound","GLOBAL",1)
END

// Triggers after Sent Naronguth to Hell

IF
Global("SanNarQ","GLOBAL",6)
Global("NarHellAfter","GLOBAL",1)
AreaCheck("CVNAR1")
!StateCheck(Player1,CD_STATE_NOTVALID)
Delay(6)
THEN
RESPONSE #100
SetGlobal("NarHellAfter","GLOBAL",2)
MoveToObject(Player1)
StartDialogueNoSet("CVSandr")
END

IF
Global("SanNarQ","GLOBAL",6) 
AreaCheck("CVNAR1") 
Global("NarCavOut","GLOBAL",0)
!PartyHasItem("EShard")
Global("NarHellAfter","GLOBAL",3)
Delay(4)
THEN
RESPONSE #100
SetGlobal("NarCavOut","GLOBAL",1)
MoveToObject(Player1)
StartDialogueNoSet("CVSandr")
END

IF
Global("SanNarQ","GLOBAL",6)
GlobalLT("NarCavOut","GLOBAL",3) 
Global("NarHellAfter","GLOBAL",3)
PartyHasItemIdentified("EShard")
PartyHasItem("Sandebo")
THEN
RESPONSE #100
SetGlobal("NarCavOut","GLOBAL",3)
MoveToObject(Player1)
StartDialogueNoSet("CVSandr")
END

IF
Global("SanNarQ","GLOBAL",6)
Global("NarCavOut","GLOBAL",4)
AreaCheck("BG5300")
PartyHasItem("EShard")
THEN
RESPONSE #100
SetGlobal("NarCavOut","GLOBAL",5)
MoveToObject(Player1)
StartDialogueNoSet("CVSandr")
END

IF
Global("SanDblEnc","GLOBAL",0)
Dead("sandbl1")
Dead("sandbl2")
THEN
RESPONSE #100
SetGlobal("SanDblEnc","GLOBAL",1)
END

IF
GlobalGT("NarCavOut","GLOBAL",5)
Global("CVPest","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("CVPest","LOCALS",1)
AddSpecialAbility("CVPest")
AddSpecialAbility("CVPest")
END

IF
Global("CVGodag","GLOBAL",1)
PartyHasItem("Godag01")
GlobalGT("ElmHint","GLOBAL",3)
AreaType(OUTDOOR)
!AreaType(CITY)
Delay(12)
THEN
RESPONSE #100
SetGlobal("CVGodag","GLOBAL",2)
END

IF
Global("CVGodag","GLOBAL",4)
PartyHasItem("Godag02")
!AreaCheck("bg2300")
Delay(12)
THEN
RESPONSE #100
SetGlobal("CVGodag","GLOBAL",5)
END

// Discovering Elminster's Daughter
IF
GlobalGT("ElmHint","GLOBAL",5)
GlobalGT("SanPidPack","GLOBAL",7)
InParty("CVSandr")
Global("PCKnowsElmDaughter","GLOBAL",0)
Global("PCDisciovF","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("PCDisciovF","LOCALS",1)
RealSetGlobalTimer("PCTalkElmDaughterT","GLOBAL",180)
END

IF
RealGlobalTimerExpired("PCTalkElmDaughterT","GLOBAL")
InParty("CVSandr")
!AreaType(DUNGEON)
Global("PCKnowsElmDaughter","GLOBAL",0)
Global("PCTalkElmDaughter","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("PCTalkElmDaughter","GLOBAL",1)
END

IF
Global("PCTalkElmDaughter","GLOBAL",2)
THEN
RESPONSE #100
SetGlobal("PCTalkElmDaughter","GLOBAL",3)
ClearAllActions()
SmallWait(2)
SetInterrupt(FALSE)
TextScreen("SanElm")
AddJournalEntry(@133,QUEST_DONE)
END

//Trigger Garrick
IF
InParty("Garrick")
!AreaCheck("BG3300")
AreaType(OUTDOOR)
Global("SanGarr1","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanGarr1","GLOBAL",1)
END

IF
InParty("Garrick")
Global("SanGarr1","GLOBAL",2)
OR(22)
AreaCheck("bh0115")
AreaCheck("bh0107")
AreaCheck("BG4801")
AreaCheck("BG2616")
AreaCheck("BG3351")
AreaCheck("BG3304")
AreaCheck("BG2301")
AreaCheck("BG0105")
AreaCheck("BG0116")
AreaCheck("BG0119")
AreaCheck("BG0706")
AreaCheck("BG4003")
AreaCheck("BG1001")
AreaCheck("BG0002")
AreaCheck("BG4802")
AreaCheck("BG2304")
AreaCheck("BG3402")
AreaCheck("BG0132")
AreaCheck("BG0131")
AreaCheck("BG3202")
AreaCheck("BG0149")
AreaCheck("CVRoa2")
THEN
RESPONSE #100
SetGlobal("SanGarr1","GLOBAL",3)
END

IF
Global("SanGarr1","GLOBAL",4)
OR(14)
AreaCheck("BG4400")
AreaCheck("BG4700")
AreaCheck("BG4600")
AreaCheck("BG5000")
AreaCheck("BG5200")
AreaCheck("BG5100")
AreaCheck("BG5300")
AreaCheck("BG5400")
AreaCheck("BG0400")
AreaCheck("BG0900")
AreaCheck("BG2400")
AreaCheck("BG2900")
AreaCheck("BG3600")
AreaCheck("BG3700")
THEN
RESPONSE #100
SetGlobal("SanGarr1","GLOBAL",5)
END

IF
InParty("Garrick")
HasItemEquiped("x#garch","Garrick")
Global("SanGarQCh","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanGarQCh","GLOBAL",1)
END

IF
InParty("Garrick")
Global("SanGarQCh","GLOBAL",2)
OR(14)
AreaCheck("BG4801")
AreaCheck("BG2616")
AreaCheck("BG3351")
AreaCheck("BG3304")
AreaCheck("BG2301")
AreaCheck("BG0105")
AreaCheck("BG0116")
AreaCheck("BG0119")
AreaCheck("BG0706")
AreaCheck("BG4003")
AreaCheck("BG1001")
AreaCheck("bh0115")
AreaCheck("bh0107")
AreaCheck("CVRoa2")
THEN
RESPONSE #100
SetGlobal("SanGarQCh","GLOBAL",3)
END

IF
InParty("Garrick")
Global("SanGarr1","GLOBAL",6)
Global("SanGarQCh","GLOBAL",5)
RealGlobalTimerExpired("SangarLeDel","LOCALS")
!AreaType(OUTDOOR)
!AreaType(DUNGEON)
THEN
RESPONSE #100
SetGlobal("SanGarr1","GLOBAL",7)
END

IF
See("Garrick")
InParty("Garrick")
!See([ENEMY])
!StateCheck("Garrick",CD_STATE_NOTVALID)
OR(6)
Global("SanGarr1","GLOBAL",1)
Global("SanGarr1","GLOBAL",3)
Global("SanGarr1","GLOBAL",5)
Global("SanGarQCh","GLOBAL",1)
Global("SanGarQCh","GLOBAL",3)
Global("SanGarr1","GLOBAL",7)
THEN
RESPONSE #100
MoveToObject("Garrick")
Interact("CVSandr")
END

IF
Global("SanGarQCh","GLOBAL",4)
THEN
RESPONSE #100
SetGlobal("SanGarQCh","GLOBAL",5)
AddSpecialAbility("CVKnok")
AddSpecialAbility("CVBard")
AddSpecialAbility("cvtrap")
END


// Drizzt in BG1
IF
OR(2)
Global("MeetDrizztInBeard","Global",1)
Global("F_MeetDrizztInBeard","Global",1)
!See("F_Drizzt")
Global("SanDrizzt","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanDrizzt","GLOBAL",1)
END

// Breagar

IF
See("ACBre")
CombatCounter(0)
!See([ENEMY])
!StateCheck("ACBre",CD_STATE_NOTVALID)
OR(5)
Global("SanBreBa","GLOBAL",4)
Global("SanBreBa","GLOBAL",1)
Global("SanBreAbb","LOCALS",1)
Global("ACMINEC2","GLOBAL",2)
Global("SanBreBa","GLOBAL",9)
THEN
RESPONSE #100
Interact("CVSandr")
END

IF
Global("SanHealBre","GLOBAL",6)
Global("SanBreBa","GLOBAL",3)
HPPercentLT("ACBre",75)
!See([ENEMY])
!StateCheck("ACBre",CD_STATE_NOTVALID)
THEN
RESPONSE #100
SetGlobal("SanBreBa","GLOBAL",4)
END

IF
InParty("ACBre")
AreaCheck("ac4403")
Global("SanBreAbb","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanBreAbb","LOCALS",1)
END

IF
Global("ACMINEC2","GLOBAL",1)
Delay(12)
THEN
RESPONSE #100
SetGlobal("ACMINEC2","GLOBAL",2)
END

IF
GlobalGT("ACSILVERAPPEARS","GLOBAL",8)
Global("SanBreBa","GLOBAL",7)
!AreaCheck("BG5300")
InParty("ACBre")
THEN
RESPONSE #100
SetGlobal("SanBreBa","GLOBAL",8)
RealSetGlobalTimer("SanBreHaBat","LOCALS",3160)
END

IF
Global("SanBreBa","GLOBAL",8)
RealGlobalTimerExpired("SanBreHaBat","LOCALS")
InParty("ACBre")
AreaType(OUTDOOR)
THEN
RESPONSE #100
SetGlobal("SanBreBa","GLOBAL",9)
END

// Xan

IF
Global("PCKnowsElmDaughter","GLOBAL",1)
InParty("XAN")
Global("SanXanA","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanXanA","GLOBAL",1)
RealSetGlobalTimer("SanXanT","GLOBAL",600)
END

IF
InParty("XAN")
RealGlobalTimerExpired("SanXanT","GLOBAL")
Global("SanXanA","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("SanXanA","GLOBAL",2)
END

IF
InParty("XAN")
RealGlobalTimerExpired("SanXanT","GLOBAL")
Global("SanXanA","GLOBAL",3)
THEN
RESPONSE #100
SetGlobal("SanXanA","GLOBAL",4)
END

IF
InParty("XAN")
RealGlobalTimerExpired("SanXanT","GLOBAL")
Global("SanXanA","GLOBAL",5)
OR(16)
AreaCheck("BG4801")
AreaCheck("BG2616")
AreaCheck("BG3351")
AreaCheck("BG3304")
AreaCheck("BG2301")
AreaCheck("BG0105")
AreaCheck("BG0116")
AreaCheck("BG0119")
AreaCheck("BG0706")
AreaCheck("BG4003")
AreaCheck("BG1001")
AreaCheck("bh0115")
AreaCheck("bh0107")
AreaCheck("BG3357")
AreaCheck("BG0114")
AreaCheck("CVRoa2")
THEN
RESPONSE #100
SetGlobal("SanXanA","GLOBAL",6)
END

IF
InParty("XAN")
RealGlobalTimerExpired("SanXanT","GLOBAL")
Global("SanXanA","GLOBAL",7)
OR(16)
AreaCheck("BG4801")
AreaCheck("BG2616")
AreaCheck("BG3351")
AreaCheck("BG3304")
AreaCheck("BG2301")
AreaCheck("BG0105")
AreaCheck("BG0116")
AreaCheck("BG0119")
AreaCheck("BG0706")
AreaCheck("BG4003")
AreaCheck("BG1001")
AreaCheck("bh0115")
AreaCheck("bh0107")
AreaCheck("BG3357")
AreaCheck("BG0114")
AreaCheck("CVRoa2")
THEN
RESPONSE #100
SetGlobal("SanXanA","GLOBAL",8)
END

IF
GlobalGT("X#IMXA2","GLOBAL",1)
GlobalLT("X#IMXA2","GLOBAL",8)
InParty("XAN")
GlobalGT("SanXanA","GLOBAL",3)
Global("SanXanPink","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanXanPink","LOCALS",1)
END

IF
InParty("XAN")
GlobalGT("SanXanA","GLOBAL",8)
AreaCheck("ar10pb")
!See([ENEMY])
CombatCounter(0)
Global("SanXanFielD","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanXanFielD","LOCALS",1)
END

IF
Global("SanXanA","GLOBAL",23)
RealGlobalTimerExpired("SanXanT","GLOBAL")
OR(2)
Global("X#XQFriendlyArmsMoved","GLOBAL",3)
Global("X#XQXanrewarded","GLOBAL",2)
AreaType(CITY)
THEN
RESPONSE #100
CreateCreatureObjectOffset("sanboy1",Myself,[75.75]) 
SetGlobal("SanXanA","GLOBAL",24)
Wait(2)
ActionOverride("Sanboy1",StartDialogueNoSet([PC]))
END

IF
Global("SanXanPink","LOCALS",2)
Global("X#IMXA2","GLOBAL",8)
InParty("XAN")
!AreaType(OUTDOOR)
THEN
RESPONSE #100
SetGlobal("SanXanPink","LOCALS",3)
END

IF
See("Xan")
!See([ENEMY])
CombatCounter(0)
!StateCheck("Xan",CD_STATE_NOTVALID)
OR(22)
Global("SanXanA","GLOBAL",2)
Global("SanXanA","GLOBAL",4)
Global("SanXanA","GLOBAL",6)
Global("SanXanA","GLOBAL",8)
Global("SanXanA","GLOBAL",12)
Global("SanXanA","GLOBAL",14)
Global("SanXanA","GLOBAL",16)
Global("SanXanA","GLOBAL",18)
Global("SanXanA","GLOBAL",20)
Global("SanXanA","GLOBAL",22)
Global("SanXanPCL","GLOBAL",1)
Global("SanXanPCL","GLOBAL",3)
Global("CentXan","GLOBAL",1)
Global("SanXanPCL","GLOBAL",6)
Global("XanDecide","GLOBAL",2)
Global("XanDecide","GLOBAL",5)
Global("SanXanPink","LOCALS",1)
Global("SanXanPink","LOCALS",3)
Global("SanXanFielD","LOCALS",1)
Global("SanXanNashRet","LOCALS",1)
Global("SanXanSurvWit","LOCALS",1)
Global("SanXanSurv","LOCALS",1)
THEN
RESPONSE #100
MoveToObject("Xan")
Interact("CVSandr")
END

IF
GlobalGT("SanXanA","GLOBAL",6)
Global("SanRomPath","GLOBAL",2)
!AreaType(CITY)
AreaType(OUTDOOR)
InParty("Xan")
Global("SanXanPC","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanXanPC","GLOBAL",1)
END

IF
Global("SanXanPC","GLOBAL",1)
!See([ENEMY])
CombatCounter(0)
!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogNoSet("CVSandr")
END

IF
Global("SanXanA","GLOBAL",11)
RealGlobalTimerExpired("SanXanT","GLOBAL")
!TimeOfDay(DAY)
InParty("Xan")
!AreaType(OUTDOOR)
See("Xan")
THEN
RESPONSE #100
SetGlobal("SanXanA","GLOBAL",12)
END

IF
Global("SanXanA","GLOBAL",13)
RealGlobalTimerExpired("SanXanT","GLOBAL")
!TimeOfDay(DAY)
!AreaType(DUNGEON)
THEN
RESPONSE #100
SetGlobal("SanXanA","GLOBAL",14)
END

IF
GlobalGT("X#XALOVETALK","GLOBAL",22)
InParty("XAN")
!TimeOfDay(NIGHT)
!AreaType(OUTDOOR)
Global("SanXanPCL","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanXanPCL","GLOBAL",1)
END

IF
Global("SanXanPCL","GLOBAL",2)
InParty("XAN")
AreaType(DUNGEON)
THEN
RESPONSE #100
SetGlobal("SanXanPCL","GLOBAL",3)
END

IF
!Global("ENDOFBG1","GLOBAL",2)
GlobalGT("SanXanA","GLOBAL",13)
Global("Chapter","GLOBAL",5)
InParty("XAN")
AreaCheck("BG1800")
Global("SanXanPCL","GLOBAL",4)
THEN
RESPONSE #100
SetGlobal("SanXanPCL","GLOBAL",5)
RealSetGlobalTimer("SanXanT","GLOBAL",1200)
END

IF
RealGlobalTimerExpired("SanXanT","GLOBAL")
Global("SanXanPCL","GLOBAL",5)
!AreaType(DUNGEON)
THEN
RESPONSE #100
SetGlobal("SanXanPCL","GLOBAL",6)
END

IF
Global("X#XALOVETALK","GLOBAL",39)
InParty("XAN")
Global("XanDecide","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("XanDecide","GLOBAL",1)
RealSetGlobalTimer("SanXanT","GLOBAL",420)
END

IF
RealGlobalTimerExpired("SanXanT","GLOBAL")
Global("XanDecide","GLOBAL",1)
InParty("XAN")
THEN
RESPONSE #100
SetGlobal("XanDecide","GLOBAL",2)
END

IF
Global("X#XALOVETALK","GLOBAL",43)
InParty("XAN")
Global("XanDecide","GLOBAL",3)
THEN
RESPONSE #100
SetGlobal("XanDecide","GLOBAL",4)
RealSetGlobalTimer("SanXanT","GLOBAL",420)
END

IF
RealGlobalTimerExpired("SanXanT","GLOBAL")
Global("XanDecide","GLOBAL",4)
InParty("XAN")
THEN
RESPONSE #100
SetGlobal("XanDecide","GLOBAL",5)
END

IF
!Global("ENDOFBG1","GLOBAL",2)
Global("XanDecide","GLOBAL",8)
THEN
RESPONSE #100
SetGlobal("XanDecide","GLOBAL",9)
AddSpecialAbility("CVDrag3")
END

IF
Global("ENDOFBG1","GLOBAL",1)
InParty("XAN")
RealGlobalTimerExpired("SanXanT","GLOBAL")
GlobalGT("SanXanA","GLOBAL",14)
Global("SanXanSurv","LOCALS",0)
OR(16)
AreaCheck("BG4801")
AreaCheck("BG2616")
AreaCheck("BG3351")
AreaCheck("BG3304")
AreaCheck("BG2301")
AreaCheck("BG0105")
AreaCheck("BG0116")
AreaCheck("BG0119")
AreaCheck("BG0706")
AreaCheck("BG4003")
AreaCheck("BG1001")
AreaCheck("bh0115")
AreaCheck("bh0107")
AreaCheck("BG3357")
AreaCheck("BG0114")
AreaCheck("CVRoa2")
THEN
RESPONSE #100
SetGlobal("SanXanSurv","LOCALS",1)
END

// Xan if no PC Romance
IF
RealGlobalTimerExpired("SanXanT","GLOBAL")  
InParty("Xan")
OR(2)
Global("X#XARomanceInactive","GLOBAL",1)
Global("SanRomPath","GLOBAL",1)
OR(4)
Global("SanXanA","GLOBAL",15)
Global("SanXanA","GLOBAL",17)
Global("SanXanA","GLOBAL",19)
Global("SanXanA","GLOBAL",21)
THEN
RESPONSE #100
IncrementGlobal("SanXanA","GLOBAL",1)
END

IF
!Global("ENDOFBG1","GLOBAL",2)
GlobalGT("SanXanA","GLOBAL",16)
Global("Chapter","GLOBAL",5)
InParty("XAN")
Global("SanXanSurvWit","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanXanSurvWit","LOCALS",1)
END

// Yeslick
IF
InParty("Yeslick")
Dead("Davaeorn")
Global("SanYesl","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanYesl","GLOBAL",1)
RealSetGlobalTimer("SanYeslTa","LOCALS",850)
END

IF
RealGlobalTimerExpired("SanYeslTa","LOCALS")
Global("SanYesl","GLOBAL",1)
InParty("Yeslick")
THEN
RESPONSE #100
SetGlobal("SanYesl","GLOBAL",2)
END

IF
See("Yeslick")
!StateCheck("Yeslick",CD_STATE_NOTVALID)
!StateCheck("CVSandr",CD_STATE_NOTVALID)
CombatCounter(0)
!See([ENEMY])
OR(2)
Global("SanYesl","GLOBAL",2)
Global("SanYesl","GLOBAL",4)
THEN
RESPONSE #100
MoveToObject("Yeslick")
Interact("CVSandr")
END


// Tiax

IF
InParty("Tiax")
!AreaCheck("BG3300")
!AreaCheck("BG1100")
Global("Santiax","LOCALS",0)
Delay(12)
THEN
RESPONSE #100
SetGlobal("Santiax","LOCALS",1)
END

IF
Global("Santiax","LOCALS",2) 
RealGlobalTimerExpired("SantiaxTa","LOCALS")
InParty("Tiax")
!TimeOfDay(DAY)
GlobalGT("PCKnowsElmDaughter","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("Santiax","LOCALS",3)
END

IF
See("Tiax")
!StateCheck("Tiax",CD_STATE_NOTVALID)
!StateCheck("CVSandr",CD_STATE_NOTVALID)
CombatCounter(0)
!See([ENEMY])
OR(2)
Global("Santiax","LOCALS",1)
Global("Santiax","LOCALS",3)
THEN
RESPONSE #100
MoveToObject("Tiax")
Interact("CVSandr")
END


//Triggered Imo
IF
Global("SanImoElm1","GLOBAL",0)
Global("X#ImoenElmin1","GLOBAL",1)
InParty("Imoen2")                                 
THEN
RESPONSE #100
SetGlobal("SanImoElm1","GLOBAL",1)
END

IF
Global("SanImoPCInterest","GLOBAL",0)
InParty("Imoen2")
GlobalGT("SandrahMorningTalk","GLOBAL",9)
GlobalGT("SandrahLT","GLOBAL",1)
AreaType(FOREST)
THEN
RESPONSE #100
SetGlobal("SanImoPCInterest","GLOBAL",1)
END

IF
Global("X#IMForeshadow","GLOBAL",2)
InParty("Imoen2")
THEN
RESPONSE #100
SetGlobal("X#IMForeshadow","GLOBAL",3)
Interact("CVSandr")
END

IF
Global("X#ImoenBereg","GLOBAL",2)
AreaCheck("BG3300")
InParty("Imoen2")
THEN
RESPONSE #100
SetGlobal("X#ImoenBereg","GLOBAL",3)
Interact("CVSandr")
END

IF
InParty("Imoen2")
!AreaCheck("bg2300")
!AreaType(CITY)
!See([ENEMY])
AreaType(OUTDOOR)
TimeOfDay(DUSK)
Global("ImoHousew","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("ImoHousew","GLOBAL",1)
END

IF
!Global("ENDOFBG1","GLOBAL",2)
InParty("Imoen2")
AreaCheck("BG3600")
GlobalGT("Chapter","GLOBAL",2)
Global("PallonTalk","GLOBAL",0)
OR(4)
Global("X#Pallon1","GLOBAL",1)
Global("X#Pallon2","GLOBAL",1)
Global("X#Pallon3","GLOBAL",1)
Global("X#Pallon4","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("PallonTalk","GLOBAL",1)
END

IF
InParty("Imoen2")
Global("PallonTalk","GLOBAL",0)
OR(3)
See("Gaxir")
See("Divine")
See("Lantanara")
THEN
RESPONSE #100
SetGlobal("PallonTalk","GLOBAL",1)
END

IF
AreaCheck("BG3320")
See("Nobl10")
InParty("Imoen2")
Global("ImoTravGlimps","GLOBAL",0)
GlobalLT("OrcPrison","GLOBAL",16)
THEN
RESPONSE #100
SetGlobal("ImoTravGlimps","GLOBAL",1)
RealSetGlobalTimer("ImoMansTi","LOCALS",35)
END

IF
RealGlobalTimerExpired("ImoMansTi","LOCALS")
Global("ImoTravGlimps","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("ImoTravGlimps","GLOBAL",2)
END

IF
AreaCheck("BG4300")
InParty("Imoen2")
Global("SanImoGrMa","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanImoGrMa","GLOBAL",1)
END

IF
Global("Cowscroll","GLOBAL",12)
RealGlobalTimerExpired("CowscrollT","GLOBAL")
InParty("Edwin")
InParty("Imoen2")
TimeOfDay(DAY)
!AreaType(OUTDOOR)
Global("SanImoEd","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanImoEd","LOCALS",1)
END

IF
Global("ImoNashSK","GLOBAL",1)
!AreaCheck("BG4803")
!AreaCheck("BG4800")
InParty("Imoen2")
Global("SanImoNashInt","GLOBAL",0)
!Global("Imoenclasschoice","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("SanImoNashInt","GLOBAL",1)
END

IF
Global("SanImoNashInt","GLOBAL",2) 
RealGlobalTimerExpired("SanImoNashIntT","GLOBAL")
InParty("Imoen2")
AreaCheck("BG4800")
THEN
RESPONSE #100
SetGlobal("SanImoNashInt","GLOBAL",3)
END

IF
InParty("Imoen2")
Global("ImopeltHunt","GLOBAL",0)
OR(2)
Global("SanImoNashInt","GLOBAL",2)
Global("SanImoNashInt","GLOBAL",4)
OR(4)
AreaCheck("BG5200")
AreaCheck("BG5400")
AreaCheck("BG5300")
AreaType(FOREST)
THEN
RESPONSE #100
SetGlobal("ImopeltHunt","GLOBAL",1)
END

IF
InParty("Imoen2")
!AreaCheck("BG4803")
!AreaCheck("BG4800")
Global("SanImoNashInt","GLOBAL",5)
THEN
RESPONSE #100
SetGlobal("SanImoNashInt","GLOBAL",6)
END

IF
InParty("Imoen2")
AreaCheck("BG4803")
Global("SanImoNashInt","GLOBAL",6)
THEN
RESPONSE #100
SetGlobal("SanImoNashInt","GLOBAL",7)
END

IF
Global("SanImoNashInt","GLOBAL",8)
PartyHasItem("imofurc")
InParty("Imoen2")
!AreaCheck("BG4803")
!AreaCheck("BG4800")
THEN
RESPONSE #100
SetGlobal("SanImoNashInt","GLOBAL",9)
END

IF
GlobalGT("SanImoNashInt","GLOBAL",9)
GlobalLT("SanImoNashInt","GLOBAL",14)
Global("SanImoLoveLet","GLOBAL",0)
AreaType(CITY)
PartyHasItem("imofurc")
InParty("Imoen2")
!AreaCheck("BG4800")
THEN
RESPONSE #100
SetGlobal("SanImoLoveLet","GLOBAL",1)
END

IF
!Global("ENDOFBG1","GLOBAL",2)
Global("SanImoNashInt","GLOBAL",11)
GlobalGT("Chapter","GLOBAL",2)
!AreaCheck("BG4803")
!AreaCheck("BG4800")
!AreaCheck("BG4801")
!AreaCheck("BG4802")
!AreaCheck("BG4804")
!AreaCheck("BG4805")
!AreaCheck("BG4806")
!AreaCheck("BG4807")
!AreaCheck("BG4808")
!AreaCheck("BG4809")
!AreaCheck("BG4810")
THEN
RESPONSE #100
SetGlobal("SanImoNashInt","GLOBAL",12)
RealSetGlobalTimer("SanImoNashRet","GLOBAL",ONE_DAY)
END

IF
Global("SanImoNashInt","GLOBAL",12)
!AreaCheck("BG4803")
OR(3)
RealGlobalTimerExpired("SanImoNashRet","GLOBAL")
AreaCheck("BG2900")
AreaCheck("BG2400")
Global("SanThruNasM","GLOBAL",2)
Global("SanImoNashRaid","GLOBAL",0)
CombatCounter(0)
!See([ENEMY])
AreaType(OUTDOOR)
THEN
RESPONSE #100
SetGlobal("SanImoNashRaid","GLOBAL",1)
CreateCreatureObject("SanNaWi",Myself,0,0,0)
RealSetGlobalTimer("SanImoNashRet","GLOBAL",SIX_DAYS)
END

IF
Global("SanImoNashInt","GLOBAL",12)
AreaCheck("BG4803")
RealGlobalTimerExpired("SanImoNashRet","GLOBAL")
THEN
RESPONSE #100
SetGlobal("SanImoNashInt","GLOBAL",13)
CreateCreature("Sanana",[244.200],8)
END

IF
Global("SanImoNashInt","GLOBAL",12)
AreaCheck("BG4803")
!RealGlobalTimerExpired("SanImoNashRet","GLOBAL")
THEN
RESPONSE #100
SetGlobal("SanImoNashInt","GLOBAL",14)
ActionOverride("Shopkn",DestroySelf())
END

IF
Global("SanImoNashInt","GLOBAL",16)
AreaCheck("BG4800")
!InMyArea("Berrun")
Global("BerHenEx","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("BerHenEx","LOCALS",1)
CreateCreature("Berrun",[2365.1308],6)
END

IF
Global("SANIMONASHINT","GLOBAL",17)
Global("SanOrkWitn","LOCALS",0)
AreaType(OUTDOOR)
!AreaType(CITY)
THEN
RESPONSE #100
SetGlobal("SanOrkWitn","LOCALS",1)
RealSetGlobalTimer("SanOrkWitnA","LOCALS",125)
END

IF
RealGlobalTimerExpired("SanOrkWitnA","LOCALS")
Global("SanOrkWitn","LOCALS",1)
AreaType(OUTDOOR)
CombatCounter(0)
!AreaType(CITY)                               
!See([ENEMY])
THEN
RESPONSE #100
SetGlobal("SanOrkWitn","LOCALS",2)
CreateCreatureObject("SanOrWi",Myself,0,0,0)
END

IF
Dead("Rellruk")
Global("SANIMONASHINT","GLOBAL",17)
THEN
RESPONSE #100
SetGlobal("SANIMONASHINT","GLOBAL",18)
END

IF
Global("SANIMONASHINT","GLOBAL",18)
!See([ENEMY])
!AreaCheck("CVORCA")
CombatCounter(0)
!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogNoSet("CVSandr")
END

IF
OR(2)
AreaCheck("BG1903")
AreaCheck("arr019")
InParty("Imoen2")
See("Orcimo1")
Global("Orcimo1T","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("Orcimo1T","LOCALS",1)
END

IF
Global("Orcimo1T","LOCALS",1)
OR(2)
AreaCheck("BG1903")
AreaCheck("arr019")
!See([ENEMY])
CombatCounter(0)
!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
RESPONSE #100
MoveToObject(Player1)
SetGlobal("Orcimo1T","LOCALS",2)
StartDialogNoSet("CVSandr")
END

IF 
Global("SanClkWo","GLOBAL",0)
InParty("Imoen2")
AreaCheck("BG2100")
PartyHasItem("misc90")
GlobalGT("Orcimo1T","LOCALS",1)
THEN
RESPONSE #100
SetGlobal("SanClkWo","GLOBAL",1)
END

IF
Global("OrcPrison","GLOBAL",2)
AreaCheck("BG1804")
InParty("Imoen2")
Dead("CVORW4")
Global("SanPrisDo","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanPrisDo","GLOBAL",1)
END

IF
InParty("Imoen2")
AreaCheck("CVORC2")
See("CVORW1")
Global("OrcPrison","GLOBAL",6)
THEN
RESPONSE #100
SetGlobal("OrcPrison","GLOBAL",7)
ActionOverride("Imoen2",CreateItem("ImoSlHP1",0,0,0))
ActionOverride("Imoen2",FillSlot(SLOT_AMULET))
ActionOverride("Imoen2",ReallyForceSpell(Myself,SLAYER_IMMUNE_TO_DAMAGE))
ActionOverride("Imoen2",MakeUnselectable(20))
ActionOverride("Imoen2",ReallyForceSpellRES("Imoslay1",Myself))
ActionOverride("Imoen2",Attack("CVORW1"))
END

IF
Dead("CVORW1")
Global("OrcPrison","GLOBAL",7)
THEN
RESPONSE #100
SetGlobal("OrcPrison","GLOBAL",8)
END

IF
See("CVKNAW")
InParty("Imoen2")
!Dead("Imoen2")
Global("OrcPrison","GLOBAL",9)
THEN
RESPONSE #100
SetGlobal("OrcPrison","GLOBAL",10)
ActionOverride("Imoen2",DestroyItem("ImoSlHP1"))
END

IF
Global("OrcPrison","GLOBAL",11)
THEN
RESPONSE #100
SetGlobal("OrcPrison","GLOBAL",12)
GiveItemCreate("SanHenHu","CVSandr",0,0,0)
ActionOverride("Shopknhu",DestroySelf())
END

IF
Global("OrcPrison","GLOBAL",12)
Dead("CVKNAW")
PartyHasItem("SanHenHu")
THEN
RESPONSE #100
SetGlobal("OrcPrison","GLOBAL",13)
EraseJournalEntry(@186)
EraseJournalEntry(@955)
END

IF
!See([ENEMY])
See("Imoen2")
CombatCounter(0)
!StateCheck(Player1,CD_STATE_NOTVALID)
Global("OrcPrison","GLOBAL",9)
Global("SanImoFiSl","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanImoFiSl","LOCALS",1)
StartDialogNoSet("CVSandr")
END

IF
See(Player1)
AreaCheck("BG1804")
Global("OrcPrison","GLOBAL",15)
!See([ENEMY])
CombatCounter(0)
!StateCheck(Player1,CD_STATE_NOTVALID)
THEN
RESPONSE #100
StartDialogNoSet("CVSandr")
END

IF
GlobalGT("SANIMONASHINT","GLOBAL",18)
InParty("Imoen2")
Dead("Davaeorn")
Global("SanImoRetWD","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanImoRetWD","GLOBAL",1)
SetGlobalTimer("SanImoRetWDC","LOCALS",TEN_DAYS)
END

IF
GlobalTimerExpired("SanImoRetWDC","LOCALS")
Global("SanImoRetWD","GLOBAL",1)
GlobalLT("OrcPrison","GLOBAL",27)
THEN
RESPONSE #100
SetGlobal("SanImoRetWD","GLOBAL",2)
END

IF
GlobalTimerExpired("SanImoRetWDC","LOCALS")
Global("SanImoRetWD","GLOBAL",1)
GlobalGT("OrcPrison","GLOBAL",26)
THEN
RESPONSE #100
SetGlobal("SanImoRetWD","GLOBAL",3)
END

// The Orphanage of Beregost

IF
Global("OrcPrison","GLOBAL",16)
InParty("Imoen2")
AreaCheck("BG3300")
PartyHasItem("CVTravMo")
THEN
RESPONSE #100
SetGlobal("OrcPrison","GLOBAL",17)
END

IF
Global("OrcPrison","GLOBAL",18)
AreaCheck("BG3402")
InParty("Imoen2")
PartyHasItem("CVTravMo")
THEN
RESPONSE #100
SetGlobal("OrcPrison","GLOBAL",19)
END

IF
GlobalLT("OrcPrison","GLOBAL",21) 
GlobalGT("OrcPrison","GLOBAL",18)
Global("KeldPriTrav","LOCALS",0)
AreaCheck("BG3402")
InParty("Imoen2")
PartyHasItem("CVTravMo")
THEN
RESPONSE #100
SetGlobal("KeldPriTrav","LOCALS",1)
Interact(Player1)
END

IF
Global("OrcPrison","GLOBAL",25)
AreaCheck("BG3402")
InParty("Imoen2")
PartyHasItem("CVTravMo")
PartyHasItem("CVTravde")
THEN
RESPONSE #100
SetGlobal("OrcPrison","GLOBAL",26)
END

IF
Global("OrcPrison","GLOBAL",22)
InParty("Imoen2")
PartyHasItem("CVTravde")
THEN
RESPONSE #100
SetGlobal("OrcPrison","GLOBAL",23)
DisplayStringHead("Imoen2",@263)
AddexperienceParty(9500)
END

IF
Global("OrcPrison","GLOBAL",23)
InParty("Imoen2")
PartyHasItem("CVTravde")
!AreaCheck("BG3321")
!AreaCheck("BG3320")
THEN
RESPONSE #100
SetGlobal("OrcPrison","GLOBAL",24)
END

IF
Global("OrcPrison","GLOBAL",27)
Global("Orphitems","LOCALS",0)
THEN
RESPONSE #100
TakePartyItem("CVTRAVDE")
TakePartyItem("CVTRAVMO")
DestroyItem("CVTRAVDE")
DestroyItem("CVTRAVMO")
SetGlobal("Orphitems","LOCALS",1)
END

IF
RealGlobalTimerExpired("BeregOrphOpen","GLOBAL")
Global("OrcPrison","GLOBAL",27)
THEN
RESPONSE #100
SetGlobal("OrcPrison","GLOBAL",28)
END

IF
Global("OrcPrison","GLOBAL",28)
AreaCheck("BG3300")
InParty("Imoen2")
THEN
RESPONSE #100
SetGlobal("OrcPrison","GLOBAL",29)
END

IF
Global("SanImohelmKill","LOCALS",0)
InParty("Imoen2")
InParty("Ajantis")
AreaType(CITY)
GlobalGT("Chapter","Global",2)
THEN
RESPONSE #100
SetGlobal("SanImohelmKill","LOCALS",1)
END

IF
!See([ENEMY])
CombatCounter(0)
InParty("Imoen2")
!StateCheck(Player1,CD_STATE_NOTVALID)
!StateCheck("Imoen2",CD_STATE_NOTVALID)
OR(9)
Global("OrcPrison","GLOBAL",17)
Global("OrcPrison","GLOBAL",19)
Global("OrcPrison","GLOBAL",24)
Global("OrcPrison","GLOBAL",26)
Global("OrcPrison","GLOBAL",29)
Global("SanImoRetWD","GLOBAL",2)
Global("SanImoRetWD","GLOBAL",3)
Global("SanImoRetCK","LOCALS",1)
Global("SanImohelmKill","LOCALS",1)
THEN
RESPONSE #100
Interact(Player1)
END

IF
NumItemsPartyGT("CVPirbag",0)
GlobalGT("OrcPrison","GLOBAL",28)
Global("PirTresDon","GLOBAL",0)
OR(3)
AreaCheck("BG3400")
AreaCheck("BG3402")
AreaCheck("BG3300")
THEN
RESPONSE #100
SetGlobal("PirTresDon","GLOBAL",1)
END

IF
NumItemsParty("CVPirbag",0)
Global("PirTresDon","GLOBAL",2)
THEN
RESPONSE #100
SetGlobal("PirTresDon","GLOBAL",3)
END

IF
AreaCheck("CVDre2")
See("Henning2")
InParty("Imoen2")
Global("SanImoRetWD","GLOBAL",4)
THEN
RESPONSE #100
SetGlobal("SanImoRetWD","GLOBAL",5)
ActionOverride("henning2",MoveToPointNoInterrupt([790.877]))
ActionOverride("Imoen2",MoveToPointNoInterrupt([790.877]))
END

IF
Global("SanImoRetWD","GLOBAL",5)
THEN
RESPONSE #100
SetGlobal("SanImoRetWD","GLOBAL",6)
Wait(3)
Interact(Player1)
END

//Naskel Mine
IF
AreaCheck("BG5402")
!See([ENEMY])
Global("SaNasIro","GLOBAL",0)
OR(5)
See("Container9")
See("Container2")
See("Container3")
See("Container4")
See("Container7")
THEN
RESPONSE #100
SetGlobal("SaNasIro","GLOBAL",1)
END

//Trigger Bounty Hunters

IF
Dead("Tarnesh")
AreaCheck("bg2300")
Global("Tarded","GLOBAL",0)
!InParty("Imoen2")
THEN
RESPONSE #100
SetGlobal("Tarded","GLOBAL",1)
END

IF
Dead("Tarnesh")
AreaCheck("bg2300")
Global("Tarded","GLOBAL",0)
InParty("Imoen2")
!StateCheck("Imoen2",CD_STATE_NOTVALID)
THEN
RESPONSE #100
SetGlobal("Tarded","GLOBAL",1)
END

IF
!StateCheck(Player1,CD_STATE_NOTVALID)
Global("Tarded","GLOBAL",1)
CombatCounter(0)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogNoSet("CVSandr")
END

//Haeball
IF
Global("9001Fi","GLOBAL",1)
!AreaCheck("ar9001")
!AreaCheck("ar9002")
CombatCounter(0)
THEN
RESPONSE #100
SetGlobal("9001Fi","GLOBAL",2)
MoveToObject(Player1)
StartDialogNoSet("CVSandr")
END

IF
OR(2)
Global("MeetIndfigtToOffer","GLOBAL",1)
Global("NTMeetIndfigtToOffer","GLOBAL",1)
AreaCheck("ar82pb")
Global("9001Fi","GLOBAL",3)
!PartyHasItem("NTMISC06")
THEN
RESPONSE #100
SetGlobal("9001Fi","GLOBAL",4)
END

IF
GlobalGT("9001Fi","GLOBAL",2)
Global("SanNTFalseWarn","LOCALS",2)
Global("SanOrcCKey","LOCALS",0)
!AreaCheck("ar01pb")
PartyHasItem("ntkeypb3")
THEN
RESPONSE #100
SetGlobal("SanOrcCKey","LOCALS",1)
END

IF
OR(3) 
Global("TalkedToHasdar1","GLOBAL",1)
Global("NTTalkedToHasdar","GLOBAL",2)
Global("NTTalkedToHasdar","GLOBAL",3)
GlobalLT("SanKnowsHasdId","GLOBAL",3)
Global("Hasntlet","LOCALS",0)
PartyHasItem("ntpblet2")
THEN
RESPONSE #100
SetGlobal("Hasntlet","LOCALS",1)
IncrementGlobal("SanKnowsHasdId","GLOBAL",1)
END

IF
OR(3)
Global("TalkedToHasdar1","GLOBAL",1)
Global("NTTalkedToHasdar","GLOBAL",2)
Global("NTTalkedToHasdar","GLOBAL",3)
GlobalLT("SanKnowsHasdId","GLOBAL",3)
Global("Hasntmisc","LOCALS",0)
PartyHasItem("ntmisc10")
THEN
RESPONSE #100
SetGlobal("Hasntmisc","LOCALS",1)
IncrementGlobal("SanKnowsHasdId","GLOBAL",1)
END

IF
OR(3)
Global("TalkedToHasdar1","GLOBAL",1)
Global("NTTalkedToHasdar","GLOBAL",2)
Global("NTTalkedToHasdar","GLOBAL",3)
GlobalLT("SanKnowsHasdId","GLOBAL",3)
Global("Hasnkey3","LOCALS",0)
PartyHasItem("ntkeypb3")
THEN
RESPONSE #100
SetGlobal("Hasnkey3","LOCALS",1)
IncrementGlobal("SanKnowsHasdId","GLOBAL",1)
END
        
IF
GlobalLT("SanKnowsHasdId","GLOBAL",5)
PartyHasItem("ntkeypb2")
THEN
RESPONSE #100
SetGlobal("SanKnowsHasdId","GLOBAL",6)
END

IF
OR(2)
Global("TalkedToHasdar1","GLOBAL",2)
Global("NTTalkedToHasdar","GLOBAL",4) 
!Dead("NTDRAAGI")
Global("SanKnowsHasdId","GLOBAL",4)
THEN
RESPONSE #100
SetGlobal("SanKnowsHasdId","GLOBAL",5)
END

//  Red Wizards in East Wood

IF
AreaCheck("BG3000")
Dead("denak")
Dead("diana")
Dead("brendan")
Global("sanredatt","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("sanredatt","GLOBAL",1)
END

IF
AreaCheck("BG3000")
Global("VestibuleQuest","GLOBAL",5)
Global("sanredatt","GLOBAL",0)
Delay(12)
THEN
RESPONSE #100
SetGlobal("sanredatt","GLOBAL",1)
END

IF
AreaCheck("BG3000")
Global("VestibuleQuest","GLOBAL",5)
Global("sanredatt","GLOBAL",2)
InParty("Edwin")
THEN
RESPONSE #100
SetGlobal("sanredatt","GLOBAL",3)
END


//Samuel and the Deserters
IF
Global("SanDesertersAmb","LOCALS",1)
OR(2)
PartyHasItem("Misc13L")
PartyHasItem("Misc13")
!AreaCheck("BG5500")
!AreaCheck("bg2300")
Delay(8)
THEN
RESPONSE #100
CreateCreatureObjectOffScreen("CVBandf4","CVSandr",500,500,0)
CreateCreatureObjectOffScreen("CVBande2","CVSandr",350,350,0)
CreateCreatureObjectOffScreen("CVBande2","CVSandr",-100,-300,0)
SetGlobal("SanDesertersAmb","LOCALS",2)
END

IF
Global("SanSamSp","BG5500",2)
Global("SanDesertersAmb","LOCALS",0)
AreaCheck("BG5500")
!See([ENEMY])
!StateCheck(Player1,CD_STATE_NOTVALID)
CombatCounter(0)
See(Player1)
OR(2)
PartyHasItem("Misc13L")
PartyHasItem("Misc13")
Delay(12)
THEN
RESPONSE #100
CreateCreatureObject("CVSamhu","CVSandr",-10,-30,0)
SetGlobal("SanDesertersAmb","LOCALS",1)
END

IF
InParty("CVSandr")
PartyHasItem("Misc13L")
GlobalTimerExpired("Samuel","GLOBAL")
THEN
RESPONSE #100
TakePartyItem("Misc13L")
GiveItemCreate("Misc13","CVSandr",0,0,0)
END

// Return to Candlekeep
IF
Global("SanCandlOgr","LOCALS",0)
PartyHasItem("CVOGscr")
!AreaCheck("ar12pb")
THEN
RESPONSE #100
SetGlobal("SanCandlOgr","LOCALS",1)
END

IF
AreaCheck("BG2626")
InParty("Imoen2")
GlobalGT("Formedcloth","GLOBAL",23)
OR(2 )
See("rabbit")
See("Rabbit01")
Global("SanImoRetCK","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanImoRetCK","LOCALS",1)
END

IF
AreaCheck("BG2608") 
Global("SanLibCommt1","LOCALS",0)
OR(2)
PartyHasItem("scrl3d")
See("Container20")
THEN
RESPONSE #100
SetGlobal("SanLibCommt1","LOCALS",1)
END

IF
Global("SanLibCommt1","LOCALS",2)
THEN
RESPONSE #100
ActionOverride(Player1,ForceSpell(Myself,CLERIC_HEAL))
ActionOverride(Player2,ForceSpell(Myself,CLERIC_HEAL))
ActionOverride(Player3,ForceSpell(Myself,CLERIC_HEAL))
ActionOverride(Player4,ForceSpell(Myself,CLERIC_HEAL))
ActionOverride(Player5,ForceSpell(Myself,CLERIC_HEAL))
ActionOverride(Player6,ForceSpell(Myself,CLERIC_HEAL))
SetGlobal("SanLibCommt1","LOCALS",3)
END

IF
AreaCheck("BG2609")
OR(2)
Global("Criminal","GLOBAL",1)
Global("KillReiltar","GLOBAL",1)
Global("SanLibCommt2","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanLibCommt2","LOCALS",1)
SetGlobal("Criminal","GLOBAL",6)
END

IF
Global("Criminal","GLOBAL",6)
PartyHasItem("scrl2J")
!AreaCheck("BG2612")
THEN
RESPONSE #100
SetGlobal("Criminal","GLOBAL",1)
END

IF
AreaCheck("BG5506")
Global("SanLibCommt3","LOCALS",0)
Dead("Prat")
THEN
RESPONSE #100
SetGlobal("SanLibCommt3","LOCALS",1)
END

// First Viconia Banter

IF
RealGlobalTimerExpired("VicBantT","GLOBAL")
Global("VicBant1","GLOBAL",0)
InParty("Viconia")
AreaType(OUTDOOR)
Gender(Player1,MALE)
THEN
RESPONSE #100
SetGlobal("VicBant1","GLOBAL",1)
END

IF
RealGlobalTimerExpired("VicBantT","GLOBAL")
Global("VicBant2","GLOBAL",0)
InParty("Viconia")
AreaType(OUTDOOR)
Gender(Player1,FEMALE)
THEN
RESPONSE #100
SetGlobal("VicBant2","GLOBAL",1)
END

// Second Viconia (Give Piece)

IF
!Global("ENDOFBG1","GLOBAL",2)
RealGlobalTimerExpired("VicBantT","GLOBAL")
InParty("Viconia")
Global("VicBant3","GLOBAL",0)
OR(2)
Global("VicBant1","GLOBAL",2)
Global("VicBant2","GLOBAL",2)
THEN
RESPONSE #100
SetGlobal("VicBant3","GLOBAL",1)
END

// Third Viconia (Murder)

IF
!Global("ENDOFBG1","GLOBAL",2)
Global("VicBant3","GLOBAL",2)
RealGlobalTimerExpired("VicBantT","GLOBAL")
InParty("Viconia")
!AreaCheck("BG5000")
!AreaCheck("BG5404")
!AreaCheck("BG5405")
THEN
RESPONSE #100
SetGlobal("VicBant3","GLOBAL",3)
END


//Fourth Viconia (Learning the Art)
IF
RealGlobalTimerExpired("VicBantT","GLOBAL")
Global("VicBant3","GLOBAL",4)
GlobalGT("Chapter","GLOBAL",2)
InParty("Viconia")
!AreaType(DUNGEON)
!AreaCheck("BG5000")
THEN
RESPONSE #100
SetGlobal("VicBant3","GLOBAL",5)
END

IF 
See("Viconia")
!StateCheck("Viconia",CD_STATE_NOTVALID)
!StateCheck("CVSandr",CD_STATE_NOTVALID)
!See([ENEMY])
CombatCounter(0)
OR(14)
Global("VicBant1","GLOBAL",1)
Global("VicBant2","GLOBAL",1)
Global("VicBant3","GLOBAL",1)
Global("VicBant3","GLOBAL",3)
Global("VicBant3","GLOBAL",5)
Global("SanVicInnLov","LOCALS",1)
Global("SanVicInnLov","LOCALS",3)
Global("SanVicInnLov","LOCALS",5)
Global("SanVicInnLov","LOCALS",7)
Global("SanVicInnLov","LOCALS",11)
Global("SanVicInnLov","LOCALS",13)
Global("SanVicInnLov","LOCALS",15)
Global("SanVicInnLov","LOCALS",17)
Global("spawnDrow1","AR2100",2)
THEN
RESPONSE #100
MoveToObject("Viconia")
Interact("CVSandr")
END

IF
!Global("ENDOFBG1","GLOBAL",2)
InParty("Viconia")
GlobalGT("Chapter","GLOBAL",4)
OR(16)
AreaCheck("BG4801")
AreaCheck("BG2616")
AreaCheck("BG3351")
AreaCheck("BG3304")
AreaCheck("BG2301")
AreaCheck("BG0105")
AreaCheck("BG0116")
AreaCheck("BG0119")
AreaCheck("BG0706")
AreaCheck("BG4003")
AreaCheck("BG1001")
AreaCheck("bh0115")
AreaCheck("bh0107")
AreaCheck("BG3357")
AreaCheck("BG0114")
AreaCheck("CVRoa2")
Global("SanVicInnLov","LOCALS",0)
Delay(8)
THEN
RESPONSE #100
SetGlobal("SanVicInnLov","LOCALS",1)
END

IF
Global("ENDOFBG1","GLOBAL",2)
InParty("Viconia")
OR(16)
AreaCheck("ar0314")
AreaCheck("ar0406")
AreaCheck("ar0509")
AreaCheck("ar0511")
AreaCheck("ar0513")
AreaCheck("ar0704")
AreaCheck("ar0709")
AreaCheck("ar1105")
AreaCheck("ar1602")
AreaCheck("ar2010")
AreaCheck("ar2203")
AreaCheck("ar4267")
AreaCheck("dd3302")
AreaCheck("ra5104")
AreaCheck("BG3200")
AreaCheck("ys0396")
Global("SanVicInnLov","LOCALS",0)
Delay(8)
THEN
RESPONSE #100
SetGlobal("SanVicInnLov","LOCALS",11)
RealSetGlobalTimer("SanVicinnT","LOCALS",3600)
END

IF
PartyRested()
InParty("Viconia")
OR(4)
Global("SanVicInnLov","LOCALS",2)
Global("SanVicInnLov","LOCALS",4)
Global("SanVicInnLov","LOCALS",12)
Global("SanVicInnLov","LOCALS",14)
THEN
RESPONSE #100
IncrementGlobal("SanVicInnLov","LOCALS",1)
END

IF
OR(2)
Global("SanVicInnLov","LOCALS",6) 
Global("SanVicInnLov","LOCALS",16)
RealGlobalTimerExpired("SanVicinnT","LOCALS")
InParty("Viconia")
OR(26)
AreaCheck("BG0103")
AreaCheck("BG0106")
AreaCheck("BG0120")
AreaCheck("BG0133")
AreaCheck("BG0165")
AreaCheck("BG0807")
AreaCheck("BG0809")
AreaCheck("BG1109")
AreaCheck("BG1113")
AreaCheck("BG2301")
AreaCheck("ar0314")
AreaCheck("ar0406")
AreaCheck("ar0509")
AreaCheck("ar0511")
AreaCheck("ar0513")
AreaCheck("ar0704")
AreaCheck("ar0709")
AreaCheck("ar1105")
AreaCheck("ar1602")
AreaCheck("ar2010")
AreaCheck("ar2203")
AreaCheck("ar4267")
AreaCheck("dd3302")
AreaCheck("ra5104")
AreaCheck("BG3200")
AreaCheck("ys0396")
THEN
RESPONSE #100
IncrementGlobal("SanVicInnLov","LOCALS",1)
END

IF
OR(2)
Global("SanVicInnLov","LOCALS",8)
Global("SanVicInnLov","LOCALS",18)
THEN
RESPONSE #100
IncrementGlobal("SanVicInnLov","LOCALS",1)
AddSpecialAbility("CVViSpi")
END

// Dynaheir Triggers
IF
AreaCheck("BG5100")
NumInParty(6)
Global("SanDyResc","GLOBAL",0)
Global("DynBantTre","LOCALS",0)
!BeenInParty("dynaheir")
THEN
RESPONSE #100
SetGlobal("DynBantTre","LOCALS",1)
RealSetGlobalTimer("DynBantT","GLOBAL",240)
END

IF
RealGlobalTimerExpired("DynBantT","GLOBAL")
Global("SanDyResc","GLOBAL",0)
!InParty("Dynaheir")
!BeenInParty("dynaheir")
AreaCheck("BG5100")
THEN
RESPONSE #100
SetGlobal("SanDyResc","GLOBAL",1)
END

IF
InParty("Dynaheir")
AreaCheck("BG4802")
InParty("CVSandr")
Global("SanDynAftGn","GLOBAL",0)
GlobalLT("DYBant","GLOBAL",2)
THEN
RESPONSE #100
SetGlobal("SanDynAftGn","GLOBAL",1)
END

IF
InParty("Dynaheir")
Global("DYBant","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("DYBant","GLOBAL",1)
RealSetGlobalTimer("DynBantT","GLOBAL",600)
END

IF
InParty("Dynaheir")
Global("DYBant","GLOBAL",1)
RealGlobalTimerExpired("DynBantT","GLOBAL")
THEN
RESPONSE #100
SetGlobal("DYBant","GLOBAL",2)
END

IF
Global("DYBant","GLOBAL",3)
InParty("Dynaheir")
GlobalLT("SanNotCloth","Global",1)
Global("X#DynaJournal","GLOBAL",8)
Delay(33)
THEN
RESPONSE #100
SetGlobal("DYBant","GLOBAL",4)
END

IF
Global("DYBant","GLOBAL",3)
InParty("Dynaheir")
GlobalGT("SanNotCloth","Global",1)
RealGlobalTimerExpired("DynBantT","GLOBAL")
THEN
RESPONSE #100
SetGlobal("DYBant","GLOBAL",4)
END

IF
Global("SanRomPath","GLOBAL",1)
GlobalGT("X#DYLOVETALK","GLOBAL",4)
Global("DYBant","GLOBAL",5)
InParty("Dynaheir")
RealGlobalTimerExpired("DynBantT","GLOBAL")
THEN
RESPONSE #100
SetGlobal("DYBant","GLOBAL",6)
END

IF
Global("DYBant","GLOBAL",5)
InParty("Dynaheir")
RealGlobalTimerExpired("DynBantT","GLOBAL")
OR(2)
Global("SanRomPath","GLOBAL",2)
Global("X#DynaheirRomanceActive","GLOBAL",3)
THEN
RESPONSE #100
SetGlobal("DYBant","GLOBAL",6)
END

IF
Global("DYBant","GLOBAL",7)
RealGlobalTimerExpired("DynBantT","GLOBAL")
!AreaType(DUNGEON)
InParty("Dynaheir")
THEN
RESPONSE #100
SetGlobal("DYBant","GLOBAL",8)
END

IF
GlobalGT("Cowscroll","GLOBAL",8)
InParty("Edwin")
InParty("Dynaheir")
GlobalGT("DYBant","GLOBAL",9)
AreaType(OUTDOOR)
Global("SanDyWyEd","LOCALS",0)
RealGlobalTimerExpired("SanGenWait","GLOBAL")
THEN
RESPONSE #100
SetGlobal("SanDyWyEd","LOCALS",1)
END

IF
Global("DYBant","GLOBAL",11)
RealGlobalTimerExpired("DynBantT","GLOBAL")
!TimeOfDay(NIGHT)
AreaType(OUTDOOR)
!AreaType(DUNGEON)
InParty("Dynaheir")
OR(2)
GlobalGT("WarnEd","GLOBAL",0)
GlobalGT("CmRedWizard3900","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("DYBant","GLOBAL",12)
END

IF
Global("SanRomPath","GLOBAL",1)
Global("DYBant","GLOBAL",13)
InParty("Dynaheir")
RealGlobalTimerExpired("DynBantT","GLOBAL")
OR(2)
GlobalGT("X#DYLOVETALK","GLOBAL",34)
Global("EndofBG1","Global",1)
AreaType(OUTDOOR)
!AreaType(CITY)
THEN
RESPONSE #100
SetGlobal("DYBant","GLOBAL",14)
END

IF
Global("DYBant","GLOBAL",13)
InParty("Dynaheir")
RealGlobalTimerExpired("DynBantT","GLOBAL")
AreaType(OUTDOOR)
!AreaType(CITY)
OR(2)
Global("SanRomPath","GLOBAL",2)
Global("X#DynaheirRomanceActive","GLOBAL",3)
THEN
RESPONSE #100
SetGlobal("DYBant","GLOBAL",34)
END

IF
Global("EndofBG1","Global",1)
InParty("Dynaheir")
RealGlobalTimerExpired("DynBantT","GLOBAL")
!AreaType(DUNGEON)
Global("DYBant","GLOBAL",17)
THEN
RESPONSE #100
SetGlobal("DYBant","GLOBAL",48)
END

IF
InParty("Dynaheir")
RealGlobalTimerExpired("DynBantT","GLOBAL")
!AreaType(DUNGEON)
OR(2)
Global("DYBant","GLOBAL",15)
Global("DYBant","GLOBAL",17)
THEN
RESPONSE #100
IncrementGlobal("DYBant","GLOBAL",1)
END

IF
InParty("Dynaheir")
InParty("Minsc")
Global("SanHealDyna","GLOBAL",6)
GlobalGT("SanBooTlk","GLOBAL",3)
RealGlobalTimerExpired("SanHealDynaB","LOCALS")
!AreaType(DUNGEON)
AreaType(OUTDOOR)
Global("SanMinDyStat","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanMinDyStat","LOCALS",1)
END

IF
InParty("Dynaheir")
Global("DYBant","GLOBAL",19)
Global("SanRomPath","GLOBAL",1)
RealGlobalTimerExpired("DynBantT","GLOBAL")
GlobalGT("Dylovetalk","GLOBAL",50)
OR(16)
AreaCheck("BG4801")
AreaCheck("BG2616")
AreaCheck("BG3351")
AreaCheck("BG3304")
AreaCheck("BG2301")
AreaCheck("BG0105")
AreaCheck("BG0116")
AreaCheck("BG0119")
AreaCheck("BG0706")
AreaCheck("BG4003")
AreaCheck("BG1001")
AreaCheck("bh0115")
AreaCheck("bh0107")
AreaCheck("BG3357")
AreaCheck("BG0114")
AreaCheck("CVRoa2")
THEN
RESPONSE #100
SetGlobal("DYBant","GLOBAL",20)
END

IF
InParty("Dynaheir")
Global("DYBant","GLOBAL",19)
RealGlobalTimerExpired("DynBantT","GLOBAL")
OR(2)
Global("SanRomPath","GLOBAL",2)
Global("X#DynaheirRomanceActive","GLOBAL",3)
OR(16)
AreaCheck("BG4801")
AreaCheck("BG2616")
AreaCheck("BG3351")
AreaCheck("BG3304")
AreaCheck("BG2301")
AreaCheck("BG0105")
AreaCheck("BG0116")
AreaCheck("BG0119")
AreaCheck("BG0706")
AreaCheck("BG4003")
AreaCheck("BG1001")
AreaCheck("bh0115")
AreaCheck("bh0107")
AreaCheck("BG3357")
AreaCheck("BG0114")
AreaCheck("CVRoa2")
THEN
RESPONSE #100
SetGlobal("DYBant","GLOBAL",35)
END

IF
GlobalGT("SanIrThr","LOCALS",3)
!AreaCheck("BG0612")
!AreaCheck("BG0613")
!AreaCheck("BG0614")
!AreaCheck("BG0615")
!AreaCheck("BG0616")
InParty("Dynaheir")
!AreaType(OUTDOOR)
Global("DYBant","GLOBAL",21)
THEN
RESPONSE #100
SetGlobal("DYBant","GLOBAL",22)
END

IF
AreaCheck("BG0123")
InParty("Dynaheir")
Global("SanDyUnTo","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanDyUnTo","LOCALS",1)
END

IF
!StateCheck("Dynaheir",CD_STATE_NOTVALID)
!StateCheck("CVSandr",CD_STATE_NOTVALID)
!See([ENEMY])
CombatCounter(0)
OR(16)
Global("SanDynAftGn","GLOBAL",1)
Global("DYBant","GLOBAL",2)
Global("DYBant","GLOBAL",4)
Global("DYBant","GLOBAL",6)
Global("DYBant","GLOBAL",8)
Global("DYBant","GLOBAL",12)
Global("DYBant","GLOBAL",14)
Global("DYBant","GLOBAL",16)
Global("DYBant","GLOBAL",18)
Global("DYBant","GLOBAL",48)
Global("DYBant","GLOBAL",20)
Global("SanMinDyStat","LOCALS",1)
Global("SanDyWyEd","LOCALS",1)
Global("DYBant","GLOBAL",22)
Global("SanDyUnTo","LOCALS",1)
Global("X#MinscBoo","GLOBAL",4)
THEN
RESPONSE #100
MoveToObject("Dynaheir")
Interact("CVSandr")
END

IF
Global("SanDyUnTo","LOCALS",2)
Global("SanDrag6","LOCALS",0)
!See([ENEMY])
CombatCounter(0)
THEN
RESPONSE #100
IncrementGlobal("SanDrag6","LOCALS",1)
DisplayStringWait(Myself,@440)
AddSpecialAbility("CVDrag6")
END

IF
Global("DYBant","GLOBAL",23)
!See([ENEMY])
CombatCounter(0)
THEN
RESPONSE #100
SetGlobal("DYBant","GLOBAL",24)
IncrementGlobal("SanDrag6","LOCALS",1)
AddSpecialAbility("CVDrag6") 
DisplayStringWait(Myself,@440)
END

IF
Global("SanDrag6","LOCALS",0)
GlobalGT("DYBant","GLOBAL",18)
!InParty("Dynaheir")
!See([ENEMY])
CombatCounter(0)
THEN
RESPONSE #100
IncrementGlobal("SanDrag6","LOCALS",1)
DisplayStringWait(Myself,@440)
AddSpecialAbility("CVDrag6")
END

// First Jaheira Banters

IF
!Global("ENDOFBG1","GLOBAL",2)
InParty("JAHEIRA")
AreaType(OUTDOOR)
Global("JarKhalBant1","GLOBAL",0)
!Global("PCKnowsElmDaughter","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("JarKhalBant1","GLOBAL",1)
END

IF
!Global("ENDOFBG1","GLOBAL",2)
Global("SanFrJah","LOCALS",0)
GlobalGT("Chapter","GLOBAL",3)
InParty("Jaheira")
AreaType(OUTDOOR)
Delay(30)
THEN
RESPONSE #100
SetGlobal("SanFrJah","LOCALS",1)
END

IF
InParty("JAHEIRA")
!StateCheck("JAHEIRA",CD_STATE_NOTVALID)
!StateCheck("CVSandr",CD_STATE_NOTVALID)
!See([ENEMY])
CombatCounter(0)
OR(4)
Global("JarKhalBant1","GLOBAL",1)
Global("SanJahKiv","GLOBAL",1)
Global("SanHealkal","GLOBAL",9)
Global("SanFrJah","LOCALS",1)
THEN
RESPONSE #100
MoveToObject("JAHEIRA")
Interact("CVSandr")
END

IF
InParty("Khalid")
!InParty("JAHEIRA")
!AreaCheck("BG2301")
!AreaCheck("BG2302")
!AreaType(OUTDOOR)
!AreaType(DUNGEON)
Global("JarKhalBant1","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("JarKhalBant1","GLOBAL",6)
END

IF
Global("JarKhalBant1","GLOBAL",2)
InParty("Khalid")
!AreaType(OUTDOOR)
!AreaType(DUNGEON)
THEN
RESPONSE #100
SetGlobal("JarKhalBant1","GLOBAL",3)
END

IF
GlobalGT("SanKivTaz","GLOBAL",0)
OR(2)
GlobalGT("Chapter","GLOBAL",1)
Global("CVAR1100","GLOBAL",1)
InParty("JAHEIRA")
OR(2)
InParty("Kivan")
InParty("P#Kivan")
TimeOfDay(DAY)
!AreaType(FOREST)
Global("SanJahKiv","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanJahKiv","GLOBAL",1)
END

IF
InParty("Khalid")
!StateCheck("Khalid",CD_STATE_NOTVALID)
!StateCheck("CVSandr",CD_STATE_NOTVALID)
!See([ENEMY])
CombatCounter(0)
OR(2)
Global("JarKhalBant1","GLOBAL",3)
Global("JarKhalBant1","GLOBAL",6)
THEN
RESPONSE #100
MoveToObject("Khalid")
Interact("CVSandr")
END

IF
!Global("ENDOFBG1","GLOBAL",2)
Global("SanHealkal","GLOBAL",6)
InParty("Khalid")
AreaType(OUTDOOR)
!AreaType(DUNGEON)
TimeOfDay(NIGHT)
GlobalGT("Chapter","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("SanHealkal","GLOBAL",7)
END

IF
Global("SanHealkal","GLOBAL",8)
InParty("Jaheira")
!TimeOfDay(NIGHT)
!AreaType(OUTDOOR)
THEN
RESPONSE #100
SetGlobal("SanHealkal","GLOBAL",9)
END

IF
InParty("Jaheira")
InParty("Khalid")
Global("SanHealkal","GLOBAL",10)
OR(16)
AreaCheck("BG2400")
AreaCheck("BG2900")
AreaCheck("BG3600")
AreaCheck("BG3100")
AreaCheck("BG2100")
AreaCheck("bg2700")
AreaCheck("BG5800")
AreaCheck("BG3901")
AreaCheck("BG3400")
AreaCheck("BG3500")
AreaCheck("BG2000")
AreaCheck("BG1000")
AreaCheck("BG1500")
AreaCheck("BG4600")
AreaCheck("BG4200")
AreaCheck("BG4400")
THEN
RESPONSE #100
SetGlobal("SanHealkal","GLOBAL",11)
END

IF
Global("SanHealkal","GLOBAL",12)
THEN
RESPONSE #100
SetGlobal("SanHealkal","GLOBAL",13)
END

IF
InParty("Khalid")
!StateCheck("Khalid",CD_STATE_NOTVALID)
!StateCheck("CVSandr",CD_STATE_NOTVALID)
!See([ENEMY])
CombatCounter(0)
OR(3)
Global("SanHealkal","GLOBAL",11)
Global("SanHealkal","GLOBAL",7)
Global("SanHealkal","GLOBAL",13)
THEN
RESPONSE #100
Interact("CVSandr")
END

IF
Global("SanHealkal","GLOBAL",14)
THEN
RESPONSE #100
SetGlobal("SanHealkal","GLOBAL",15)
AddSpecialAbility("cvdra15")
END


// PC Dreams Sandrah's Mother
IF
InParty("CVSandr") 
Global("SanDreamTalk","GLOBAL",4)
RealGlobalTimerExpired("SanDreamTalkTime","GLOBAL") 
Global("PCKnowsElmDaughter","GLOBAL",1)
!StateCheck(Player1,CD_STATE_NOTVALID)
CombatCounter(0)
OR(16)
AreaCheck("BG4801")
AreaCheck("BG2616")
AreaCheck("BG3351")
AreaCheck("BG3304")
AreaCheck("BG2301")
AreaCheck("BG0105")
AreaCheck("BG0116")
AreaCheck("BG0119")
AreaCheck("BG0706")
AreaCheck("BG4003")
AreaCheck("BG1001")
AreaCheck("bh0115")
AreaCheck("bh0107")
AreaCheck("BG3357")
AreaCheck("BG0114")
AreaCheck("CVRoa2")
THEN
RESPONSE #100
SetGlobal("SanDreamTalk","GLOBAL",5)
END

IF
Global("Mothdream1","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("Mothdream1","GLOBAL",2)
ClearAllActions()
StartCutSceneMode()
StartCutScene("Sanmoth")
END

IF
Global("Mothdream1","GLOBAL",3)
THEN
RESPONSE #100
SetGlobal("Mothdream1","GLOBAL",4)
ClearAllActions()
StartCutSceneMode()                                           
StartCutScene("SanmothR")
END

IF
Global("Mothdream1","GLOBAL",5)
THEN
RESPONSE #100
MoveToObject(Player1)
SetGlobal("Mothdream1","GLOBAL",6)
Interact("CVSandr")
END

// Second Dream
IF
InParty("CVSandr")
Global("SanDreamTalk","GLOBAL",6)
RealGlobalTimerExpired("SanDreamTalkTime","GLOBAL")
PartyRested()
!See([ENEMY])
CombatCounter(0)
THEN
RESPONSE #100
SetGlobal("SanDreamTalk","GLOBAL",7)
END

IF
Global("SanDreamTalk","GLOBAL",7)
Global("Mothdream2","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("Mothdream2","GLOBAL",1)
END

IF
Global("Mothdream2","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("Mothdream2","GLOBAL",2)
ClearAllActions()
StartCutSceneMode()
StartCutScene("Sanmot2")
END

IF
Global("Mothdream2","GLOBAL",3)
THEN
RESPONSE #100
SetGlobal("Mothdream2","GLOBAL",4)
ClearAllActions()
StartCutSceneMode()
StartCutScene("Sanmot2R")
END

IF
Global("Mothdream2","GLOBAL",5)
THEN
RESPONSE #100
SetGlobal("Mothdream2","GLOBAL",6)
SetGlobal("SanDreamTalk","GLOBAL",8)
RealSetGlobalTimer("SanDreamTalkTime","GLOBAL",SANROM_TIMER)
END

// Castle Owner
IF
PartyHasItem("CVOLDSH")
Global("SanCasOwn","GLOBAL",0)
OR(3)
AreaCheck("BH1000")
AreaCheck("BG0500")
AreaCheck("dsc010")
THEN
RESPONSE #100
SetGlobal("SanCasOwn","GLOBAL",1)
END

IF
PartyHasItem("CVOLDSH")
Global("SanCasOwn","GLOBAL",2)
RealGlobalTimerExpired("SanCasOwnT","LOCALS")
OR(3)
AreaCheck("BH1000")
AreaCheck("BG0500")
AreaCheck("dsc010")
THEN
RESPONSE #100
SetGlobal("SanCasOwn","GLOBAL",3)
END

IF
PartyHasItem("CVOLDSH")
Global("SanCasOwn","GLOBAL",4)
RealGlobalTimerExpired("SanCasOwnT","LOCALS")
OR(3)
AreaCheck("BH1000")
AreaCheck("BG0500")
AreaCheck("dsc010")
THEN
RESPONSE #100
SetGlobal("SanCasOwn","GLOBAL",5)
END

IF
!StateCheck(Player1,CD_STATE_NOTVALID)
CombatCounter(0)
OR(3)
AreaCheck("bh1000")
AreaCheck("BG0500")
AreaCheck("dsc010")
OR(3)
Global("SanCasOwn","GLOBAL",1)
Global("SanCasOwn","GLOBAL",3)
Global("SanCasOwn","GLOBAL",5)
THEN
RESPONSE #100
MoveToObject(Player1)
Interact("CVSandr")
END

// Baldur Town

IF
AreaCheck("BG0700")
!See([ENEMY])
Global("SaBalCarn","GLOBAL",0)
OR(5)
See("Container9")
See("Container6")
See("Container10")
See("Container4")
See("Container7")
THEN
RESPONSE #100
SetGlobal("SaBalCarn","GLOBAL",1)
END

IF
AreaCheck("BG0300")
Global("SanSecrt","BG0300",1)
See("Container3")
THEN
RESPONSE #100
SetGlobal("SanSecrt","BG0300",2)
END

IF
Global("SanSpiWeb1","LOCALS",0)
TimeOfDay(DAY)
OR(4)
AreaCheck("BG0100")
AreaCheck("BG0200")
AreaCheck("BG1100")
AreaCheck("BG1200")
Delay(15)
THEN
RESPONSE #100
SetGlobal("SanSpiWeb1","LOCALS",1)
END

IF
OR(2)
AreaCheck("BG0600")
AreaCheck("BG0800")
PartyHasItem("misc64")
Global("SanTelscp","LOCALS",0)
Delay(12)
THEN
RESPONSE #100
SetGlobal("SanTelscp","LOCALS",1)
END

IF
OR(2)
Global("SanTelscp","LOCALS",2)
Global("SanTelscp","LOCALS",0)
!AreaCheck("BG0600")
TimeOfDay(NIGHT)
AreaType(OUTDOOR)
PartyHasItem("misc64")
Delay(12)
THEN
RESPONSE #100
SetGlobal("SanTelscp","LOCALS",3)
END

IF
AreaCheck("BG0613")
!See([ENEMY])
Global("SanIrThr","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanIrThr","LOCALS",1)
END

IF
Global("SanIrThr","LOCALS",2)
AreaCheck("BG0615")
Dead("ZHALIMAR")
Dead("aasim")
Dead("Alai")
Dead("Naaman")
THEN
RESPONSE #100
SetGlobal("SanIrThr","LOCALS",3)
END

IF
Global("SearchIronThrone","GLOBAL",1)
PartyHasItem("Scrl3a")
Global("SanIrThr","LOCALS",4)
Delay(15)
THEN
RESPONSE #100
SetGlobal("SanIrThr","LOCALS",5)
END

IF
Global("TamokoMove","GLOBAL",2)
!AreaCheck("BG0607")
!AreaCheck("BG1100")
Global("SanTamoko","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanTamoko","LOCALS",1)
END

IF
OR(2)
Global("SanTamoko","LOCALS",2)
Global("SanTamoko","LOCALS",4)
OR(2)
Global("TamokoMove","GLOBAL",4)
Dead("Tamoko")
THEN
RESPONSE #100
SetGlobal("SanTamoko","LOCALS",5)
END

IF
OR(2)
Dead("bdkorlas")
Global("BD_KORLASZ_SURRENDER","GLOBAL",1)
AreaCheck("bd0120")
Global("SanEndBG1Plot","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanEndBG1Plot","GLOBAL",1)
END

IF
PartyHasItemIdentified("CVNARVBO")
Global("SanMysRise","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanMysRise","GLOBAL",1)
END

IF
Global("SanMysRise","GLOBAL",1)
GlobalGT("SanEndBG1Plot","GLOBAL",4)
THEN
RESPONSE #100
SetGlobal("SanMysRise","GLOBAL",2)
END

IF
AreaCheck("BG0705")
See("B!Jolun")
!InParty("B!Gavin")
Global("SanJolInto","GLOBAL",0)
Global("SanJolSolo","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanJolSolo","LOCALS",1)
Interact("CVSandr")
END

IF
Global("SanBG1ShauPrev","GLOBAL",0)
AreaCheck("BG1200")
OR(3)
See("NTwelt")
See("Door8101")
See("Door1201")
THEN
RESPONSE #100
SetGlobal("SanBG1ShauPrev","GLOBAL",1)
END


// Jet'laya  + DSOTSC
IF
InParty("Xan")
InParty("Jetlaya")
Global("San2Elves","GLOBAL",2)
AreaType(CITY)
THEN
RESPONSE #100
SetGlobal("San2Elves","GLOBAL",3)
END

IF
InParty("Jetlaya")
Global("SanJetAml","LOCALS",0)
PartyHasItem("DSAmul02")
THEN
RESPONSE #100
SetGlobal("SanJetAml","LOCALS",1)
END

IF 
See("Jetlaya")
!See([ENEMY])
CombatCounter(0)
!StateCheck("Jetlaya",CD_STATE_NOTVALID)
!StateCheck("CVSandr",CD_STATE_NOTVALID)
OR(2)
Global("San2Elves","GLOBAL",3)
Global("SanJetAml","LOCALS",1)
THEN
RESPONSE #100
Interact("CVSandr")
END

IF
AreaCheck("ar10pb")
Global("Copersan","ar10pb",1)
See("CVCoper")
THEN
RESPONSE #100
SetGlobal("Copersan","ar10pb",2)
END

IF
AreaCheck("dsc014")
Global("SanWoodSt","LOCALS",0)
OR(2)
Dead("Vamflf01")
Dead("Vampif01")
THEN
RESPONSE #100
SetGlobal("SanWoodSt","LOCALS",1)
END

IF
AreaCheck("dsc017")
Global("SanWoodSt","LOCALS",0)
OR(2)
Dead("Vamflf01")
Dead("Vampif01")
THEN
RESPONSE #100
SetGlobal("SanWoodSt","LOCALS",5)
END

IF
Global("SanWoodSt","LOCALS",3)
RealGlobalTimerExpired("SanWoodStRep","LOCALS")
THEN
RESPONSE #100
SetGlobal("SanWoodSt","LOCALS",2)
END

IF
Dead("Clairis")
Dead("Lordvamp")
Global("SanKiLordVa","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanKiLordVa","LOCALS",1)
END

IF
AreaCheck("dsc021")
!Dead("DsDuegM1")
Global("SanDSOTSCUW","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanDSOTSCUW","GLOBAL",1)
END

IF
Global("SanDSOTSCUW","GLOBAL",2)
OR(3)
AreaCheck("dsc023")
AreaCheck("dsc026")
AreaCheck("dsc030")
OR(5)
PartyHasItem("DWPlat01")
PartyHasItem("DWChan01")
PartyHasItem("DsRobe05")
PartyHasItem("MiscDrw2")
PartyHasItem("DWChan02")
THEN
RESPONSE #100
SetGlobal("SanDSOTSCUW","GLOBAL",3)
END

IF
Global("SanDSOTSCUW","GLOBAL",4)
Dead("DSDrow01")
THEN
RESPONSE #100
SetGlobal("SanDSOTSCUW","GLOBAL",5)
END

IF
InParty("Viconia")
Global("SanDSOTSCUW","GLOBAL",6)
THEN
RESPONSE #100
Interact("CVSandr")
END

IF
GlobalLT("SanDSOTSCUW","GLOBAL",10)
AreaCheck("Dsc034")
Dead("Grunk")
Dead("Jabbress")
Dead("DSShar")
THEN
RESPONSE #100
SetGlobal("SanDSOTSCUW","GLOBAL",10)
END

IF
GlobalGT("SanGithVS","GLOBAL",4)
PartyHasItem("DSHamm01")
Global("SanDSOTSCUW","GLOBAL",11)
THEN
RESPONSE #100 
RealSetGlobalTimer("SanGithVSDelT","LOCALS",40)
SetGlobal("SanDSOTSCUW","GLOBAL",12)
END

IF
Global("SanDSOTSCUW","GLOBAL",12)
RealGlobalTimerExpired("SanGithVSDelT","LOCALS")
THEN
RESPONSE #100
SetGlobal("SanDSOTSCUW","GLOBAL",13)
END

IF
InParty("CVSandr")
PartyHasItem("Sw2h15")
Global("SanGithVS","GLOBAL",0)
Global("SanGithVSDel","LOCALS",0)
!See([ENEMY])
CombatCounter(0)
OR(2)
AreaCheck("BG4300")
AreaCheck("BG1900")
THEN
RESPONSE #100
SetGlobal("SanGithVSDel","LOCALS",1)
RealSetGlobalTimer("SanGithVSDelT","LOCALS",45)
END

IF
Global("SanGithVSDel","LOCALS",1)
RealGlobalTimerExpired("SanGithVSDelT","LOCALS")
THEN
RESPONSE #100
SetGlobal("SanGithVSDel","LOCALS",2)
StartCutSceneMode()
CreateCreatureObjectOffset("sangith",Myself,[125.125])
CreateCreatureObjectOffset("ppgithgi",Myself,[-125.-125])
CreateCreatureObjectOffset("ppgithg1",Myself,[225.-125])
CreateCreatureObjectOffset("ppgithma",Myself,[-225.225])
CreateCreatureObjectOffset("ppgithwa",Myself,[-325.-225])
CreateCreatureObjectOffset("ppgithm1",Myself,[425.-325])
CreateCreatureObjectOffset("ppgithw1",Myself,[425.-125])
EndCutSceneMode()
SetGlobal("SanGithVS","GLOBAL",1)
END

IF
!PartyHasItem("Sw2h15")
Dead("DSShar")
Global("HasGithS","LOCALS",0)
OR(2)
AreaCheck("dsc035")
AreaCheck("dsc033")
THEN
RESPONSE #100
SetGlobal("HasGithS","LOCALS",1)
GiveItemCreate("Sw2h15",Player3,0,0,0)
END

//Shar-Teel
IF
Global("x#sharmatch","GLOBAL",1)
Global("SanSharInt","GLOBAL",0)
InParty("SHARTEEL")
THEN
RESPONSE #100
SetGlobal("SanSharInt","GLOBAL",1)
SetGlobal("X#SharPissed","GLOBAL",12)
RealSetGlobalTimer("SanSharIntT","GLOBAL",SANROM_TIMER)
END

IF
Global("SanShartDuel","GLOBAL",1)
InParty("SHARTEEL")
HPPercentGT("SHARTEEL",95)
THEN
RESPONSE #100
SetGlobal("SanShartDuel","GLOBAL",2)
END

IF
Global("SanShartDuel","GLOBAL",0)
InParty("Sharteel")
HPPercentGT("SHARTEEL",95)
THEN
RESPONSE #100
SetGlobal("SanShartDuel","GLOBAL",4)
END

IF
GlobalGT("SanShartDuel","GLOBAL",2)
Global("x#sharmatch","GLOBAL",0)
Global("SanSharInt","GLOBAL",0)
InParty("SHARTEEL")
THEN
RESPONSE #100
SetGlobal("SanSharInt","GLOBAL",1)
RealSetGlobalTimer("SanSharIntT","GLOBAL",SANROM_TIMER)
END

IF
RealGlobalTimerExpired("SanSharIntT","GLOBAL")
InParty("SHARTEEL")
OR(2)
Global("SanSharInt","GLOBAL",1)
Global("SanSharInt","GLOBAL",3)
THEN
RESPONSE #100
IncrementGlobal("SanSharInt","GLOBAL",1)
END

IF
RealGlobalTimerExpired("SanSharIntT","GLOBAL")
Global("SanRomPath","GLOBAL",1)
Global("SanSharInt","GLOBAL",5)
InParty("SHARTEEL")
THEN
RESPONSE #100
SetGlobal("SanSharInt","GLOBAL",6)
END

IF
RealGlobalTimerExpired("SanSharIntT","GLOBAL")
Global("SanRomPath","GLOBAL",2)
Global("SanSharInt","GLOBAL",5)
InParty("SHARTEEL")
THEN
RESPONSE #100
SetGlobal("SanSharInt","GLOBAL",7)
END

IF
GlobalGT("SanSharInt","GLOBAL",6)
InParty("SHARTEEL")
Global("X#SHARINTEREST","GLOBAL",3)
Global("SanSharReDo","GLOBAL",0)
Global("SanRomPath","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("SanSharReDo","GLOBAL",1)
END

IF
RealGlobalTimerExpired("SanSharIntT","GLOBAL")
Global("SanSharInt","GLOBAL",8)
Dead("Greywolf")
InParty("SHARTEEL")
THEN
RESPONSE #100
SetGlobal("SanSharInt","GLOBAL",9)
END

IF
Global("SanSharInt","GLOBAL",14)
InParty("SHARTEEL")
GlobalGT("SanSplash","GLOBAL",7)
OR(17)
AreaCheck("BG4200")
AreaCheck("BG4600")
AreaCheck("BG5200")
AreaCheck("BG0400")
AreaCheck("BG0900")
AreaCheck("BG2400")
AreaCheck("BG3600")
AreaCheck("BG3100")
AreaCheck("BG2100")
AreaCheck("bg2700")
AreaCheck("BG5800")
AreaCheck("ar3594")
AreaCheck("ar3588")
AreaCheck("ar3500")
AreaCheck("BG2000")
AreaCheck("BG1000")
AreaCheck("BG1500")
THEN
RESPONSE #100
SetGlobal("SanSharInt","GLOBAL",15)
END

IF
GlobalGT("SanSharInt","GLOBAL",9)
!Global("X#SHARINTEREST","GLOBAL",3)
GlobalGT("X#SHARINTERESTTALK","GLOBAL",10)
InParty("SHARTEEL")
Global("SharRead1","GLOBAL",0)
OR(8)
AreaCheck("BG0706")
AreaCheck("BG0120")
AreaCheck("BG0121")
AreaCheck("BG0106")
AreaCheck("BG0107")
AreaCheck("BG0104")
AreaCheck("BG2303")
AreaCheck("BG2302")
THEN
RESPONSE #100
SetGlobal("SharRead1","GLOBAL",1)
END

IF
!Global("ENDOFBG1","GLOBAL",2)
Global("SharRead1","GLOBAL",2)
InParty("SHARTEEL")
GlobalGT("Chapter","GLOBAL",4)
TimeOfDay(NIGHT)
AreaType(OUTDOOR)
!AreaType(CITY)
THEN
RESPONSE #100
SetGlobal("SharRead1","GLOBAL",3)
END

IF
Global("SanSharInt","GLOBAL",10)
RealGlobalTimerExpired("SanSharIntT","GLOBAL")
!Global("X#SHARINTEREST","GLOBAL",3)
GlobalGT("X#SHARINTERESTTALK","GLOBAL",10)
InParty("SHARTEEL")
THEN
RESPONSE #100
SetGlobal("SanSharInt","GLOBAL",11)
END

IF
Global("SanSharInt","GLOBAL",11)
AreaType(OUTDOOR)
!AreaType(CITY)
!StateCheck("Sharteel",CD_STATE_NOTVALID)
!See([ENEMY])
CombatCounter(0)
THEN
RESPONSE #100
MoveToObject("SHARTEEL")
Interact("CVSandr")
END

IF
Global("SanSharInt","GLOBAL",10)
RealGlobalTimerExpired("SanSharIntT","GLOBAL")
Global("SanRompath","Global",2)
AreaType(OUTDOOR)
!AreaType(CITY)
!StateCheck("Sharteel",CD_STATE_NOTVALID)
!See([ENEMY])
CombatCounter(0)
THEN
RESPONSE #100
SetGlobal("SanSharInt","GLOBAL",13)
END

IF
Global("SanSharInt","GLOBAL",12)
RealGlobalTimerExpired("SanSharIntT","GLOBAL")
!Global("X#SHARINTEREST","GLOBAL",3)
InParty("SHARTEEL")
TimeOfDay(DUSK)
AreaType(OUTDOOR)
THEN
RESPONSE #100
SetGlobal("SanSharInt","GLOBAL",13)
END

IF
Global("X#SharInterest","GLOBAL",2)
InParty("SHARTEEL")
Global("DimDay","GLOBAL",0)
OR(16)
AreaCheck("BG4801")
AreaCheck("BG2616")
AreaCheck("BG3351")
AreaCheck("BG3304")
AreaCheck("BG2301")
AreaCheck("BG0105")
AreaCheck("BG0116")
AreaCheck("BG0119")
AreaCheck("BG0706")
AreaCheck("BG4003")
AreaCheck("BG1001")
AreaCheck("bh0115")
AreaCheck("bh0107")
AreaCheck("BG3357")
AreaCheck("BG0114")
AreaCheck("CVRoa2")
THEN
RESPONSE #100
SetGlobal("DimDay","GLOBAL",1)
END

IF
GlobalGT("X#SHARINTERESTTALK","GLOBAL",37)
Global("X#SharInterest","GLOBAL",2)
InParty("SHARTEEL")
Global("SanSharInt","GLOBAL",16)
!AreaType(DUNGEON)
TimeOfDay(DAY)
THEN
RESPONSE #100
SetGlobal("SanSharInt","GLOBAL",17)
END

IF
Global("SanSharInt","GLOBAL",18)
THEN
RESPONSE #100
SetGlobal("SanSharInt","GLOBAL",19)
RealSetGlobalTimer("SanSharPreg","GLOBAL",30000)
END

IF
Global("SanSharInt","GLOBAL",19)
OR(2)
PartyHasItem("Misc78")
RealGlobalTimerExpired("SanSharPreg","GLOBAL")
InParty("SHARTEEL")
!AreaCheck("BG0112")
THEN
RESPONSE #100
SetGlobal("SanSharInt","GLOBAL",20)
END

IF
Global("SanSharInt","GLOBAL",21)
RealGlobalTimerExpired("SanSharIntT","GLOBAL")
InParty("SHARTEEL")
THEN
RESPONSE #100
SetGlobal("SanSharInt","GLOBAL",22)
END

IF
Global("SanSharInt","GLOBAL",26)
GlobalGT("EndofBG1","GLOBAL",1)
RealGlobalTimerExpired("SanSharPreg","GLOBAL")
!InParty("Sharteel")
THEN
RESPONSE #100
SetGlobal("SanSharInt","GLOBAL",27)
END

IF
Global("SanSharInt","GLOBAL",27)
!See([ENEMY])
CombatCounter(0)
!AreaType(DUNGEON)
!Global("Chapter","Global",17)
InParty("CVSandr")
!StateCheck("CVSandr",CD_STATE_NOTVALID)
THEN
RESPONSE #100
SetGlobal("SanSharInt","GLOBAL",28)
CreateCreatureObjectOffset("NarQMes",Myself,[100.100])
END

IF
Global("DimDay","GLOBAL",1)
THEN
RESPONSE #100
PlaySound("DimDay")
MoveToObject("SHARTEEL")
Interact("CVSandr")
END

IF
Global("DimDay","GLOBAL",3)
InParty("Sharteel")
See("Sharteel")
!TimeOfDay(NIGHT)
AreaType(OUTDOOR)
THEN
RESPONSE #100
SetGlobal("DimDay","GLOBAL",4)
END

IF
InParty("SHARTEEL")
AreaCheck("BG0800")
Global("SanSharTown","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanSharTown","GLOBAL",1)
RealSetGlobalTimer("SanTownDel","LOCALS",240)
END

IF
AreaCheck("BG0800")
Global("SanSharTown","GLOBAL",1)
RealGlobalTimerExpired("SanTownDel","LOCALS")
THEN
RESPONSE #100
SetGlobal("SanSharTown","GLOBAL",2)
END

IF
InParty("Sharteel")
Global("SanSharInt","GLOBAL",23)
Global("EndofBG1","GLOBAL",1)
AreaType(OUTDOOR)
AreaType(CITY)
!AreaCheck("BG0800")
Delay(33)
THEN
RESPONSE #100
SetGlobal("SanSharInt","GLOBAL",24)
END

IF
Global("SanSharInt","GLOBAL",23)
InParty("Sharteel")
GlobalLT("Chapter","GLOBAL",6)
Global("SanHarToWD","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanHarToWD","LOCALS",1)
RealSetGlobalTimer("SanSharPregWD","LOCALS",30000)
END

IF
Global("SanSharInt","GLOBAL",23)
InParty("Sharteel")
GlobalLT("EndofBG1","GLOBAL",1)
RealGlobalTimerExpired("SanSharPregWD","LOCALS")
GlobalGT("Chapter","GLOBAL",4)
AreaType(OUTDOOR)
AreaType(CITY)
!AreaCheck("BG0800")
Delay(33)
THEN
RESPONSE #100
SetGlobal("SanSharInt","GLOBAL",24)
END

IF
InParty("Sharteel")
AreaType(OUTDOOR)
Global("Chapter","GLOBAL",7)
Global("SanSharGoM","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanSharGoM","LOCALS",1)
END

IF
InParty("Sharteel")
AreaCheck("BG0125")
Dead("Galdor")
!See([ENEMY])
CombatCounter(0)
Global("SanSharAngD","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanSharAngD","LOCALS",1)
END

IF
See("Sharteel")
!StateCheck("SHARTEEL",CD_STATE_NOTVALID)
!See([ENEMY])
CombatCounter(0)
OR(20)
Global("SanSharInt","GLOBAL",2)
Global("SanSharInt","GLOBAL",4)
Global("SanSharInt","GLOBAL",6)
Global("SanSharInt","GLOBAL",7)
Global("SanSharInt","GLOBAL",9)
Global("SanSharInt","GLOBAL",13)
Global("SanSharInt","GLOBAL",15)
Global("SanSharInt","GLOBAL",17)
Global("SharRead1","GLOBAL",1)
Global("SansharDzt","GLOBAL",1)
Global("SanShartDuel","GLOBAL",2)
Global("SanShartDuel","GLOBAL",4)
Global("SanSharReDo","GLOBAL",1)
Global("SanSharTown","GLOBAL",2)
Global("SanSharInt","GLOBAL",22)
Global("SharRead1","GLOBAL",3)
Global("DimDay","GLOBAL",4)
Global("SanSharGoM","LOCALS",1)
Global("SanSharInt","GLOBAL",24)
Global("SanSharAngD","LOCALS",1)
THEN
RESPONSE #100
MoveToObject("SHARTEEL")
Interact("CVSandr")
END

IF
Global("SanSharInt","GLOBAL",25)
THEN
RESPONSE #100
SetGlobal("SanSharInt","GLOBAL",26)
AddSpecialAbility("CVDrag7")
END

// Kivan Banter
IF
InParty("Kivan")
See("Kivan")
Global("Kivshil","GLOBAL",0)
!AreaCheck("BG3200")
!AreaCheck("BG3202")
!AreaCheck("bg2800")
THEN
RESPONSE #100
SetGlobal("Kivshil","GLOBAL",1)
END

IF
InParty("Kivan")
See("Kivan")
RealGlobalTimerExpired("KivshilT","GLOBAL")
!TimeOfDay(DAY)
!AreaType(CITY)
AreaType(OUTDOOR)
Global("Kivshil","GLOBAL",2)
!StateCheck("CVSandr",CD_STATE_NOTVALID)
!StateCheck("Kivan",CD_STATE_NOTVALID)
THEN
RESPONSE #100
SetGlobal("Kivshil","GLOBAL",3)
END

IF
Global("Kivshil","GLOBAL",4)
InParty("Kivan")
AreaType(CITY)
TimeOfDay(DAY)
RealGlobalTimerExpired("KivshilT","GLOBAL")
!StateCheck("CVSandr",CD_STATE_NOTVALID)
!StateCheck("Kivan",CD_STATE_NOTVALID)
THEN
RESPONSE #100
SetGlobal("Kivshil","GLOBAL",5)
END

IF
Global("Kivshil","GLOBAL",6)
RealGlobalTimerExpired("KivshilT","GLOBAL")
Global("Kivkill","GLOBAL",0)
AreaType(Forest)
InParty("Kivan")
!StateCheck("CVSandr",CD_STATE_NOTVALID)
!StateCheck("Kivan",CD_STATE_NOTVALID)
Delay(6)
THEN
RESPONSE #100
ClearAllActions()
StartCutSceneMode()
Wait(2)
CreateCreatureObjectOffset("sahobwiz",Myself,[100.100])
CreateCreatureObjectOffset("hobwiz01",Myself,[-100.-100])
CreateCreatureObjectOffset("hobwiz02",Myself,[100.-100])
CreateCreatureObjectOffset("sakiwiz",Myself,[-100.100])
CreateCreatureObjectOffset("hobelite",Myself,[0.0])
Wait(2)
EndCutSceneMode()
SetGlobal("Kivkill","GLOBAL",1)
END

IF
!Global("ENDOFBG1","GLOBAL",2)
Dead("sakiwiz")
Global("Kivkill","GLOBAL",1)
InParty("Kivan")
!StateCheck("CVSandr",CD_STATE_NOTVALID)
!StateCheck("Kivan",CD_STATE_NOTVALID)
THEN
RESPONSE #100
SetGlobal("Kivkill","GLOBAL",2)
END

IF
Global("Kivkill","GLOBAL",3)
InParty("Kivan")
RealGlobalTimerExpired("KivshilT","GLOBAL")
OR(2)
AreaType(OUTDOOR)
AreaType(DUNGEON)
!StateCheck("CVSandr",CD_STATE_NOTVALID)
!StateCheck("Kivan",CD_STATE_NOTVALID)
THEN
RESPONSE #100
SetGlobal("Kivkill","GLOBAL",4)
END

IF
InParty("Kivan")
GlobalGT("Kivshil","GLOBAL",5)
TimeOfDay(NIGHT)
RealGlobalTimerExpired("KivshilT","GLOBAL")
Global("KivNakD","GLOBAL",0)
OR(11)
AreaCheck("BG3600")
AreaCheck("BG3100")
AreaCheck("BG2100")
AreaCheck("bg2700")
AreaCheck("BG5800")
AreaCheck("ar3594")
AreaCheck("ar3588")
AreaCheck("ar3500")
AreaCheck("BG2000")
AreaCheck("BG1000")
AreaCheck("BG1500")
THEN
RESPONSE #100
SetGlobal("KivNakD","GLOBAL",1)
END

IF
Global("JoinedBandits","GLOBAL",0)
AreaCheck("BG1900")
Global("SanBadDir","GLOBAL",0)
GlobalLT("Chapter","Global",5)
!Dead("Tazok")
THEN
RESPONSE #100
SetGlobal("SanBadDir","GLOBAL",1)
END

IF
Global("SanBadDir","GLOBAL",1)
!StateCheck("CVSandr",CD_STATE_NOTVALID)
!See([ENEMY])
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogNoSet("CVSandr")
END

IF
!Global("ENDOFBG1","GLOBAL",2)
Dead("Tazok")
GlobalLT("Chapter","GLOBAL",6)
InParty("Kivan")
!AreaCheck("BG1900")
AreaType(OUTDOOR)
!TimeOfDay(DAY)
Global("SanKivTaz","GLOBAL",0)
!StateCheck("CVSandr",CD_STATE_NOTVALID)
!StateCheck("Kivan",CD_STATE_NOTVALID)
THEN
RESPONSE #100
SetGlobal("SanKivTaz","GLOBAL",1)
END

IF
Global("SanKivTaz","GLOBAL",2) 
RealGlobalTimerExpired("KivshilT","GLOBAL")
!TimeOfDay(DAY)
AreaType(OUTDOOR)
InParty("Kivan")
!StateCheck("CVSandr",CD_STATE_NOTVALID)
!StateCheck("Kivan",CD_STATE_NOTVALID)
THEN
RESPONSE #100
SetGlobal("SanKivTaz","GLOBAL",3)
END

IF
AreaCheck("BG0900")
PartyHasItem("P#Bow")
InParty("Kivan")
Global("SanKivBow","GLOBAL",0)
!StateCheck("CVSandr",CD_STATE_NOTVALID)
!StateCheck("Kivan",CD_STATE_NOTVALID)
THEN
RESPONSE #100
SetGlobal("SanKivBow","GLOBAL",1)
END

IF
Global("SanKivTaz","GLOBAL",4) 
RealGlobalTimerExpired("KivshilT","GLOBAL")
InParty("Kivan")
!TimeOfDay(NIGHT)
AreaType(CITY)
!StateCheck("CVSandr",CD_STATE_NOTVALID)
!StateCheck("Kivan",CD_STATE_NOTVALID)
THEN
RESPONSE #100
SetGlobal("SanKivTaz","GLOBAL",5)
END

IF
GlobalGT("SanKivTaz","GLOBAL",3)
Global("SanKivBtlAh","GLOBAL",0)
InParty("Kivan")
OR(11)
AreaCheck("BG0616")
AreaCheck("BG0601")
AreaCheck("BG2615")
AreaCheck("BG2613")
AreaCheck("BG5100")
AreaCheck("BG0123")
AreaCheck("BG0137")
AreaCheck("ar9001")
AreaCheck("ar9002")
AreaCheck("BG0500")
AreaCheck("BG1500")
THEN
RESPONSE #100
SetGlobal("SanKivBtlAh","GLOBAL",1)
END

IF
GlobalGT("SanKivTaz","GLOBAL",3)
InParty("Kivan")
AreaType(FOREST)
TimeOfDay(DAY)
RealGlobalTimerExpired("KivshilT","GLOBAL")
Global("SanKevStay","LOCALS",0)
!StateCheck("CVSandr",CD_STATE_NOTVALID)
!StateCheck("Kivan",CD_STATE_NOTVALID)
THEN
RESPONSE #100
SetGlobal("SanKevStay","LOCALS",1)
END

IF
AreaCheck("BG0600")
InParty("Kivan")
OR(2 )
See("rabbit")
See("Rabbit01")
Global("SankivRab","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SankivRab","LOCALS",1)
END

IF
Global("SankivRab","LOCALS",2)
OR(2)
AreaCheck("ar30pb")
AreaType(FOREST)
InParty("Kivan")
THEN
RESPONSE #100
SetGlobal("SankivRab","LOCALS",3)
RealSetGlobalTimer("KivshilT","GLOBAL",1200)
END

IF
Global("SankivRab","LOCALS",4)
RealGlobalTimerExpired("KivshilT","GLOBAL")
InParty("Kivan")
!TimeOfDay(NIGHT)
!AreaType(CITY)
!AreaType(DUNGEON)
AreaType(OUTDOOR)
!StateCheck("CVSandr",CD_STATE_NOTVALID)
!StateCheck("Kivan",CD_STATE_NOTVALID)
THEN
RESPONSE #100
SetGlobal("SankivRab","LOCALS",5)
END

IF
Global("SanTamoko","LOCALS",2)
InParty("Kivan")
AreaCheck("BG0702")
THEN
RESPONSE #100
SetGlobal("SanTamoko","LOCALS",3)
END

IF
CombatCounter(0)
!See([ENEMY])
!StateCheck("CVSandr",CD_STATE_NOTVALID)
!StateCheck("Kivan",CD_STATE_NOTVALID)
OR(20)
Global("Kivshil","GLOBAL",1)
Global("Kivshil","GLOBAL",3)
Global("Kivshil","GLOBAL",5)
Global("Kivkill","GLOBAL",2)
Global("KivNakD","GLOBAL",1)
Global("SanKivTaz","GLOBAL",1)
Global("SanKivTaz","GLOBAL",3)
Global("SanKivTaz","GLOBAL",5)
Global("SanKivTaz","GLOBAL",7)
Global("Kivkill","GLOBAL",4)
Global("CentKiv","GLOBAL",1)
Global("SanKivBow","GLOBAL",1)
Global("SanKivBtlAh","GLOBAL",1)
Global("SankivRab","LOCALS",1)
Global("SankivRab","LOCALS",3)
Global("SankivRab","LOCALS",5)
Global("SanKevStay","LOCALS",1)
Global("SanTamoko","LOCALS",3)
Global("SanKivBG1End","GLOBAL",1)
Global("San2ElvesK","GLOBAL",1)
THEN
RESPONSE #100
MoveToObject("KIVAN")
Interact("CVSandr")
END

IF
!Global("ENDOFBG1","GLOBAL",2)
Global("SanKivBow","GLOBAL",2)
THEN
RESPONSE #100
SetGlobal("SanKivBow","GLOBAL",3)
AddSpecialAbility("CVDrag4")
END

//Drizzt

IF
Global("SanDrizzt","GLOBAL",2)
InParty("F_Drizzt")
!AreaType(DUNGEON)
CombatCounter(0)
!See([ENEMY])
THEN
RESPONSE #100
SetGlobal("SanDrizzt","GLOBAL",3)
END

IF
InParty("F_Drizzt")
RealGlobalTimerExpired("SanDrizztInterv","GLOBAL")
OR(3)
Global("SanDrizzt","GLOBAL",4)
Global("SanDrizzt","GLOBAL",9)
Global("SanDrizzt","GLOBAL",11)
THEN
RESPONSE #100
IncrementGlobal("SanDrizzt","GLOBAL",1)
END

IF
AreaCheck("F_9898")
InParty("F_Drizzt")
Dead("F_Robed")
Global("SanDrByeBG1","LOCALS",0)
Delay(12)
THEN
RESPONSE #100
SetGlobal("SanDrByeBG1","LOCALS",1)
END

IF
InParty("F_Drizzt")
CombatCounter(0)
!See([ENEMY])
!StateCheck("F_Drizzt",CD_STATE_NOTVALID)
OR(8)
Global("SanDrizzt","GLOBAL",3)
Global("SanDrizzt","GLOBAL",5)
Global("SanDrizzt","GLOBAL",7)
Global("SanDrizzt","GLOBAL",10)
Global("SanHealDriz","GLOBAL",3)
Global("SanDrizzt","GLOBAL",12)
Global("SanDriDrowAmb","GLOBAL",1)
Global("SanDrByeBG1","LOCALS",1)
THEN
RESPONSE #100
MoveToObject("F_Drizzt")
Interact("CVSandr")
END

IF
Global("SanDrizzt","GLOBAL",8)
THEN
RESPONSE #100
SetGlobal("SanDrizzt","GLOBAL",9)
AddSpecialAbility("CVDrag9")
END

IF
PartyHasItem("F_Irenot")
Global("SanIreHint","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanIreHint","LOCALS",1)
END

// Fishermen and Umberlee
IF
Global("SanUmberbowl","Global",1)
InParty("CVSandr")
PartyHasItem("Misc53")
Global("Umbowl","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("Umbowl","GLOBAL",1)
END


// Northern Tales Episodes

IF 
Global("SanFDGGoth","GLOBAL",1)
!StateCheck("CVSandr",CD_STATE_NOTVALID)
!See([ENEMY])
CombatCounter(0)
AreaCheck("ar10pb")
THEN
RESPONSE #100
StartDialogNoSet("CVSandr")
END

IF
AreaCheck("ar01PB")
See("FALSEDOOR")
Global("SanNTFalseWarn","LOCALS",0)
OR(2)
!PartyHasItem("ntkeypb2")
!PartyHasItem("ntkeypb3")
THEN
RESPONSE #100
SetGlobal("SanNTFalseWarn","LOCALS",1)
END

IF
PartyHasItem("NTSwd05")
!Dead("NTGGHOTA")
!Dead("NTGGHOT1")
Global("SanGothSwFound","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanGothSwFound","GLOBAL",1)
END

IF
PartyHasItem("NTSwd05")
Dead("NTGGHOTA")
Dead("NTGGHOT1")
Global("SanGothSwFound","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanGothSwFound","GLOBAL",3)
END

//Bjornin revisited
IF
Global("HelpBjornin","GLOBAL",2)
Global("SanHadBjor","GLOBAL",0)
InParty("CVSandr")
AreaCheck("BG3304")
THEN
RESPONSE #100
SetGlobal("SanHadBjor","GLOBAL",1)
END

IF
Global("SanHadBjor","GLOBAL",1)
AreaCheck("BG3304")
!StateCheck("CVSandr",CD_STATE_NOTVALID)
!See([ENEMY])
THEN
RESPONSE #100
Interact("CVSandr")
END

IF
Global("SanHadBjor","GLOBAL",5)
InParty("CVSandr")
AreaCheck("BG3304")
Global("HelpBjornin","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("SanHadBjor","GLOBAL",6)
END

IF
Global("SanHadBjor","GLOBAL",6)
AreaCheck("BG3304")
!StateCheck("CVSandr",CD_STATE_NOTVALID)
!See([ENEMY])
THEN
RESPONSE #100
Interact("CVSandr")
END

IF
Global("OgresKilled","GLOBAL",4)
AreaCheck("BG4200")
Global("SanHadBjor","GLOBAL",2)
THEN
RESPONSE #100
SetGlobal("SanHadBjor","GLOBAL",3)
END

IF
Global("SanHadBjor","GLOBAL",3)
AreaCheck("BG4200")
!StateCheck("CVSandr",CD_STATE_NOTVALID)
!See([ENEMY])
CombatCounter(0)
THEN
RESPONSE #100
SetGlobal("SanHadBjor","GLOBAL",4)
END

//Journey to Waterdeep
IF
PartyHasItem("SanMap")
AreaCheck("bg2300")
InParty("CVSandr")
Global("RoadFound","GLOBAL",0)
THEN
RESPONSE #100
DisplayStringHead(Myself,@95)
SmallWait(8)
SetGlobal("RoadFound","GLOBAL",1)
END

IF
Global("RoadFound","GLOBAL",3)
THEN
RESPONSE #100
Explore()
ClearAllActions()
SmallWait(2)
HideGUI()
StartCutScene("CVRoad")
END

IF
Global("RoadFound","GLOBAL",4)
THEN
RESPONSE #100
ClearAllActions()
SmallWait(2)
StartCutSceneMode()
SmallWait(4)
DisplayStringWait(Myself,@96)
SmallWait(10)
FadeToColor([30.0],0)
Wait(2)
ActionOverride(Player1,LeaveAreaLUA("CVROA1","",[859.2231],12))
ActionOverride(Player2,LeaveAreaLUA("CVROA1","",[859.2231],10))
ActionOverride(Player3,LeaveAreaLUA("CVROA1","",[859.2231],11))
ActionOverride(Player4,LeaveAreaLUA("CVROA1","",[859.2231],12))
ActionOverride(Player5,LeaveAreaLUA("CVROA1","",[859.2231],11))
ActionOverride(Player6,LeaveAreaLUA("CVROA1","",[859.2231],10))
FadeFromColor([30.0],0)
EndCutSceneMode()
SetGlobal("RoadFound","GLOBAL",5)
RevealAreaOnMap("CVROA1")
END

IF
Global("SanVisitedWD","GLOBAL",1)
Global("SanEagl","LOCALS",0)
AreaCheck("CVElm1")
THEN
RESPONSE #100
SetGlobal("SanEagl","LOCALS",1)
CreateCreatureObject("Saneagl",Player1,0,0,0)
END

IF
See("Saneagl")
Global("SanEagl","LOCALS",1)
THEN
RESPONSE #100
SetGlobal("SanEagl","LOCALS",2)
MoveToObject(Player1)
Interact("CVSandr")
END

IF
AreaCheck("CVROA2")
Global("WDIntrotalk","LOCALS",0)
OR(3)
See("Cat01")
See("Dog01")
See("Dog02")
THEN
RESPONSE #100
SetGlobal("WDIntrotalk","LOCALS",1)
SetGlobal("Infomap","CVRoa2",1)
END

IF
Global("SanWDTemplWi","GLOBAL",4)
THEN
RESPONSE #100
ClearAllActions()
SetInterrupt(FALSE)
StartCutsceneMode()
DestroyAllEquipment()
ActionOverride(Player1,DropInventory())
Wait(5)
ActionOverride(Player2,EscapeArea())
ActionOverride(Player3,EscapeArea())
ActionOverride(Player4,EscapeArea())
ActionOverride(Player5,EscapeArea())
ActionOverride(Player6,EscapeArea())
ActionOverride("haiass",EscapeArea())
ActionOverride("Pellig",EscapeArea())
ActionOverride(Player2,LeaveParty())
ActionOverride(Player3,LeaveParty())
ActionOverride(Player4,LeaveParty())
ActionOverride(Player5,LeaveParty())
ActionOverride(Player6,LeaveParty())
ActionOverride(Player1,LeaveAreaLUA("BG3100","",[1203.1141],2))
EndCutsceneMode()
ActionOverride(Player1,DisplayString(Myself,@435))
SetGlobal("SanWDTemplWi","GLOBAL",31)
END

// Fight Khattark
IF
Global("Katcut","GLOBAL",12)
THEN
RESPONSE #100
SetGlobal("Katcut","GLOBAL",13)
LeaveParty()
SetGlobal("SandrahJoined","GLOBAL",2)
ActionOverride("CVSandr",EscapeAreaMove("BG3402",270,497,0))
END

IF
Global("Katcut","GLOBAL",7)
!AreaCheck("CVWDRE")
THEN
RESPONSE #100
SetGlobal("Katcut","GLOBAL",8)
END

// FINCH BLOOMWHIFFLER
IF  
Global("SUSanKnowsFinch","GLOBAL",0)
InParty("CVSandr")
OR(2)
InParty("Sufinch")
Global("SURedSheafMeet","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("SUSanKnowsFinch","GLOBAL",1)
END

IF
InParty("Sufinch")
Global("FinchBant1","LOCALS",0)
!AreaType(CITY)
AreaType(OUTDOOR)
Global("SanRomPath","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("FinchBant1","LOCALS",1)
END

IF
InParty("Sufinch")
Global("FinchBant1","LOCALS",0)
!AreaType(CITY)
AreaType(OUTDOOR)
Global("SanRomPath","GLOBAL",2)
THEN
RESPONSE #100
SetGlobal("FinchBant1","LOCALS",2)
END

IF
InParty("Sufinch")
Global("FinchBant1","LOCALS",3)
GlobalGT("Chapter","GLOBAL",2)
TimeofDay(DUSK)
Global("PCKnowsElmDaughter","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("FinchBant1","LOCALS",4)
END

IF
Global("SanFab2","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("SanFab2","GLOBAL",2)
MoveToObject(Player1)
StartDialogNoSet("CVSandr")
END

IF
Global("HelpShaella","GLOBAL",1)
InParty("Sufinch")
!AreaCheck("BG0800")
Global("SanSuUnKnBo","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanSuUnKnBo","GLOBAL",1)
END

IF
InParty("Sufinch")
!StateCheck("Sufinch",CD_STATE_NOTVALID)
!StateCheck("CVSandr",CD_STATE_NOTVALID)
!See([ENEMY])
OR(6)
Global("FinchBant1","LOCALS",4)
Global("FinchBant1","LOCALS",2)
Global("FinchBant1","LOCALS",1)
Global("SuFiPel","GLOBAL",1)
Global("SanSuUnKnBo","GLOBAL",1)
Global("SanSUFiCLREV","GLOBAL",1)
THEN
RESPONSE #100
MoveToObject("Sufinch")
Interact("CVSandr")
END

IF
Global("HelpShaella","GLOBAL",1)
!InParty("Sufinch")
!AreaCheck("BG0800")
Global("SanSuUnKnBo","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanSuUnKnBo","GLOBAL",1)
END

IF
Global("SanSuUnKnBo","GLOBAL",1)
!InParty("Sufinch")
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogNoSet("CVSandr")
END

//Bookhunt

IF
RealGlobalTimerExpired("BloomwT","GLOBAL")
AreaType(OUTDOOR)
!AreaType(CITY)
!AreaCheck("CVROA1")
!AreaCheck("CVDre1")
PartyHasItem("SuSaBo")
Global("SanSuBH","GLOBAL",0)
!See([ENEMY])
CombatCounter(0)
OR(3)
Global("Bloomw","GLOBAL",9)
Global("Bloomw","GLOBAL",6)
Global("Bloomw","GLOBAL",5)
THEN
RESPONSE #100
SetGlobal("SanSuBH","GLOBAL",1)
StartCutSceneMode()
CreateCreatureObjectOffset("SanSuWi",Myself,[100.100])
CreateCreatureObjectOffset("SanSuW2",Myself,[-100.-100])
CreateCreatureObjectOffset("SanSuW3",Myself,[100.-100])
CreateCreatureObjectOffset("SanSuWL",Myself,[50.50])
EndCutSceneMode()
END

IF
Global("SanSuBH","GLOBAL",3)
Dead("SanSuWL")
Dead("SanSuWi")
Dead("SanSuW2")
Dead("SanSuW3")
THEN
RESPONSE #100
SetGlobal("SanSuBH","GLOBAL",4)
END

IF
Global("SanSuBH","GLOBAL",5)
RealGlobalTimerExpired("BloomwT","GLOBAL")
AreaType(OUTDOOR)
PartyHasItem("SuSaBo")
THEN
RESPONSE #100
SetGlobal("SanSuBH","GLOBAL",6)
StartCutSceneMode()
CreateCreatureObjectOffset("SanSuWi",Myself,[100.100])                 
CreateCreatureObjectOffset("SanSuW2",Myself,[-100.-100])
CreateCreatureObjectOffset("SanSuW3",Myself,[100.-100])
CreateCreatureObjectOffset("SanSuWP",Myself,[50.50])
EndCutSceneMode()
END

IF
Global("SanSuBH","GLOBAL",7)
THEN
RESPONSE #100
StartCutSceneMode()
ActionOverride("SanSuWp",ChangeEnemyAlly(Myself,ENEMY))
ActionOverride("SanSuWi",ChangeEnemyAlly(Myself,ENEMY))
ActionOverride("SanSuW2",ChangeEnemyAlly(Myself,ENEMY))
ActionOverride("SanSuW3",ChangeEnemyAlly(Myself,ENEMY))
ActionOverride("SanSuWp",Attack(Player1))
ActionOverride("SanSuWi",Attack(Player2))
ActionOverride("SanSuW2",Attack(Player3))
ActionOverride("SanSuW3",Attack(Player4))
EndCutSceneMode()
SetGlobal("SanSuBH","GLOBAL",8)
END

IF
Global("SanSuBH","GLOBAL",8)
Dead("SanSuWp")
!See([ENEMY])
CombatCounter(0)
THEN
RESPONSE #100
SetGlobal("SanSuBH","GLOBAL",9)
END

IF
Global("SanSuBH","GLOBAL",10)
RealGlobalTimerExpired("BloomwT","GLOBAL")
!AreaType(OUTDOOR)
!AreaType(DUNGEON)
THEN
RESPONSE #100
SetGlobal("SanSuBH","GLOBAL",11)
END

IF
Global("SanSuBH","GLOBAL",14)
OR(2)
Global("FurlIntre","GLOBAL",1)
Global("FurlIntr","GLOBAL",1)
RealGlobalTimerExpired("BloomwT","GLOBAL")
!AreaCheck("bg0900")
THEN
RESPONSE #100
SetGlobal("SanSuBH","GLOBAL",15)
END

IF
Global("SanSuBH","GLOBAL",12)
RealGlobalTimerExpired("BloomwT","GLOBAL")
AreaType(OUTDOOR)
THEN
RESPONSE #100
SetGlobal("SanSuBH","GLOBAL",13)
END

IF
Global("SanSuBH","GLOBAL",13)
InParty("Sufinch")
!See([ENEMY])
CombatCounter(0)
THEN
RESPONSE #100
MoveToObject("Sufinch")
Interact("CVSandr")
END

IF
Global("SanSuBH","GLOBAL",13)
!InParty("Sufinch")
!See([ENEMY])
CombatCounter(0)
THEN
RESPONSE #100
MoveToObject(Player1)
Interact("CVSandr")
END

IF
GlobalGT("SanSuBH","GLOBAL",18)
Global("HasDra23","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("HasDra23","LOCALS",1)
AddSpecialAbility("CVDra23")
END

IF
RealGlobalTimerExpired("BloomwT","GLOBAL")
Global("SanSuBH","GLOBAL",17)
THEN
RESPONSE #100
SetGlobal("SanSuBH","GLOBAL",18)
RealSetGlobalTimer("BloomwT","GLOBAL",1000)
END

IF
Global("SanSuBH","GLOBAL",29)
OR(2)
PartyHasItem("CVPirbag")
PartyHasItem("CVFarkpa")
THEN
RESPONSE #100
SetGlobal("SanSuBH","GLOBAL",30)
END

IF
Dead("capholg")
Global("SanSuBH","GLOBAL",31)
THEN
RESPONSE #100
SetGlobal("SanSuBH","GLOBAL",32)
END

IF
Global("J#PirateFight","GLOBAL",2)
Dead("J#pirat1")
Global("CVPirFight","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("J#PirateFight","GLOBAL",3)
SetGlobal("CVPirFight","LOCALS",1)
END

IF
Global("J#PirateFight","GLOBAL",3)
Global("CVPirFight","LOCALS",1)
THEN
RESPONSE #100
SetGlobal("CVPirFight","LOCALS",2)
END

IF
GlobalGT("SanSuBH","GLOBAL",18)
RealGlobalTimerExpired("BloomwT","GLOBAL")
AreaType(OUTDOOR)
PartyHasItem("SuSaBo")
!AreaCheck("BG1000")
!AreaCheck("BG1008")
Global("SanSuBHAtt3","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanSuBHAtt3","LOCALS",1)
StartCutSceneMode()
CreateCreatureObjectOffset("SanSuWi",Myself,[100.100])                 
CreateCreatureObjectOffset("SanSuW2",Myself,[-100.-100])
CreateCreatureObjectOffset("SanSuW3",Myself,[100.-100])
CreateCreatureObjectOffset("SanSuWP",Myself,[50.50])
CreateCreatureObjectOffset("Orc02",Myself,[100.150])
CreateCreatureObjectOffset("Orc03",Myself,[-150.-100])
EndCutSceneMode()
END

IF
PartyHasItem("CVSHPRTE")
Global("SanLHpir","GLOBAL",0)
GlobalLT("J#PirateFight","GLOBAL",1)
OR(2)
AreaCheck("J#Ligh")
AreaCheck("J#Lig2")
THEN
RESPONSE #100
SetGlobal("SanLHpir","GLOBAL",1)
END

IF
Global("SanSuBHAtt3","LOCALS",1)
THEN
RESPONSE #100
StartCutSceneMode()
ActionOverride("SanSuWp",ChangeEnemyAlly(Myself,ENEMY))
ActionOverride("SanSuWi",ChangeEnemyAlly(Myself,ENEMY))
ActionOverride("SanSuW2",ChangeEnemyAlly(Myself,ENEMY))
ActionOverride("SanSuW3",ChangeEnemyAlly(Myself,ENEMY))
ActionOverride("SanSuWp",Attack(Player1))
ActionOverride("SanSuWi",Attack(Player2))
ActionOverride("SanSuW2",Attack(Player3))
ActionOverride("SanSuW3",Attack(Player4))
EndCutSceneMode()
SetGlobal("SanSuBHAtt3","LOCALS",2)
END

IF
Global("SanSuBH","GLOBAL",26)
AreaCheck("CVPIR2")
!StateCheck(Player1,CD_STATE_NOTVALID)
!See([ENEMY])
CombatCounter(0)
THEN
RESPONSE #100
MoveToObject(Player1)
Interact("CVSandr")
END

IF
Global("SanSuBH","GLOBAL",28)
AreaCheck("CVPIR3")
!StateCheck(Player1,CD_STATE_NOTVALID)
!See([ENEMY])
CombatCounter(0)
THEN
RESPONSE #100
ReallyForceSpellPointRES("spin689",[340.465])
Interact("CVSandr")
END

IF
Global("Homesail","GLOBAL",1)
THEN
RESPONSE #100
ClearAllActions()
StartCutsceneMode()
DisplayStringWait(Myself,@339)
ApplySpellRES("CVSLEEP",Player2)
ApplySpellRES("CVSLEEP",Player3)
ApplySpellRES("CVSLEEP",Player4)
ApplySpellRES("CVSLEEP",Player5)
ApplySpellRES("CVSLEEP",Player6)
ApplySpellRES("CVSLEEP",Player1)
EndCutsceneMode()
SetGlobal("Homesail","GLOBAL",2)
END

IF
Global("Homesail","GLOBAL",2)
!StateCheck(Player1,CD_STATE_NOTVALID)
!StateCheck(Player2,CD_STATE_NOTVALID)
!StateCheck(Player3,CD_STATE_NOTVALID)
!StateCheck(Player4,CD_STATE_NOTVALID)
!StateCheck(Player5,CD_STATE_NOTVALID)
!StateCheck(Player6,CD_STATE_NOTVALID)
Delay(4)
THEN
RESPONSE #100
Interact("CVSandr")
END


IF
Global("Homesail","GLOBAL",3)
THEN
RESPONSE #100
ClearAllActions()
SetInterrupt(FALSE)
TextScreen("ZomHom")
Wait(2)
SetInterrupt(TRUE)
SetGlobal("Homesail","GLOBAL",4)
END

IF
Global("Homesail","GLOBAL",4)
THEN
RESPONSE #100
StartCutsceneMode()
ActionOverride(Player1,LeaveAreaLUA("BG3100","",[1203.1141],2))
ActionOverride(Player2,LeaveAreaLUA("BG3100","",[1305.1625],2))
ActionOverride(Player3,LeaveAreaLUA("BG3100","",[983.1620],2))
ActionOverride(Player4,LeaveAreaLUA("BG3100","",[849.1483],2))
ActionOverride(Player5,LeaveAreaLUA("BG3100","",[1202.1867],2))
ActionOverride(Player6,LeaveAreaLUA("BG3100","",[1336.1403],2))
ActionOverride("haiass",LeaveAreaLUA("BG3100","",[797.1452],2))
ActionOverride("Pellig",LeaveAreaLUA("BG3100","",[1031.1918],2))
EndCutsceneMode()
SetGlobal("Homesail","GLOBAL",5)
END

IF
Global("Homesail","GLOBAL",5)
THEN
RESPONSE #100
ApplySpellRES("CVSLEEP",Player2)
ApplySpellRES("BGSLEEP",Player3)
ApplySpellRES("CVSLEEP",Player4)
ApplySpellRES("BGSLEEP",Player5)
ApplySpellRES("CVSLEEP",Player6)
ApplySpellRES("BGSLEEP",Player1)
SetGlobal("Homesail","GLOBAL",6)
END

IF
Global("Homesail","GLOBAL",6)
!StateCheck(Player1,CD_STATE_NOTVALID)
!StateCheck(Player2,CD_STATE_NOTVALID)
!StateCheck(Player3,CD_STATE_NOTVALID)
!StateCheck(Player4,CD_STATE_NOTVALID)
!StateCheck(Player5,CD_STATE_NOTVALID)
!StateCheck(Player6,CD_STATE_NOTVALID)
Delay(4)
THEN
RESPONSE #100
Interact("CVSandr")
END

IF
Global("Homesail","GLOBAL",8)
THEN
RESPONSE #100
SetGlobal("Homesail","GLOBAL",9)
RealSetGlobalTimer("BloomwT","GLOBAL",3620)
END

IF
Global("Homesail","GLOBAL",9)
RealGlobalTimerExpired("BloomwT","GLOBAL")
AreaType(OUTDOOR)
!AreaCheck("BG5100")
CombatCounter(0)
THEN
RESPONSE #100
SetGlobal("Homesail","GLOBAL",10)
CreateCreatureObjectOffset("CVMonte",Myself,[100.100])
END

IF
Global("Homesail","GLOBAL",10)
Global("SanGavMontPapers","GLOBAL",1)
CombatCounter(0)
!See([ENEMY])
!StateCheck(Player1,CD_STATE_NOTVALID)
!StateCheck(Player2,CD_STATE_NOTVALID)
!StateCheck(Player3,CD_STATE_NOTVALID)
!StateCheck(Player4,CD_STATE_NOTVALID)
!StateCheck(Player5,CD_STATE_NOTVALID)
!StateCheck(Player6,CD_STATE_NOTVALID)
Delay(4)
THEN
RESPONSE #100
SetGlobal("Homesail","GLOBAL",11)
Interact("CVSandr")
END

// Knight's Shield  + Valiant

IF
PartyHasItemIdentified("AGSHLD01")
Global("KNSHLDF","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("KNSHLDF","GLOBAL",1)
END

IF
Global("SanKahrk","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("SanKahrk","GLOBAL",2)
RealSetGlobalTimer("SanKarkhAp","LOCALS",10)
END

IF
Global("SanKahrk","GLOBAL",2)
RealGlobalTimerExpired("SanKarkhAp","LOCALS")
!InMyArea("Carsa")
!InMyArea("Kahrk")
!Dead("Carsa")
!Dead("Kahrk")
THEN
RESPONSE #100
SetGlobal("SanKahrk","GLOBAL",3)
DisplayStringWait(Myself,@484)
END

IF
Global("SanKahrk","GLOBAL",3)
Delay(6)
THEN
RESPONSE #100
SetGlobal("SanKahrk","GLOBAL",4)
CreateCreature("KAHRK",[3476.852],0)
END

IF
OR(2)
PartyHasItemIdentified("SW2VAL")
PartyHasItemIdentified("Valiant")
Global("ValiantKN","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("ValiantKN","GLOBAL",1)
END

IF
Global("ValiantKN","GLOBAL",2) 
RealGlobalTimerExpired("ValiantTime","GLOBAL")
THEN
RESPONSE #100
SetGlobal("ValiantKN","GLOBAL",3)
END

IF
!StateCheck(Player1,CD_STATE_NOTVALID)
!See([ENEMY])
CombatCounter(0)
InParty("CVSandr")
Global("ValiantKN","GLOBAL",3)
OR(2)
AreaType(OUTDOOR)
AreaType(DUNGEON)
!AreaCheck("CVDre1")
THEN
RESPONSE #100
SetGlobal("ValiantKN","GLOBAL",4)
CreateCreatureObjectDoor("sankah",Player1,0,0,0)
END

IF
Global("ValiantKN","GLOBAL",5)
THEN
RESPONSE #100
SetGlobal("ValiantKN","GLOBAL",6)
CreateCreatureObjectDoor("Ogrema01",Myself,0,0,0)
CreateCreatureObjectDoor("ogrema_a",Myself,0,0,0)
END

IF
Dead("sankah")
Global("ValiantKN","GLOBAL",6)
THEN
RESPONSE #100
SetGlobal("ValiantKN","GLOBAL",7)
END

IF
AreaCheck("BG0112")
OR(2)
See("acqx0004")
See("acq10106")
OR(2)
Global("SanDrgln","LOCALS",0)
Global("SanDrgln","LOCALS",3)
OR(6)
Race(Player1,DWARF)
Race(Player2,DWARF)
Race(Player3,DWARF)
Race(Player4,DWARF)
Race(Player5,DWARF)
Race(Player6,DWARF)
THEN
RESPONSE #100
SetGlobal("SanDrgln","LOCALS",4)
END

IF
AreaCheck("BG0112")
OR(2)
See("acqx0004")
See("acq10106")
Global("SanDrgln","LOCALS",0)
!Race(Player1,DWARF)
!Race(Player2,DWARF)
!Race(Player3,DWARF)
!Race(Player4,DWARF)
!Race(Player5,DWARF)
!Race(Player6,DWARF)
THEN
RESPONSE #100
SetGlobal("SanDrgln","LOCALS",2)
END

IF
Global("ValiantKN","GLOBAL",8)
RealGlobalTimerExpired("ValiantTime","GLOBAL")
OR(2)
AreaType(OUTDOOR)
AreaType(DUNGEON)
!AreaCheck("CVDre1")
THEN
RESPONSE #100
SetGlobal("ValiantKN","GLOBAL",9)
CreateCreatureObjectDoor("Ogrema01",Myself,0,0,0)
CreateCreatureObjectDoor("ogrema_a",Myself,0,0,0)
END

IF
Global("GullyOgre","GLOBAL",4)
Global("KharzD","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("KharzD","LOCALS",1)
SetGlobal("ValiantKN","GLOBAL",15)
END

//Elminster's House

IF
InParty("CVSandr")
AreaCheck("cvsant")
Global("Santlove","GLOBAL",0)
THEN
RESPONSE #100
DayNight(MIDNIGHT)
SetGlobal("Santlove","GLOBAL",1)
StartCutSceneMode()
ActionOverride(Player1,MoveToPoint([769.524]))
SmallWait(5)
MoveToPoint([769.524])
SmallWait(5)
EndCutSceneMode()
PlaySound("mernig")
END

IF
Global("Santlove","GLOBAL",3)
THEN
RESPONSE #100
SetGlobal("Santlove","GLOBAL",4)
StartCutSceneMode()
Wait(2)
ActionOverride(Player1,LeaveAreaLUA("CVsans","",[244.418],12))
ActionOverride("CVSandr",LeaveAreaLUA("CVsans","",[337.303],3))
EndCutSceneMode()
RealSetGlobalTimer("SantloveT","LOCALS",90)
END

IF
Global("SanVisitedWD","GLOBAL",1) 
AreaCheck("CVDRE1")
Global("Mothdream2","GLOBAL",6)
THEN
RESPONSE #100
SetGlobal("Mothdream2","GLOBAL",7)
END

IF
Global("Santlove","GLOBAL",4)
RealGlobalTimerExpired("SantloveT","LOCALS")
THEN
RESPONSE #100
StartDialogNoSet("CVSandr")
END

IF
Global("Santlove","GLOBAL",5)
InParty("CVSandr")
AreaCheck("cvsant")
THEN
RESPONSE #100
DayNight(DAWN_END)
SetGlobal("SanPidPack","GLOBAL",10)
SetGlobal("Santlove","GLOBAL",6)
END

IF
Global("Santlove","GLOBAL",7)
AreaCheck("cvdre2")
InParty("CVSandr")
InParty(Player3)
THEN
RESPONSE #100
MoveToObject(Player1)
Interact("CVSandr")
END

// Charleston Excavation
IF 
Global("TalkedToCharleston","GLOBAL",2)
!PartyHasItem("Misc48")
Global("SanIdolTake","GLOBAL",0)
Global("TORKIONNEEDYOU","GLOBAL",1) 
OR(2)
AreaCheck("BG4100")
AreaCheck("BG4101")
THEN
RESPONSE #100
SetGlobal("SanIdolTake","GLOBAL",1)
END

IF
Global("TORKIONNEEDYOU","GLOBAL",1)
Global("SanIdolTake","GLOBAL",2)
OR(2)
PartyHasItem("sw1h19")
PartyHasItem("SW1HVAM")
THEN
RESPONSE #100
SetGlobal("SanIdolTake","GLOBAL",3)
END

IF
Global("TORKIONNEEDYOU","GLOBAL",2)
Global("SanIdolTake","GLOBAL",4)
AreaCheck("ar9305")
THEN
RESPONSE #100
SetGlobal("SanIdolTake","GLOBAL",5)
END

IF
Global("TheVault","GLOBAL",1)
Global("PriestGondVault","GLOBAL",1)
!AreaCheck("BG0131")
THEN
RESPONSE #100
SetGlobal("PriestGondVault","GLOBAL",2)
MoveToObject(Player1)
StartDialogNoSet("CVSandr")
END

//Firewine Plains Hut
IF
AreaCheck("BG4400")
GlobalGT("SandrahMorningTalk","GLOBAL",7)
Global("SanLoveHut","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanLoveHut","GLOBAL",1)
RealSetGlobalTimer("LoveHutT","LOCALS",150)
END

IF
RealGlobalTimerExpired("LoveHutT","LOCALS")
AreaCheck("BG4400")
Global("SanLoveHut","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("SanLoveHut","GLOBAL",2)
END

IF
Global("SaOgmaIn","GLOBAL",1)
AreaCheck("BG4400")
RealGlobalTimerExpired("SaogmaReal","GLOBAL")
THEN
RESPONSE #100
SetGlobal("SaOgmaIn","GLOBAL",2)
END

IF
AreaCheck("BG4400")
Global("SaOgmaIn","GLOBAL",0)
See("saogma")
THEN
RESPONSE #100
SetGlobal("SaOgmaIn","GLOBAL",1) 
RealSetGlobalTimer("SaogmaReal","GLOBAL",180)
END

IF
Global("SaOgmaIn","GLOBAL",1)
Global("SanOGFo","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanOGFo","LOCALS",1)
ActionOverride("SaOgma",MoveToObjectFollow(Player1))
END

IF
Global("SaOgmaIn","GLOBAL",2)
!StateCheck(Player1,CD_STATE_NOTVALID)
!See([ENEMY])
CombatCounter(0)
THEN
RESPONSE #100
MoveToObject("saogma")
StartDialogNoSet("CVSandr")
END

IF
Dead("saogma")
OR(2)
Global("SaOgmaIn","GLOBAL",0)
Global("SaOgmaIn","GLOBAL",3)
THEN
RESPONSE #100
SetGlobal("SaOgmaIn","GLOBAL",4)
RealSetGlobalTimer("LoveHutT","LOCALS",70)
END

IF
RealGlobalTimerExpired("LoveHutT","LOCALS")
Global("SaOgmaIn","GLOBAL",4)
THEN
RESPONSE #100
SetGlobal("SaOgmaIn","GLOBAL",5)
END

IF
Global("SaOgmaIn","GLOBAL",7)
!See([ENEMY])
CombatCounter(0)
AreaCheck("BG4400")
OR(6)
CheckStatGT(Player1,5,FATIGUE)
CheckStatGT(Player2,5,FATIGUE)
CheckStatGT(Player3,5,FATIGUE)
CheckStatGT(Player4,5,FATIGUE)
CheckStatGT(Player5,5,FATIGUE)
CheckStatGT(Player6,5,FATIGUE)
THEN
RESPONSE #100
SetGlobal("SaOgmaIn","GLOBAL",8)
MoveToObject(Player1)
StartDialogNoSet("CVSandr")
END

IF
Global("SaOgmaIn","GLOBAL",7)
Global("SanVeilDance","GLOBAL",0)
Global("SanVeilDelay","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanVeilDelay","LOCALS",1)
RealSetGlobalTimer("LoveHutT","LOCALS",400)
END

IF
GlobalGT("SaOgmaIn","GLOBAL",6)
RealGlobalTimerExpired("LoveHutT","LOCALS")
Global("SanVeilDance","GLOBAL",0)
OR(4)
AreaCheck("CVWOHA")
AreaCheck("BG4201")
AreaCheck("ar31pb")
AreaCheck("BG2215")
THEN
RESPONSE #100
SetGlobal("SanVeilDance","GLOBAL",1)
END

IF
Global("SanVeilDance","GLOBAL",1)
!Global("SanRompa","Global",2)
!StateCheck(Player1,CD_STATE_NOTVALID)
OR(4)
AreaCheck("CVWOHA")
AreaCheck("BG4201")
AreaCheck("ar31pb")
AreaCheck("BG2215")
THEN
RESPONSE #100
MoveToObject(Player1)
Interact("CVSandr")
END

//Indira
IF
AreaCheck("BG5201")
See("J#INDI")
HPPercentLT("J#INDI",80)
THEN
RESPONSE #100
ForceSpell("J#Indi",CLERIC_HEAL)
END

IF
InParty("J#INDI")
!AreaCheck("BG5201")
Global("HealworkIndi","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("HealworkIndi","GLOBAL",1)
END

IF
InParty("J#INDI")
!TimeOfDay(DAY) 
!AreaType(DUNGEON)
!AreaCheck("BG5201")
RealGlobalTimerExpired("HealIndiT","GLOBAL")
Global("HealworkIndi","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("HealworkIndi","GLOBAL",2)
END

IF
Global("HealworkIndi","GLOBAL",3)
RealGlobalTimerExpired("HealIndiT","GLOBAL")
InParty("J#INDI")
OR(27)
AreaCheck("BG0002")
AreaCheck("BG4802")
AreaCheck("BG2304")
AreaCheck("BG3402")
AreaCheck("ar37pb")
AreaCheck("BG0132")
AreaCheck("BG0131")
AreaCheck("BG3202")
AreaCheck("BG0149")
AreaCheck("BG0609")
AreaCheck("BG4003")
AreaCheck("bh0302")
AreaCheck("BG4801")
AreaCheck("BG2616")
AreaCheck("BG3351")
AreaCheck("BG3304")
AreaCheck("BG2301")
AreaCheck("BG0105")
AreaCheck("BG0116")
AreaCheck("BG0119")
AreaCheck("BG0706")
AreaCheck("BG4003")
AreaCheck("BG1001")
AreaCheck("bh0115")
AreaCheck("bh0107")
AreaCheck("BG3357")
AreaCheck("BG0114")
THEN
RESPONSE #100
SetGlobal("HealworkIndi","GLOBAL",4)
END

IF
Global("HealworkIndi","GLOBAL",6)
RealGlobalTimerExpired("HealIndiT","GLOBAL")
InParty("J#INDI")
THEN
RESPONSE #100
SetGlobal("HealworkIndi","GLOBAL",7)
END

IF
!See([ENEMY])
InParty("J#INDI")
CombatCounter(0)
OR(3)
Global("HealworkIndi","GLOBAL",2)
Global("HealworkIndi","GLOBAL",4)
Global("HealworkIndi","GLOBAL",7)
THEN
RESPONSE #100
MoveToObject("J#INDI")
Interact("CVSandr")
END

IF
Global("HealworkIndi","GLOBAL",5)
THEN
RESPONSE #100
SetGlobal("HealworkIndi","GLOBAL",6)
AddSpecialAbility("cvdra13")
END

// Bandit Camp
IF
PartyHasItem("Scrl2z")
Global("SanSareHi3","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanSareHi3","LOCALS",1)
END

// Shandalar's Island

IF
InParty("CVSandr")
AreaCheck("BG1010")
Global("ShanIsl","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("ShanIsl","GLOBAL",1)
END

// Splashing

IF
InParty("CVSandr")
GlobalGT("SandrahLT","GLOBAL",2)
Global("SanSplash","GLOBAL",0)
!See([ENEMY])
CombatCounter(0)
OR(6)
AreaCheck("BG4200")
AreaCheck("BG4600")
AreaCheck("BG5200")
AreaCheck("BG0400")
AreaCheck("BG0900")
AreaCheck("BG2400")
OR(2)
See("rabbit01")
See("rabbit")
THEN
RESPONSE #100
SetGlobal("SanSplash","GLOBAL",1)
END

IF
Global("SanSplash","GLOBAL",2)
THEN
RESPONSE #100
SetGlobal("SanSplash","GLOBAL",3)
ClearAllActions()
StartCutSceneMode()
FadeToColor([20.0],0)
StorePartyLocations()
SmallWait(2)
ActionOverride(Player1,LeaveAreaLUA("CVSPLA","",[299.542],0))
ActionOverride(Player2,LeaveAreaLUA("CVSPLA","",[400.581],0))
ActionOverride(Player3,LeaveAreaLUA("CVSPLA","",[496.565],0))
ActionOverride(Player4,LeaveAreaLUA("CVSPLA","",[665.452],0))
ActionOverride(Player5,LeaveAreaLUA("CVSPLA","",[742.445],0))
ActionOverride(Player6,LeaveAreaLUA("CVSPLA","",[474.388],0))
FadeFromColor([30.0],0)
StartCutScene("Sanspla")
END

IF
Global("SanSplash","GLOBAL",3)
AreaCheck("CVSPLA")
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogNoSet("CVSandr")
END


IF
Global("SanSplash","GLOBAL",4)
AreaCheck("CVSPLA")
Global("SplaHeal","LOCALS",0)
THEN
RESPONSE #100
ActionOverride(Player1,ForceSpell(Myself,CLERIC_HEAL))
ActionOverride(Player2,ForceSpell(Myself,CLERIC_HEAL))
ActionOverride(Player3,ForceSpell(Myself,CLERIC_HEAL))
ActionOverride(Player4,ForceSpell(Myself,CLERIC_HEAL))
ActionOverride(Player5,ForceSpell(Myself,CLERIC_HEAL))
ActionOverride(Player6,ForceSpell(Myself,CLERIC_HEAL))
SetGlobal("SplaHeal","LOCALS",1)
END

IF
Global("SanSplash","GLOBAL",4)
AreaCheck("CVSPLA")
Global("SplaHeal","LOCALS",1)
THEN
RESPONSE #100
SetGlobal("SanSplash","GLOBAL",5)
ClearAllActions()
SmallWait(2)
SetInterrupt(FALSE)
TextScreen("Beach3")
END


IF
Global("SanSplash","GLOBAL",5)
AreaCheck("CVSPLA")
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogNoSet("CVSandr")
END

IF
Global("SanSplash","GLOBAL",7)
THEN
RESPONSE #100
SetGlobal("SanSplash","GLOBAL",8)
StartCutSceneMode()
SmallWait(2)
FadeToColor([20.0],0)
Wait(3)
RestorePartyLocations()
Wait(2)
FadeFromColor([20.0],0)
EndCutSceneMode()
END


//Edwin Battle
IF
!InParty("Edwin")
AreaCheck("BG4800")
See("Edwin")
Global("WarnEd","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("WarnEd","GLOBAL",1)
END

IF
InParty("Edwin")
AreaCheck("BG4800")
Global("Cowscroll","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("Cowscroll","GLOBAL",1)
GiveItemCreate("U!SCRL02","Edwin",2,0,0)
GiveItemCreate("scrl95","Edwin",25,0,0)
GiveItemCreate("scrx9","Edwin",25,0,0)
END

IF
!Global("ENDOFBG1","GLOBAL",2)
InParty("Edwin")
!AreaCheck("BG4800")
Global("Cowscroll","GLOBAL",1)
!StateCheck("Edwin",CD_STATE_NOTVALID)
!See([ENEMY])
CombatCounter(0)
THEN
RESPONSE #100
MoveToObject(Player1)
Interact("CVSandr")
END

IF
!Global("ENDOFBG1","GLOBAL",2)
HPPercentLT("Edwin",50)
!StateCheck("Edwin",CD_STATE_NOTVALID)
!See([ENEMY])
Global("Cowscroll","GLOBAL",2)
THEN
RESPONSE #100
SetGlobal("Cowscroll","GLOBAL",3)
END

IF
!Global("ENDOFBG1","GLOBAL",2)
InParty("Edwin")
Global("SanEdAnts","GLOBAL",0)
RealGlobalTimerExpired("CowscrollT","GLOBAL")
GlobalGT("Cowscroll","GLOBAL",7)
OR(16)
AreaCheck("BG4801")
AreaCheck("BG2616")
AreaCheck("BG3351")
AreaCheck("BG3304")
AreaCheck("BG2301")
AreaCheck("BG0105")
AreaCheck("BG0116")
AreaCheck("BG0119")
AreaCheck("BG0706")
AreaCheck("BG4003")
AreaCheck("BG1001")
AreaCheck("bh0115")
AreaCheck("bh0107")
AreaCheck("BG3357")
AreaCheck("BG0114")
AreaCheck("CVRoa2")
THEN
RESPONSE #100
SetGlobal("SanEdAnts","GLOBAL",1)
END

IF
!Global("ENDOFBG1","GLOBAL",2)
InParty("Edwin")
GlobalGT("Cowscroll","GLOBAL",8)
HPLT(Player1,80)
!AreaCheck("cvelm3")
Global("SanEdLoveBoy","LOCALS",0)
RealGlobalTimerExpired("CowscrollT","GLOBAL")
!StateCheck("Edwin",CD_STATE_NOTVALID)
THEN
RESPONSE #100
SetGlobal("SanEdLoveBoy","LOCALS",1)
END

IF
!Global("ENDOFBG1","GLOBAL",2)
Global("Cowscroll","GLOBAL",10)
RealGlobalTimerExpired("CowscrollT","GLOBAL")
GlobalGT("SanEdAnts","GLOBAL",1)
InParty("Edwin")
!StateCheck("Edwin",CD_STATE_NOTVALID)
OR(2)
TimeOfDay(NIGHT)
TimeOfDay(DUSK)
OR(2)
AreaType(OUTDOOR)
AreaType(DUNGEON)
THEN
RESPONSE #100
SetGlobal("Cowscroll","GLOBAL",11)
END

IF
!Global("ENDOFBG1","GLOBAL",2)
Global("Cowscroll","GLOBAL",12) 
RealGlobalTimerExpired("CowscrollT","GLOBAL")
InParty("Edwin")
!StateCheck("Edwin",CD_STATE_NOTVALID)
!TimeOfDay(DAY)
AreaType(OUTDOOR)
THEN
RESPONSE #100
SetGlobal("Cowscroll","GLOBAL",13)
END

IF
!Global("ENDOFBG1","GLOBAL",2)
InParty("Edwin")
!StateCheck("Edwin",CD_STATE_NOTVALID)
GlobalGT("Cowscroll","GLOBAL",8)
AreaCheck("CVElm1")
Global("CowElmFear","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("CowElmFear","LOCALS",1)
ApplySpellRES("CVSLEEP","Edwin")
END

IF
!Global("ENDOFBG1","GLOBAL",2)
Global("SanEdLoveBoy","LOCALS",2)
RealGlobalTimerExpired("CowscrollT","GLOBAL")
HPLT("Edwin",85)
!StateCheck("Edwin",CD_STATE_NOTVALID)
THEN
RESPONSE #100
SetGlobal("SanEdLoveBoy","LOCALS",3)
END

IF
GlobalGT("X#EdwinBlushing","GLOBAL",5)
InParty("Edwin")
Global("SanEdBlushTa","GLOBAL",0)
Global("SanEdBlush","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanEdBlushTa","GLOBAL",1)
END

IF
!Global("ENDOFBG1","GLOBAL",2)
Global("Cowscroll","GLOBAL",14)
RealGlobalTimerExpired("CowscrollT","GLOBAL")
InParty("Edwin")
THEN
RESPONSE #100
SetGlobal("Cowscroll","GLOBAL",15)
END

IF
!Global("ENDOFBG1","GLOBAL",2)
Global("Cowscroll","GLOBAL",18)
RealGlobalTimerExpired("CowscrollT","GLOBAL")
InParty("Edwin")
!StateCheck("Edwin",CD_STATE_NOTVALID)
AreaType(CITY)
THEN
RESPONSE #100
SetGlobal("Cowscroll","GLOBAL",19)
END

IF
!Global("ENDOFBG1","GLOBAL",2)
GlobalGT("SanDrizzt","GLOBAL",12)
GlobalGT("Cowscroll","GLOBAL",9)
InParty("Edwin")
!StateCheck("Edwin",CD_STATE_NOTVALID)
RealGlobalTimerExpired("SanGenWait","GLOBAL")
Global("SanEdCyr","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanEdCyr","LOCALS",1)
END

IF
!Global("ENDOFBG1","GLOBAL",2)
AreaCheck("BG0020")
InParty("Edwin")
!StateCheck("Edwin",CD_STATE_NOTVALID)
Dead("NTSarq")
Global("SanEdWizCandlAtt","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanEdWizCandlAtt","LOCALS",1)
END

IF
See("Edwin")
InParty("Edwin")
CombatCounter(0)
!See([ENEMY])
!StateCheck("Edwin",CD_STATE_NOTVALID)
OR(15)
Global("Cowscroll","GLOBAL",3)
Global("Cowscroll","GLOBAL",7)
Global("Cowscroll","GLOBAL",9)
Global("Cowscroll","GLOBAL",11)
Global("Cowscroll","GLOBAL",13)
Global("Cowscroll","GLOBAL",15)
Global("Cowscroll","GLOBAL",19)
Global("SanEdAnts","GLOBAL",1)
Global("SanEdLoveBoy","LOCALS",1)
Global("CowElmFear","LOCALS",1)
Global("SanEdLoveBoy","LOCALS",3)
Global("SanEdBlushTa","GLOBAL",1)
Global("SanEdCyr","LOCALS",1)
Global("SanEdWizCandlAtt","LOCALS",1)
Global("sanredatt","GLOBAL",3)
THEN
RESPONSE #100
MoveToObject("Edwin")
Interact("CVSandr")
END

IF
!Global("ENDOFBG1","GLOBAL",2)
Global("Cowscroll","GLOBAL",6)
InParty("Edwin")
OR(16)
AreaCheck("BG4801")
AreaCheck("BG2616")
AreaCheck("BG3351")
AreaCheck("BG3304")
AreaCheck("BG2301")
AreaCheck("BG0105")
AreaCheck("BG0116")
AreaCheck("BG0119")
AreaCheck("BG0706")
AreaCheck("BG4003")
AreaCheck("BG1001")
AreaCheck("bh0115")
AreaCheck("bh0107")
AreaCheck("BG3357")
AreaCheck("BG0114")
AreaCheck("CVRoa2")
THEN
RESPONSE #100
SetGlobal("Cowscroll","GLOBAL",7)
END

IF
!Global("ENDOFBG1","GLOBAL",2)
InParty("Edwin")
Global("Cowscroll","GLOBAL",8) 
RealGlobalTimerExpired("CowscrollT","GLOBAL")
AreaType(CITY)
THEN
RESPONSE #100
SetGlobal("Cowscroll","GLOBAL",9)
ActionOverride("Edwin",ChangeAIScript("EDWIN_",OVERRIDE))
ReallyForceSpellRES("myscurs2","Edwin")
END

// Taerom

IF
InParty("CVSandr")
See("Taerom")
Global("SanHadTae","GLOBAL",2)
AreaCheck("BG3301")
RealGlobalTimerExpired("SanTaeT","GLOBAL")
THEN
RESPONSE #100
SetGlobal("SanHadTae","GLOBAL",3)
END

// Sandrah Other Child Quest

IF
!Global("ENDOFBG1","GLOBAL",2)
PartyHasItemIdentified("sanwi1")
PartyHasItemIdentified("sanwi2")
Global("SanHasTWOP","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanHasTWOP","GLOBAL",1)
END

IF
!Global("ENDOFBG1","GLOBAL",2)
PartyHasItemIdentified("sanwi1")
PartyHasItemIdentified("sanwi3")
Global("SanHasTWOP","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanHasTWOP","GLOBAL",1)
END

IF
!Global("ENDOFBG1","GLOBAL",2)
PartyHasItemIdentified("sanwi3")
PartyHasItemIdentified("sanwi2")
Global("SanHasTWOP","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanHasTWOP","GLOBAL",1)
END

IF
Global("SanHasTWOP","GLOBAL",1)
!AreaType(DUNGEON)
InParty("CVSandr")
THEN
RESPONSE #100
SetGlobal("SanHasTWOP","GLOBAL",2)
END

IF
PartyHasItemIdentified("SanOrDi")
Global("SanChildH","GLOBAL",0)
OR(3)
PartyHasItemIdentified("sanwi3")
PartyHasItemIdentified("sanwi2")
PartyHasItemIdentified("sanwi1")
THEN
RESPONSE #100
SetGlobal("SanChildH","GLOBAL",1)
END

IF
PartyHasItemIdentified("SanOrDi")
Global("SanChildH","GLOBAL",2)
PartyHasItemIdentified("sanwi3")
PartyHasItemIdentified("sanwi2")
THEN
RESPONSE #100
SetGlobal("SanChildH","GLOBAL",3)
END

IF
PartyHasItemIdentified("SanOrDi")
Global("SanChildH","GLOBAL",2)
PartyHasItemIdentified("sanwi3")
PartyHasItemIdentified("sanwi1")
THEN
RESPONSE #100
SetGlobal("SanChildH","GLOBAL",3)
END

IF
PartyHasItemIdentified("SanOrDi")
Global("SanChildH","GLOBAL",2)
PartyHasItemIdentified("sanwi1")
PartyHasItemIdentified("sanwi2")
THEN
RESPONSE #100
SetGlobal("SanChildH","GLOBAL",3)
END

IF
!StateCheck(Player1,CD_STATE_NOTVALID)
!AreaType(DUNGEON)
InParty("CVSandr")
!See([ENEMY])
CombatCounter(0)
OR(2)
Global("SanChildH","GLOBAL",1)
Global("SanChildH","GLOBAL",3)
THEN
RESPONSE #100
SetGlobal("SanChildH","GLOBAL",4)
END

IF 
PartyHasItemIdentified("sanwi1")
PartyHasItemIdentified("sanwi2")
PartyHasItemIdentified("sanwi3")
Global("Formedcloth","GLOBAL",0)
InParty("CVSandr")
THEN
RESPONSE #100
ClearAllActions()
StartCutSceneMode()
SetGlobal("Formedcloth","GLOBAL",1)
DisplayStringWait(Myself,@214)
TakePartyItem("sanwi1")
Wait(2)
DestroyItem("sanwi1")
Wait(2)
TakePartyItem("sanwi2")
Wait(2)
DestroyItem("sanwi2")
Wait(2)
TakePartyItem("sanwi3")
Wait(2)
DestroyItem("sanwi3")
Wait(2)
GiveItemCreate("sanwif",Player1,0,0,0)
AddexperienceParty(7050)
AddJournalEntry(@213,QUEST)
EraseJournalEntry(@148)
EndCutSceneMode()
END

IF
Global("Formedcloth","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("Formedcloth","GLOBAL",2)
ClearAllActions()
SmallWait(2)
SetInterrupt(FALSE)
TextScreen("SanClo")
END  

IF
Global("Formedcloth","GLOBAL",5)
Global("Clothwait","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("Clothwait","LOCALS",1)
RealSetGlobalTimer("ClothwaitTi","LOCALS",45)
END

IF
Global("Clothwait","LOCALS",1)
RealGlobalTimerExpired("ClothwaitTi","LOCALS")
THEN
RESPONSE #100
SetGlobal("Clothwait","LOCALS",2)
SetGlobal("Formedcloth","GLOBAL",6)
END

IF
!StateCheck(Player1,CD_STATE_NOTVALID)
!AreaType(DUNGEON)
InParty("CVSandr")
!See([ENEMY])
CombatCounter(0)
OR(3)
Global("Formedcloth","GLOBAL",2)
Global("Formedcloth","GLOBAL",6)
Global("Formedcloth","GLOBAL",13)
THEN
RESPONSE #100
MoveToObject(Player1)
StartDialogueNoSet("CVSandr")
END

IF
Global("Formedcloth","GLOBAL",8)
!AreaCheck("CVSANT")
THEN
RESPONSE #100
MoveToObject(Player1)
Interact("CVSandr")
END

IF
Global("Formedcloth","GLOBAL",11)
THEN
RESPONSE #100
SetGlobal("Formedcloth","GLOBAL",12)
RealSetGlobalTimer("ClothwaitTi","LOCALS",1400)
END

IF
Global("Formedcloth","GLOBAL",12)
PartyHasItem("sanbaf")
Global("SanbafD","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanbafD","LOCALS",1)
TakePartyItem("sanbaf")
DestroyItem("sanbaf")
END

IF
Global("Formedcloth","GLOBAL",12)
PartyHasItem("sanbam")
Global("SanbamD","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanbamD","LOCALS",1)
TakePartyItem("sanbam")
DestroyItem("sanbam")
END

IF
Global("Formedcloth","GLOBAL",12)
RealGlobalTimerExpired("ClothwaitTi","LOCALS")
AreaType(OUTDOOR)
THEN
RESPONSE #100
SetGlobal("Formedcloth","GLOBAL",13)
END

IF
Global("Formedcloth","GLOBAL",14) 
RealGlobalTimerExpired("SandrahMorningTalkTime","GLOBAL")
InParty("Imoen2")
THEN
RESPONSE #100
SetGlobal("Formedcloth","GLOBAL",15)
END

IF
Global("Formedcloth","GLOBAL",14)
InParty("Imoen2")
AreaCheck("BG2626")
Dead("Ogrema_D")
CombatCounter(0)
THEN
RESPONSE #100
SetGlobal("Formedcloth","GLOBAL",15)
END

IF
Global("Formedcloth","GLOBAL",19)
THEN
RESPONSE #100
ClearAllActions()
SmallWait(2)
SetInterrupt(FALSE)
TextScreen("SanBhl")
SetGlobal("Formedcloth","GLOBAL",20)
END

IF
Global("Formedcloth","GLOBAL",20)
THEN
RESPONSE #100
EraseJournalEntry(@90)
EraseJournalEntry(@155)
EraseJournalEntry(@200)
EraseJournalEntry(@238)
EraseJournalEntry(@213)
AddJournalEntry(@359,QUEST_DONE)
AddexperienceParty(10500)
SetGlobal("Formedcloth","GLOBAL",21)
RealSetGlobalTimer("SanImoBHScrl","LOCALS",7500)
END

IF
Global("Formedcloth","GLOBAL",21)
AreaCheck("CVROA1")
InParty("Imoen2")
THEN
RESPONSE #100
SetGlobal("Formedcloth","GLOBAL",23)
END

IF
Global("Formedcloth","GLOBAL",21)
InParty("Imoen2")
PartyHasItem("scrl2j")
THEN
RESPONSE #100
SetGlobal("Formedcloth","GLOBAL",22)
RealSetGlobalTimer("SanImoBHScrl","LOCALS",300)
END

IF
RealGlobalTimerExpired("SanImoBHScrl","LOCALS")
OR(2)
Global("Formedcloth","GLOBAL",21)
Global("Formedcloth","GLOBAL",22)
InParty("Imoen2")
THEN
RESPONSE #100
SetGlobal("Formedcloth","GLOBAL",23)
END


//BG1 Dream Reaction

IF
Global("Dream","GLOBAL",2)
Global("SanBG1DreamReact","GLOBAL",0)
AreaType(OUTDOOR)
InParty("CVSandr")
THEN
RESPONSE #100
SetGlobal("SanBG1DreamReact","GLOBAL",1)
END

IF
Global("Dream","GLOBAL",3)
GlobalLT("SanBG1DreamReact","GLOBAL",3)
InParty("CVSandr")
THEN
RESPONSE #100
SetGlobal("SanBG1DreamReact","GLOBAL",3)
END


// First Winski Appearance
IF
!Global("endofbg1","GLOBAL",2)
RealGlobalTimerExpired("WiItemR","GLOBAL")
Global("WinskApp1","GLOBAL",0)
AreaType(OUTDOOR)
InParty("CVSandr")
!StateCheck(Myself,CD_STATE_NOTVALID)
InMyArea(Player1)
!StateCheck(Player1,CD_STATE_NOTVALID)
CombatCounter(0)
!See([ENEMY])
OR(3)
PartyHasItemIdentified("sanwi1")
PartyHasItemIdentified("sanwi2")
PartyHasItemIdentified("sanwi3")
THEN
RESPONSE #100
SetGlobal("WinskApp1","GLOBAL",1)
CreateCreatureObjectDoor("sanwinsk",Player1,0,0,0)
END

IF
Global("WinskApp1","GLOBAL",4)
Delay(6)
THEN
RESPONSE #100
SetGlobal("WinskApp1","GLOBAL",5)
MoveToObject(Player1)
StartDialogueNoSet("CVSandr")
END

IF
Global("WinskApp1","GLOBAL",6)
THEN
RESPONSE #100
SetGlobal("WinskApp1","GLOBAL",7)
MoveToObject(Player1)
StartDialogueNoSet("CVSandr")
END

IF
Global("WinskApp1","GLOBAL",8)
THEN
RESPONSE #100
SetGlobal("WinskApp1","GLOBAL",9)
ClearAllActions()
SmallWait(2)
SetInterrupt(FALSE)
TextScreen("SanTiTr")
AddJournalEntry(@200,QUEST)
END



//Second Winski Appearance
IF
!Global("ENDOFBG1","GLOBAL",2)
Global("SanOrDiId","GLOBAL",4)
RealGlobalTimerExpired("WiItemR","GLOBAL")
GlobalGT("Chapter","GLOBAL",4)
AreaType(OUTDOOR)
!AreaCheck("BG1800")
!AreaCheck("BG6001")
!AreaCheck("BG6000")
THEN
RESPONSE #100
SetGlobal("SanOrDiId","GLOBAL",5)
CreateCreatureObjectDoor("sanwinsk",Player1,0,0,0)
END

IF
Global("SanOrDiId","GLOBAL",6)
THEN
RESPONSE #100
CreateCreatureObjectOffset("mepice01",Player1,[50.100])
CreateCreatureObjectOffset("ICBONE01",Player1,[100.100])
CreateCreatureObjectOffset("X#MEPHT4",Player1,[100.50])
CreateCreatureObjectOffset("GolemF",Player1,[60.60])
CreateCreatureObjectOffset("X#MEPHT2",Player1,[70.100])
CreateCreatureObjectOffset("X#MEPHT1",Player1,[40.-90])
CreateCreatureObjectOffset("ICBONE01",Player1,[-100.100])
SetGlobal("SanOrDiId","GLOBAL",7)
ActionOverride("Sanwinsk",ReallyForceSpell(Myself,DRYAD_TELEPORT))
ActionOverride("Sanwinsk",EscapeArea())
RealSetGlobalTimer("SanWinskAtt2","LOCALS",55)
END

IF
Global("SanOrDiId","GLOBAL",7)
RealGlobalTimerExpired("SanWinskAtt2","LOCALS")
THEN
RESPONSE #100
CreateCreatureObjectOffset("ICBONE01",Player1,[100.100])
CreateCreatureObjectOffset("X#MEPHT4",Player1,[100.-50])
CreateCreatureObjectOffset("GolemF",Player1,[60.60])
SetGlobal("SanOrDiId","GLOBAL",8)
END

// Found Scouts Diary
IF
PartyHasItemIdentified("SanOrDi") 
Global("SanOrDiId","GLOBAL",0)
InParty("CVSandr")
!AreaType(DUNGEON)
!See([ENEMY])
THEN
RESPONSE #100
SetGlobal("SanOrDiId","GLOBAL",1)
END

IF
Global("SanOrDiId","GLOBAL",1)
CombatCounter(0)
THEN
RESPONSE #100
SetGlobal("SanOrDiId","GLOBAL",2)
MoveToObject(Player1)
StartDialogueNoSet("CVSandr")
END

//Repairs
IF
!Global("ENDOFBG1","GLOBAL",2)
AreaCheck("BG2900")
Global("Chapter","GLOBAL",3)
!InMyArea("Teven")
Global("TevenSpawn","GLOBAL",1)
Global("TazokSays","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("TazokSays","GLOBAL",2)
SetGlobal("TevenSpawn","GLOBAL",2)
CreateCreature("Teven",[1469.2254],0)
END

IF
Global("VestibuleBran","GLOBAL",0)
Dead("JC_DEM02")
Global("VestibuleKeld","GLOBAL",2)
THEN
RESPONSE #100
SetGlobal("VestibuleBran","GLOBAL",1)
END

IF
!Global("ENDOFBG1","GLOBAL",2)
AreaCheck("BG2400")
Global("Chapter","GLOBAL",3)
!InMyArea("Raiken")
Global("TazokSays","GLOBAL",1)
Global("RaikenSpawn","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("TazokSays","GLOBAL",2)
SetGlobal("RaikenSpawn","GLOBAL",2)
CreateCreature("Raiken",[4013.594],0)
END

IF
Dead("CMPaul")
!Global("CMSectionEndGame","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("CMSectionEndGame","GLOBAL",1)
END

IF
PartyHasItem("ACQLet03")
GlobalLT("ACQXWOSTOK","GLOBAL",3)
Global("SanAbbat","LOCALS",0)
THEN
RESPONSE #100
SetGlobal("SanAbbat","LOCALS",1)
SetGlobal("ACQLEAFLET","GLOBAL",3)
END

IF
Global("SanAbbat","LOCALS",2)
!PartyHasItem("ACQLet03")
AreaCheck("BG0002")
Global("ACSEARCHLEAFLET","GLOBAL",0)
THEN
RESPONSE #100
GiveItemCreate("ACQLet03",Player1,0,0,0)
SetGlobal("SanAbbat","LOCALS",3)
SetGlobal("ACSEARCHLEAFLET","GLOBAL",1)
END

IF
Global("SanAbbat","LOCALS",2)
PartyHasItem("ACQLet03")
AreaCheck("BG0002")
Global("ACSEARCHLEAFLET","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("SanAbbat","LOCALS",3)
SetGlobal("ACSEARCHLEAFLET","GLOBAL",1)
END

IF  
AreaCheck("bg2700")
Or(2)
Global("ACQ5","GLOBAL",9)
PartyHasItem("acq17003")
OR(2)
Dead("acq17002")
Dead("acq17003")
Global("SanRetKarli","LOCALS",0)
Delay(10)
THEN
RESPONSE #100
SetGlobal("SanRetKarli","LOCALS",1)
END

IF
GlobalLT("Chapter","Global",14)
OR(2)
Dead("Brage")
Dead("Laryssa")
Global("PCKilledBrage","LOCALS",0)
THEN
RESPONSE #100
StartCutSceneMode()
DisplayStringWait(Myself,23379) // Murderer! You will pay for this!
LeaveParty()
SetGlobal("PCKilledBrage","LOCALS",1)
ChangeAIScript("RTSancop",OVERRIDE)
ChangeAIScript("Fighter3",CLASS)
ChangeAIScript("Pries10b",DEFAULT)
ActionOverride("Pellig",Enemy())
SetGlobal("HaiassJumpOn","GLOBAL",0)
ActionOverride("Haiass",EscapeArea())
Enemy()
AttackOneRound(Player1)
EndCutSceneMode()
END
