IF
NumTimesTalkedTo(0)
InParty("CVSandr")
See([PC])
CombatCounter(0)
THEN
RESPONSE #100
MoveToObject("CVSandr")
StartDialogueNoSet([PC])
END

IF
Global("agberrs","LOCALS",0)
GlobalLT("agberr","GLOBAL",36)
GlobalGT("endofbg1","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("agberrs","LOCALS",1)
Continue()
RESPONSE #3
SetGlobal("agberrs","LOCALS",1)
IncrementGlobal("agberr","GLOBAL",1)
GiveItemCreate("agberr01",Myself,1,0,0) 
Continue()
END


