IF
  True()
THEN
  RESPONSE #100
    CutSceneID("haiass")
    Wait(2)
    DestroySelf()
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneID(Protagonist)
    FadeToColor([20.0],0)
    MoveToPoint([1872.1517])
    Wait(2)
    CreateCreature("haiass3",[1643.1578],1)
    EndCutSceneMode()
END

IF
  True()
THEN
  RESPONSE #100
    ActionOverride("haiass",StartDialogueNoSet(Protagonist))
    DisplayString("haiass",@0)
END
