IF
  True()
THEN
  RESPONSE #100
    CutSceneID("haiass")
    Wait(2)
    DestroySelf()
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneID(Protagonist)
    FadeToColor([20.0],0)
    MoveToPoint([4790.2829])
    Wait(2)
    CreateCreature("haiass4",[4790.2829],1)
    EndCutSceneMode()
END

IF
  True()
THEN
  RESPONSE #100
    ActionOverride("haiass",StartDialogueNoSet(Protagonist))
    DisplayString("haiass",@0)
END
