IF
AttackedBy([GOODCUTOFF],DEFAULT)
OR(2)
!Allegiance(Myself,ENEMY)
Global("shauorcHostile","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("shauorcHostile","GLOBAL",1)
Enemy()
Continue()
END

IF
Allegiance(Myself,ENEMY)
Global("shauorcHostile","GLOBAL",0)
THEN
RESPONSE #100
SetGlobal("shauorcHostile","GLOBAL",1)
END

IF
Global("shauorcHostile","GLOBAL",1)
!Allegiance(Myself,ENEMY)
THEN
RESPONSE #100
Enemy()
END