IF
InParty("CVSandr")
Global("SanAmbKidn","m#ar05",0)
Clicked([ANYONE])
Range(LastTrigger,10)
THEN
RESPONSE #100
DisplayString(Myself,202473) // The window has been broken and a rope fashioned out of bedsheets runs through the hole. You can try to climb down the rope if you wish.
TriggerActivation("M#Climb01",FALSE)
TriggerActivation("M#Climb01b",TRUE)
SetGlobal("SanAmbKidn","m#ar05",1)
ActionOverride("CVSandr",Interact("CVSandr"))
END