IF
	Allegiance(Myself,ENEMY)
	Global("UcmgMatronHostile","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("UcmgMatronHostile","GLOBAL",1)
END

IF
	Global("UcmgMatronHostile","GLOBAL",1)
	!Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Enemy()
END

IF
	AttackedBy([GOODCUTOFF],DEFAULT)
	OR(2)
		!Allegiance(Myself,ENEMY)
		Global("UcmgMatronHostile","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("UcmgMatronHostile","GLOBAL",1)
		Enemy()
		Continue()
END


